In [45]:
import pandas as pd 
import numpy as np
import re
pd.set_option('display.max_columns', None)

In [2]:
data_1 = pd.read_csv("/home/aamin/files/marketing/copy/reports_data/reports_before_nov_dec.csv")
data_2 = pd.read_csv("/home/aamin/files/marketing/copy/reports_data/reports_nov_dec.csv")

/home/aamin/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3106: DtypeWarning: Columns (5,7,12,13,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
/home/aamin/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3106: DtypeWarning: Columns (5,7,12,13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
print(data_1.shape)
print(data_2.shape)

(563927, 23)
(82487, 23)

In [36]:
data_3  = pd.concat([data_1,data_2])

In [37]:
data_3.drop("Unnamed: 0",axis= 1,inplace=True)

In [150]:
data_3

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,category
0,4862,Quess 3105,7550176840,QUESS1164,https://bit.ly/3KWO3qd,2022-05-31 08:02:24,2022-05-31 19:33:50,2022-05-31,08:02:24,8,Tuesday,2022-05-31,19:33:50,19.0,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Idea,Madhya Pradesh-Chattisgarh,en,leads
1,4862,Quess 3105,8920194583,QUESS737,https://bit.ly/3KWO3qd,2022-05-31 08:02:28,2022-05-31 20:18:12,2022-05-31,08:02:28,8,Tuesday,2022-05-31,20:18:12,20.0,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Airtel,Madhya Pradesh-Chattisgarh,en,leads
2,4862,Quess 3105,8860875024,QUESS612,https://bit.ly/3KWO3qd,2022-05-31 08:02:27,2022-06-18 10:50:57,2022-05-31,08:02:27,8,Tuesday,2022-06-18,10:50:57,10.0,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Airtel,Delhi,en,leads
3,5084,RNR Cases 3006,7095924021,RNR544,https://mv343.app.goo.gl/pQxK,2022-06-30 10:13:28,2022-06-30 10:13:38,2022-06-30,10:13:28,10,Thursday,2022-06-30,10:13:38,10.0,"Dear Customer, We noticed your interest in a M...",NaN,Delivered,Delivered,BSNL GSM,Tamil Nadu,en,leads
4,5084,RNR Cases 3006,9494080943,RNR555,https://mv343.app.goo.gl/pQxK,2022-06-30 10:12:14,2022-06-30 10:12:19,2022-06-30,10:12:14,10,Thursday,2022-06-30,10:12:19,10.0,"Dear Customer, We noticed your interest in a M...",NaN,Delivered,Delivered,Vodafone,Chennai,en,leads
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82482,5639,Tie Up Vinolya Hindi 2511,9972363521,VINOLYA197,NaN,2022-11-25 10:56:11,NaN,2022-11-25,10:56:11,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82483,5639,Tie Up Vinolya Hindi 2511,9945768371,VINOLYA481,NaN,2022-11-25 10:56:14,NaN,2022-11-25,10:56:14,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82484,5639,Tie Up Vinolya Hindi 2511,9741814983,VINOLYA1,NaN,2022-11-25 10:56:15,NaN,2022-11-25,10:56:15,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82485,5639,Tie Up Vinolya Hindi 2511,9611708813,VINOLYA301,NaN,2022-11-25 10:56:11,NaN,2022-11-25,10:56:11,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82486,5639,Tie Up Vinolya Hindi 2511,9606157498,VINOLYA429,NaN,2022-11-25 16:56:11,NaN,2022-11-25,16:56:11,16,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,undelivered,expired,Reliance CDMA,North East,hi,NaN

In [50]:
tie_up_data = data_3[data_3["Broadcast name"].str.contains("Tie" , flags= re.IGNORECASE)].copy()

In [62]:
tie_up_data[tie_up_data["Delivered Date"].str.contains("2022")]["SMS Language"].value_counts()

en    129113
hi     39994
Name: SMS Language, dtype: int64

In [67]:
tie_up_data[tie_up_data["SMS Language"] == "en"]["Message"].value_counts()

Dear Customer, Congratulations! As an employee of our exclusive Shubh Saathi partner get attractive offers on our personal loans. Minimum take home salary is Rs.12000. Click here to apply now https://mv343.app.goo.gl/KRTr - Team MyShubhLife    129113
Name: Message, dtype: int64

In [ ]:
# def update_circle(data):
#     if data.loc[(data["Broadcast name"].str.contains("dtss" , flags = re.IGNORECASE)) & (tie_up_data["Broadcast name"].str.contains("hindi", flags= re.IGNORECASE)) & (tie_up_data["Broadcast name"].str.contains("delhi", flags= re.IGNORECASE)) , "Circle"]

In [124]:
tie_up_data.loc[(tie_up_data["Broadcast name"].str.contains("dtss", flags= re.IGNORECASE)) & (tie_up_data["Broadcast name"].str.contains("hindi", flags= re.IGNORECASE)) & (tie_up_data["Broadcast name"].str.contains("delhi", flags= re.IGNORECASE)) , "Circle"] = "Delhi"

In [109]:
tie_up_data.loc[tie_up_data["Broadcast name"].str.contains("Bangalore", flags= re.IGNORECASE) , "Circle"] = "Karnataka"

In [81]:
tie_up_data["Broadcast name"].value_counts()

Tie Up 0209                       83527
Tie Up DTSS Bang English 2511      9786
Tie Up DTSS Bang Hindi 2511        9786
Tie Up DTSS Bang English 0212      9767
Tie Up DTSS Bang Hindi 0212        9220
Tie Up UDS English 2411            5202
UDS Tie Up Hindi 2411              5202
UDS Tie Up Hindi 0512              5026
Tie Up UDS English 0512            5026
Bangalore Tieups 1411              3911
Bangalore Tieups 1311              3911
Tie Up Dtss Delhi English 0512     2814
Tie Up DTSS Delhi Hindi 0512       2814
Tie Up DTSS Hindi 2411             2811
Tie Up Avtar DTSS 2411             2811
Tie Up Cognizant 1609              1560
Tie Up Pragarthi English 2511       831
Tie Up Pragarthi Hindi 2511         831
Tie Up Cognizant 0909               782
Tie Up Vinolya 1609                 781
Tie Up Cognizant 1811               780
Tie Up Congnizant Hindi 0512        779
Tie Up Congnizant English 0612      779
Tie Up Pragathi Hindi 0212          757
Tie Up Pragathi English 0212        757
Tie Up Vinolya English 2511         612
Tie Up Vinolya Hindi 2511           612
Tie Up Vinolya English 0212         611
Tie Up Vinolya Hindi 0212           610
Tie Up Avtar 1609                   375
Tie Up Vinolya 0909                 300
Tie Up Avtar English 2411           289
Tie Up Avtar Hindi 2411             289
Tie Up Avtar English 0512           288
Tie Up Avtar Hindi 0512             288
Tie Up ASPPL 1609                   233
Tie Up ASPPL 0709                   233
Tie Up ASPPL English 0212           231
Tie Up ASPPL Hindi 0212             231
Tie Up ASPPL Hindi 2511             231
Tie Up ASPPL English 2511           231
Tie Up Bluedart Hindi 2511          230
Tie Up Bluedart English 2511        230
Tie Up BlueDart English 0212        229
Tie Up BlueDart Hindi 0212          229
Tie Up DustBucket Hindi 0212         24
Tie Up DustBucket Hindi 2511         24
Tie Up DustBucket English 0212       24
Tie Up DustBucket English 2511       24
Name: Broadcast name, dtype: int64

In [142]:
tie_up_data["Circle"].value_counts()

Karnataka                           67563
Delhi                               40117
Andhra Pradesh                      16407
Mumbai                              11740
Maharashtra-Goa                     11235
Hyderabad                            4680
Chennai                              4170
Tamil Nadu                           3845
Uttar Pradesh (East)                 2515
Bihar-Jharkhand                      1902
Orissa                               1724
-                                    1649
Uttar Pradesh (West)-Uttarakhand     1531
Haryana                              1293
Madhya Pradesh-Chattisgarh           1087
Rajasthan                             990
Tamil Nadu-Chennai                    898
Assam                                 728
Gujarat                               660
West Bengal-Andaman Nicobar           605
Punjab                                523
Kolkata                               355
North East                            231
Jammu-Kashmir                         204
Kerala                                173
Himachal Pradesh                      104
Name: Circle, dtype: int64

In [130]:
tie_up_data[tie_up_data["Circle"] == "Gujarat"]["Broadcast name"].value_counts()

Tie Up 0209    660
Name: Broadcast name, dtype: int64

In [137]:
new_tie_up_data = tie_up_data[tie_up_data["Broadcast name"] != "Tie Up 0209"].copy()

In [151]:
new_tie_up_data.to_csv("tie_up_data.csv")

In [14]:
# data_3['Delivered Year'] = data_3['Delivered Date'].apply(lambda x: x.split('-')[0])
# data_3['Delivered Month'] = data_3['Delivered Date'].apply(lambda x: x.split('-')[1])
# data_3['Delivered Day'] = data_3['Delivered Date'].apply(lambda x: x.split('-')[2])

In [26]:
# data_3[(data_3["Delivered Year"] == "2021") & (data_3['Delivered Month'] == "09")]["Delivered Day"].value_counts()

09    1001
13     953
Name: Delivered Day, dtype: int64

In [27]:
# data_3[(data_3["Delivered Year"] == "2021")]["Delivered Month"].value_counts() #(data_3['Delivered Month'] == "09")]["Delivered Day"].value_counts()

11    258462
09      1954
10       225
Name: Delivered Month, dtype: int64

In [34]:
data_3[data_3["Delivered Date"].str.contains("2022")].shape

(385773, 24)

In [35]:
data_3[data_3["Delivered Date"].str.contains("2022")][["SMS Language","Broadcast name"]].drop_duplicates().groupby(["SMS Language"]).count()

              Broadcast name
SMS Language
en                        64
hi                        19

In [62]:
data_3.to_csv("/home/aamin/files/marketing/copy/reports_data/all_reports_data.csv")

In [68]:
data_4 = pd.read_csv("/home/aamin/files/marketing/copy/final_data/mkting_cmpgn_data_wo_existing_users_3.csv")

In [74]:
data_3["Circle"]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 646414 entries, 0 to 82486
Data columns (total 23 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             646414 non-null  int64
 1   Broadcast ID           646414 non-null  int64
 2   Broadcast name         646414 non-null  object
 3   Mobile number          646414 non-null  int64
 4   Primary Key (User_id)  646414 non-null  object
 5   Link clicked           62633 non-null   object
 6   Delivered Time         646414 non-null  object
 7   Clicked time           62633 non-null   object
 8   Delivered Date         646414 non-null  object
 9   Delivery Time          646414 non-null  object
 10  Hour of Day            646414 non-null  int64
 11  Day of Week            646414 non-null  object
 12  Clicked Date           62633 non-null   object
 13  Click Time             62633 non-null   object
 14  Clicked Hour of Day    62633 non-null   float64
 15  Message                646414 non-null  object
 16  Published date         0 non-null       float64
 17  Status                 646414 non-null  object
 18  Remark                 646414 non-null  object
 19  Operator               646414 non-null  object
 20  Circle                 646414 non-null  object
 21  SMS Language           646414 non-null  object
 22  category               389804 non-null  object
dtypes: float64(2), int64(4), object(17)
memory usage: 118.4+ MB

In [73]:
data_3.groupby(["Circle","SMS Language","Day of Week","Hour of Day"]).count()

                                                                  Unnamed: 0  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                     3
                                                     10                 1645
                                                     11                    4
                                                     12                12459
                                                     13                  302
...                                                                      ...
West Bengal-Andaman Nicobar mr           Saturday    10                   50
                                                     11                    1
                                                     16                    1
                                         Sunday      14                   50
                                                     20                    2

                                                                  Broadcast ID  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                       3
                                                     10                   1645
                                                     11                      4
                                                     12                  12459
                                                     13                    302
...                                                                        ...
West Bengal-Andaman Nicobar mr           Saturday    10                     50
                                                     11                      1
                                                     16                      1
                                         Sunday      14                     50
                                                     20                      2

                                                                  Broadcast name  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                         3
                                                     10                     1645
                                                     11                        4
                                                     12                    12459
                                                     13                      302
...                                                                          ...
West Bengal-Andaman Nicobar mr           Saturday    10                       50
                                                     11                        1
                                                     16                        1
                                         Sunday      14                       50
                                                     20                        2

                                                                  Mobile number  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                        3
                                                     10                    1645
                                                     11                       4
                                                     12                   12459
                                                     13                     302
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10                      50
                                                     11                       1
                                                     16                       1
                                         Sunday      14                      50
                                                     20                       2

                                                                  Primary Key (User_id)  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                                3
                                                     10                            1645
                                                     11                               4
                                                     12                           12459
                                                     13                             302
...                                                                                 ...
West Bengal-Andaman Nicobar mr           Saturday    10                              50
                                                     11                               1
                                                     16                               1
                                         Sunday      14                              50
                                                     20                               2

                                                                  Link clicked  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                       0
                                                     10                      1
                                                     11                      0
                                                     12                    528
                                                     13                      2
...                                                                        ...
West Bengal-Andaman Nicobar mr           Saturday    10                      3
                                                     11                      0
                                                     16                      0
                                         Sunday      14                      3
                                                     20                      0

                                                                  Delivered Time  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                         3
                                                     10                     1645
                                                     11                        4
                                                     12                    12459
                                                     13                      302
...                                                                          ...
West Bengal-Andaman Nicobar mr           Saturday    10                       50
                                                     11                        1
                                                     16                        1
                                         Sunday      14                       50
                                                     20                        2

                                                                  Clicked time  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                       0
                                                     10                      1
                                                     11                      0
                                                     12                    528
                                                     13                      2
...                                                                        ...
West Bengal-Andaman Nicobar mr           Saturday    10                      3
                                                     11                      0
                                                     16                      0
                                         Sunday      14                      3
                                                     20                      0

                                                                  Delivered Date  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                         3
                                                     10                     1645
                                                     11                        4
                                                     12                    12459
                                                     13                      302
...                                                                          ...
West Bengal-Andaman Nicobar mr           Saturday    10                       50
                                                     11                        1
                                                     16                        1
                                         Sunday      14                       50
                                                     20                        2

                                                                  Delivery Time  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                        3
                                                     10                    1645
                                                     11                       4
                                                     12                   12459
                                                     13                     302
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10                      50
                                                     11                       1
                                                     16                       1
                                         Sunday      14                      50
                                                     20                       2

                                                                  Clicked Date  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                       0
                                                     10                      1
                                                     11                      0
                                                     12                    528
                                                     13                      2
...                                                                        ...
West Bengal-Andaman Nicobar mr           Saturday    10                      3
                                                     11                      0
                                                     16                      0
                                         Sunday      14                      3
                                                     20                      0

                                                                  Click Time  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                     0
                                                     10                    1
                                                     11                    0
                                                     12                  528
                                                     13                    2
...                                                                      ...
West Bengal-Andaman Nicobar mr           Saturday    10                    3
                                                     11                    0
                                                     16                    0
                                         Sunday      14                    3
                                                     20                    0

                                                                  Clicked Hour of Day  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                              0
                                                     10                             1
                                                     11                             0
                                                     12                           528
                                                     13                             2
...                                                                               ...
West Bengal-Andaman Nicobar mr           Saturday    10                             3
                                                     11                             0
                                                     16                             0
                                         Sunday      14                             3
                                                     20                             0

                                                                  Message  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                  3
                                                     10              1645
                                                     11                 4
                                                     12             12459
                                                     13               302
...                                                                   ...
West Bengal-Andaman Nicobar mr           Saturday    10                50
                                                     11                 1
                                                     16                 1
                                         Sunday      14                50
                                                     20                 2

                                                                  Published date  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                         0
                                                     10                        0
                                                     11                        0
                                                     12                        0
                                                     13                        0
...                                                                          ...
West Bengal-Andaman Nicobar mr           Saturday    10                        0
                                                     11                        0
                                                     16                        0
                                         Sunday      14                        0
                                                     20                        0

                                                                  Status  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                 3
                                                     10             1645
                                                     11                4
                                                     12            12459
                                                     13              302
...                                                                  ...
West Bengal-Andaman Nicobar mr           Saturday    10               50
                                                     11                1
                                                     16                1
                                         Sunday      14               50
                                                     20                2

                                                                  Remark  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                 3
                                                     10             1645
                                                     11                4
                                                     12            12459
                                                     13              302
...                                                                  ...
West Bengal-Andaman Nicobar mr           Saturday    10               50
                                                     11                1
                                                     16                1
                                         Sunday      14               50
                                                     20                2

                                                                  Operator  \
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                   3
                                                     10               1645
                                                     11                  4
                                                     12              12459
                                                     13                302
...                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                 50
                                                     11                  1
                                                     16                  1
                                         Sunday      14                 50
                                                     20                  2

                                                                  category
Circle                      SMS Language Day of Week Hour of Day
-                           en           Friday      9                   3
                                                     10                  0
                                                     11                  0
                                                     12               1969
                                                     13                  0
...                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                 50
                                                     11                  1
                                                     16                  1
                                         Sunday      14                 50
                                                     20                  2

[2764 rows x 19 columns]

In [146]:
data_5 = pd.read_csv("/home/aamin/files/marketing/final_leads_aggregated_data.csv")

In [147]:
data_5

,SN,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,0,Andhra Pradesh,en,Friday,2,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.000000,240.0,240.000000,240.0,0.000000,0.0,0.000000,0.0,25.000000,25.0,25.000000,25.0,34.000000,34.0,34.000000,34.0
1,1,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0
2,2,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.655128,2.0,19488.448494,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0
3,3,Andhra Pradesh,en,Friday,11,2860,591.0,20.664336,56.0,9.475465,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.969930,240.0,239.969930,240.0,2.446429,2.0,2.634615,2.0,9.020280,16.0,9.020280,16.0,33.996503,34.0,33.996503,34.0
4,4,Andhra Pradesh,en,Friday,12,868,646.0,74.423963,107.0,16.563467,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,263.419355,268.0,263.419355,268.0,7641.570093,25.0,7938.330097,26.0,11.649770,12.0,11.649770,12.0,36.509217,37.0,36.509217,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,2711,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2712,2712,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2713,2713,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2714,2714,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0
2715,2715,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0