In [2]:
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import calendar
pd.set_option('display.max_columns', None)

In [3]:
def convert_to_day_of_week(date_str):
    try:
        date_ = datetime.date.fromisoformat(date_str)
        weekday = calendar.day_name[date_.weekday()]
    except:
        weekday = np.nan
    return weekday

In [4]:
camp_dir_path = r'/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Campaign Data/Reports'
camp_filename_list = []
for path in os.scandir(camp_dir_path):
    if path.is_file():
        camp_filename_list.append(path.name)

In [5]:
camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

camp_path_to_reports = '/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Campaign Data/Reports'

camp_sms_delivery_df = pd.DataFrame()

for file in camp_delvreport_filename_list:
    
    camp_temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
    camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
    
camp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
camp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [6]:
camp_sms_delivery_df['Delivered Date'] = camp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_delivery_df['Delivery Time'] = camp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_delivery_df['Hour of Day'] = camp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_delivery_df['Day of Week'] = camp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
camp_sms_delivery_df['SMS Language'] = 'English'

In [7]:
campp_dir_path = r'/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Campaign Data/Report from 2021'
campp_filename_list = []
for path in os.scandir(campp_dir_path):
    if path.is_file():
        campp_filename_list.append(path.name)

In [8]:
campp_clickreport_filename_list = [i for i in campp_filename_list if 'Click' in i]
campp_delvreport_filename_list = [i for i in campp_filename_list if 'Delivery' in i]

campp_path_to_reports = '/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Campaign Data/Report from 2021'

campp_sms_delivery_df = pd.DataFrame()

for file in campp_delvreport_filename_list:
    
    campp_temp_delivery_df = pd.read_csv(f'{campp_path_to_reports}/{file}')
    campp_sms_delivery_df = pd.concat([campp_sms_delivery_df, campp_temp_delivery_df])
    
campp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
campp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [9]:
campp_sms_delivery_df['Delivered Date'] = campp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
campp_sms_delivery_df['Delivery Time'] = campp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
campp_sms_delivery_df['Hour of Day'] = campp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
campp_sms_delivery_df['Day of Week'] = campp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
campp_sms_delivery_df['SMS Language'] = 'English'

In [10]:
camp_sms_click_df = pd.DataFrame()

for file in camp_clickreport_filename_list:
    
    temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
    camp_sms_click_df = pd.concat([camp_sms_click_df, temp_delivery_df])
    
camp_sms_click_df.reset_index(inplace=True, drop=True)
camp_sms_click_df = camp_sms_click_df[camp_sms_click_df['Delivered Time']!='-']

In [11]:
camp_sms_click_df['Delivered Date'] = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Delivery Time']  = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Hour of Day'] = camp_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_click_df['Day of Week'] = camp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

camp_sms_click_df['Clicked Date'] = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Click Time']  = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Clicked Hour of Day'] = camp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [12]:
camp_sms_dff = pd.merge(camp_sms_click_df, camp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [13]:
campp_sms_click_df = pd.DataFrame()

for file in campp_clickreport_filename_list:
    
    temp_delivery_df = pd.read_csv(f'{campp_path_to_reports}/{file}')
    campp_sms_click_df = pd.concat([campp_sms_click_df, temp_delivery_df])
    
campp_sms_click_df.reset_index(inplace=True, drop=True)
campp_sms_click_df = campp_sms_click_df[campp_sms_click_df['Delivered Time']!='-']

In [14]:
campp_sms_click_df['Delivered Date'] = campp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
campp_sms_click_df['Delivery Time']  = campp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
campp_sms_click_df['Hour of Day'] = campp_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
campp_sms_click_df['Day of Week'] = campp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

campp_sms_click_df['Clicked Date'] = campp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
campp_sms_click_df['Click Time']  = campp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
campp_sms_click_df['Clicked Hour of Day'] = campp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [15]:
campp_sms_dff = pd.merge(campp_sms_click_df, campp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [16]:
comm_dir_path = r'/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Multilingual EMI Reminders/Reports'
comm_filename_list = []
for path in os.scandir(comm_dir_path):
    if path.is_file():
        comm_filename_list.append(path.name)

In [17]:
comm_clickreport_filename_list = [i for i in comm_filename_list if 'Click' in i]
comm_delvreport_filename_list = [i for i in comm_filename_list if 'Delivery' in i]

comm_path_to_reports = '/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Multilingual EMI Reminders/Reports'

comm_sms_delivery_df = pd.DataFrame()

for file in comm_delvreport_filename_list:
    
    comm_temp_delivery_df = pd.read_csv(f'{comm_path_to_reports}/{file}')
    comm_sms_delivery_df = pd.concat([comm_sms_delivery_df, comm_temp_delivery_df])
    
comm_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
comm_sms_delivery_df.reset_index(inplace=True, drop=True)

In [ ]:
comm_sms_delivery_df

In [18]:
comm_sms_delivery_df['Delivered Date'] = comm_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
comm_sms_delivery_df['Delivery Time'] = comm_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
comm_sms_delivery_df['Hour of Day'] = comm_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
comm_sms_delivery_df['Day of Week'] = comm_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
comm_sms_delivery_df['SMS Language'] = comm_sms_delivery_df['Broadcast name'].apply(lambda x: x.split(' - ')[1])

In [19]:
comm_sms_click_df = pd.DataFrame()

for file in comm_clickreport_filename_list:
    
    temp_delivery_df = pd.read_csv(f'{comm_path_to_reports}/{file}')
    comm_sms_click_df = pd.concat([comm_sms_click_df, temp_delivery_df])
    
comm_sms_click_df.reset_index(inplace=True, drop=True)
comm_sms_click_df = comm_sms_click_df[comm_sms_click_df['Delivered Time']!='-']

In [20]:
comm_sms_click_df['Delivered Date'] = comm_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
comm_sms_click_df['Delivery Time']  = comm_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
comm_sms_click_df['Hour of Day'] = comm_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
comm_sms_click_df['Day of Week'] = comm_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

comm_sms_click_df['Clicked Date'] = comm_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
comm_sms_click_df['Click Time']  = comm_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
comm_sms_click_df['Clicked Hour of Day'] = comm_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [21]:
comm_sms_dff = pd.merge(comm_sms_click_df, comm_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [22]:
all_sms = pd.concat([camp_sms_dff, campp_sms_dff, comm_sms_dff])
all_sms.reset_index(drop=True, inplace=True)

In [23]:
all_sms.columns

Index(['Broadcast ID', 'Broadcast name', 'Mobile number',
       'Primary Key (User_id)', 'Link clicked', 'Delivered Time',
       'Clicked time', 'Delivered Date', 'Delivery Time', 'Hour of Day',
       'Day of Week', 'Clicked Date', 'Click Time', 'Clicked Hour of Day',
       'Message', 'Published date', 'Status', 'Remark', 'Operator', 'Circle',
       'SMS Language', 'Unnamed: 0', 'myshubhlife',
       'myshubhlife-Latitude-7480', '26.07.2022 14:48',
       'file:///home/myshubhlife/.config/libreoffice/4;'],
      dtype='object')

In [24]:
all_sms = all_sms.drop(['Unnamed: 0', 'myshubhlife',
                           'myshubhlife-Latitude-7480', '26.07.2022 14:48',
                           'file:///home/myshubhlife/.config/libreoffice/4;'], axis=1)

In [25]:
cmpgn_category_df = pd.read_csv('click_rate_cmpgn_wise.csv', usecols=[0,1,2])

In [26]:
all_sms = all_sms.merge(cmpgn_category_df[['Broadcast name','category']], on='Broadcast name', how='left')

In [27]:
all_sms['category'].value_counts()

leads             389804
existing users     93880
Name: category, dtype: int64

In [28]:
all_sms

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,category
0,4408.0,MUTHOOT GOLD LOAN 1403,9.980895e+09,GOLD300,https://bit.ly/3mLPezq,2022-03-14 10:00:33,2022-03-14 10:00:36,2022-03-14,10:00:33,10,Monday,2022-03-14,10:00:36,10,"Dear [NAME] As a valued MyShubhLife customer, ...",NaN,Delivered,Delivered,Reliance JIO,Delhi,English,existing users
1,4408.0,MUTHOOT GOLD LOAN 1403,9.205702e+09,GOLD136,https://bit.ly/3mLPezq,2022-03-14 10:00:33,2022-03-14 11:08:32,2022-03-14,10:00:33,10,Monday,2022-03-14,11:08:32,11,"Dear [NAME] As a valued MyShubhLife customer, ...",NaN,Delivered,Delivered,Reliance JIO,Delhi,English,existing users
2,4408.0,MUTHOOT GOLD LOAN 1403,9.036523e+09,GOLD201,https://bit.ly/3mLPezq,2022-03-14 10:00:34,2022-03-14 10:00:37,2022-03-14,10:00:34,10,Monday,2022-03-14,10:00:37,10,"Dear [NAME] As a valued MyShubhLife customer, ...",NaN,Delivered,Delivered,Airtel,Chennai,English,existing users
3,4408.0,MUTHOOT GOLD LOAN 1403,9.591796e+09,GOLD203,https://bit.ly/3mLPezq,2022-03-14 10:00:34,2022-03-14 10:00:41,2022-03-14,10:00:34,10,Monday,2022-03-14,10:00:41,10,"Dear [NAME] As a valued MyShubhLife customer, ...",NaN,Delivered,Delivered,Vodafone,Assam,English,existing users
4,4408.0,MUTHOOT GOLD LOAN 1403,9.587904e+09,GOLD153,https://bit.ly/3mLPezq,2022-03-14 10:00:33,2022-03-14 10:00:38,2022-03-14,10:00:33,10,Monday,2022-03-14,10:00:38,10,"Dear [NAME] As a valued MyShubhLife customer, ...",NaN,Delivered,Delivered,Idea,Delhi,English,existing users
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657802,754.0,Non Delinquent NACH Inactive Reminder - Hindi ...,9.718899e+09,3628244.0,NaN,2022-03-09 14:00:54,NaN,2022-03-09,14:00:54,14,Wednesday,NaN,NaN,NaN,"प्रिय [NAME], आपको यह सूचित किया जाता है कि आप...",2022-03-09 14:00:30,undelivered,DLT Template Failure,Idea,Delhi,Hindi,existing users
657803,754.0,Non Delinquent NACH Inactive Reminder - Hindi ...,7.041693e+09,2926443.0,NaN,2021-01-04 16:43:30,NaN,2021-01-04,16:43:30,16,Monday,NaN,NaN,NaN,"प्रिय [NAME], आपको यह सूचित किया जाता है कि आप...",2021-01-04 16:42:31,Delivered,Delivered,Unitech Infrastructures,Gujarat,Hindi,existing users
657804,754.0,Non Delinquent NACH Inactive Reminder - Hindi ...,9.811034e+09,3582791.0,NaN,2021-10-04 14:00:22,NaN,2021-10-04,14:00:22,14,Monday,NaN,NaN,NaN,"प्रिय [NAME], आपको यह सूचित किया जाता है कि आप...",2021-10-04 14:00:02,Delivered,Delivered,Reliance JIO,Delhi,Hindi,existing users
657805,754.0,Non Delinquent NACH Inactive Reminder - Hindi ...,8.826019e+09,3650504.0,NaN,2021-11-04 14:00:18,NaN,2021-11-04,14:00:18,14,Thursday,NaN,NaN,NaN,"प्रिय [NAME], आपको यह सूचित किया जाता है कि आप...",2021-11-04 14:00:01,Delivered,Delivered,Airtel,Delhi,Hindi,existing users
657806,754.0,Non Delinquent NACH Inactive Reminder - Hindi ...,8.448360e+09,3725519.0,NaN,2022-04-09 14:00:24,NaN,2022-04-09,14:00:24,14,Saturday,NaN,NaN,NaN,"प्रिय [NAME], आपको यह सूचित किया जाता है कि आप...",2022-04-09 14:00:08,undelivered,undelivered,Reliance CDMA,Mumbai,Hindi,existing users

In [29]:
all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,category
60,5504.0,RBH Dussehra New Customers 0510,8.095473e+09,TIE250,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:41,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:41,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English,NaN
61,5504.0,RBH Dussehra New Customers 0510,9.972572e+09,TIE499,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English,NaN
62,5504.0,RBH Dussehra New Customers 0510,8.867518e+09,TIE555,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:42,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:42,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English,NaN
63,5504.0,RBH Dussehra New Customers 0510,9.986135e+09,TIE518,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:47,2022-10-05 10:44:19,2022-10-05,10:28:47,10,Wednesday,2022-10-05,10:44:19,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,BSNL GSM,Karnataka,English,NaN
64,5504.0,RBH Dussehra New Customers 0510,8.050241e+09,TIE759,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585113,3169.0,Bangalore Tieups 1411,9.341838e+09,BANGALORE3102,NaN,2021-11-14 14:03:06,NaN,2021-11-14,14:03:06,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance CDMA,Karnataka,English,leads
585114,3169.0,Bangalore Tieups 1411,9.731078e+09,BANGALORE1474,NaN,2021-11-14 14:03:22,NaN,2021-11-14,14:03:22,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English,leads
585115,3169.0,Bangalore Tieups 1411,8.217085e+09,BANGALORE2732,NaN,2021-11-14 14:04:14,NaN,2021-11-14,14:04:14,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English,leads
585116,3169.0,Bangalore Tieups 1411,8.496879e+09,BANGALORE400,NaN,2021-11-14 14:03:03,NaN,2021-11-14,14:03:03,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Vodafone,Karnataka,English,leads
585117,3169.0,Bangalore Tieups 1411,9.611899e+09,BANGALORE1427,NaN,2021-11-14 20:03:20,NaN,2021-11-14,20:03:20,20,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,undelivered,undelivered,Idea,Karnataka,English,leads

In [30]:
df_to_use = all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

In [31]:
df_to_use.drop(['category'], axis=1, inplace=True)

/home/myshubhlife/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [32]:
df_to_use

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language
60,5504.0,RBH Dussehra New Customers 0510,8.095473e+09,TIE250,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:41,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:41,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English
61,5504.0,RBH Dussehra New Customers 0510,9.972572e+09,TIE499,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English
62,5504.0,RBH Dussehra New Customers 0510,8.867518e+09,TIE555,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:42,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:42,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English
63,5504.0,RBH Dussehra New Customers 0510,9.986135e+09,TIE518,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:47,2022-10-05 10:44:19,2022-10-05,10:28:47,10,Wednesday,2022-10-05,10:44:19,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,BSNL GSM,Karnataka,English
64,5504.0,RBH Dussehra New Customers 0510,8.050241e+09,TIE759,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585113,3169.0,Bangalore Tieups 1411,9.341838e+09,BANGALORE3102,NaN,2021-11-14 14:03:06,NaN,2021-11-14,14:03:06,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance CDMA,Karnataka,English
585114,3169.0,Bangalore Tieups 1411,9.731078e+09,BANGALORE1474,NaN,2021-11-14 14:03:22,NaN,2021-11-14,14:03:22,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English
585115,3169.0,Bangalore Tieups 1411,8.217085e+09,BANGALORE2732,NaN,2021-11-14 14:04:14,NaN,2021-11-14,14:04:14,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English
585116,3169.0,Bangalore Tieups 1411,8.496879e+09,BANGALORE400,NaN,2021-11-14 14:03:03,NaN,2021-11-14,14:03:03,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Vodafone,Karnataka,English
585117,3169.0,Bangalore Tieups 1411,9.611899e+09,BANGALORE1427,NaN,2021-11-14 20:03:20,NaN,2021-11-14,20:03:20,20,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,undelivered,undelivered,Idea,Karnataka,English

def convert_df_for_delivery(df):
    
    df_copy = df.copy()
    
    for i, row in df_copy.iterrows():
        if (row['Clicked Date'] == row['Clicked Date']) and (row['Message'] != row['Message']):
            df_copy.at[i, 'Status'] = 'Delivered'
            df_copy.at[i, 'Remark'] = 'Delivered'
            df_copy.at[i, 'Message'] = df_copy['Message'].value_counts().index[0]
            df_copy.at[i, 'Operator'] = df_copy['Operator'].value_counts().index[0]
            df_copy.at[i, 'Circle'] = df_copy['Circle'].value_counts().index[0]
            df_copy.at[i, 'SMS Language'] = df_copy['SMS Language'].value_counts().index[0]
            #df_copy.at[i, 'SMS Length'] = len(row['Message'])
            
    for i, row in df_copy.iterrows():
        df_copy.at[i, 'SMS Length'] = len(row['Message'])
    
    return df_copy

mob_nums = df_to_use[df_to_use['Message']!=df_to_use['Message']]['Mobile number'].unique().tolist()
to_impute = df_to_use[df_to_use['Mobile number'].isin(mob_nums)]
no_impute = df_to_use[~df_to_use['Mobile number'].isin(mob_nums)]

mob_nums

groupby_df = to_impute.groupby(['Mobile number',
                              'Primary Key (User_id)'
                             ]).apply(convert_df_for_delivery)

groupby_df

groupby_df2 = groupby_df.droplevel(level=0)
groupby_df2.reset_index(drop=True, inplace=True)

prepared_df = pd.concat([groupby_df2, no_impute]).reset_index(drop=True)

In [33]:
df = df_to_use[df_to_use['Circle']!='-']
df = df[df['Operator']!='-']

In [34]:
df['SMS Length'] = df['Message'].apply(lambda x: len(x) if x==x else np.nan)

In [35]:
df.shape

(557341, 22)

In [36]:
import time
from datetime import datetime
from dateutil import parser

def func_UTCToEpoch(utcData, timestampFormat=None):
    if timestampFormat == None:
        dateObj    = parser.parse(utcData)
        epochValue = dateObj.timestamp()
    else:
        timeTuple  = time.strptime(utcData, timestampFormat)
        epochValue = time.mktime(timeTuple)
    return (epochValue)

In [37]:
import dateutil.relativedelta

def calculate_timelag(delv_time, click_time):
    
    if click_time == click_time:
        delv_time_ts = datetime.fromtimestamp(func_UTCToEpoch(delv_time))
        click_time_ts = datetime.fromtimestamp(func_UTCToEpoch(click_time))
        diff = click_time_ts - delv_time_ts
        seconds = diff.total_seconds()
    
    else:
        seconds = np.nan
    
    return seconds

In [38]:
df['Timelag (s)'] = df.apply(lambda x: calculate_timelag(x['Delivered Time'], x['Clicked time']), axis=1)

In [39]:
df = df[~(df['Timelag (s)'] < -10)]

In [40]:
df['Timelag (s)'] = df['Timelag (s)'].apply(lambda x: abs(x) if x==x else np.nan)

In [41]:
#df['SMS Length'] = len(df['Message'])
df['Num SMS Sent'] = np.ceil(df['SMS Length']/160)
df['Cost of All SMS Sent'] = 0.13 * df['Num SMS Sent']

In [42]:
df['Num words in SMS'] = df['Message'].apply(lambda x: len(x.split(' ')))

In [43]:
df

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,SMS Length,Timelag (s),Num SMS Sent,Cost of All SMS Sent,Num words in SMS
60,5504.0,RBH Dussehra New Customers 0510,8.095473e+09,TIE250,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:41,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:41,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English,286,2.0,2.0,0.26,44
61,5504.0,RBH Dussehra New Customers 0510,9.972572e+09,TIE499,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English,286,4.0,2.0,0.26,44
62,5504.0,RBH Dussehra New Customers 0510,8.867518e+09,TIE555,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:39,2022-10-05 10:28:42,2022-10-05,10:28:39,10,Wednesday,2022-10-05,10:28:42,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Airtel,Karnataka,English,286,3.0,2.0,0.26,44
63,5504.0,RBH Dussehra New Customers 0510,9.986135e+09,TIE518,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:47,2022-10-05 10:44:19,2022-10-05,10:28:47,10,Wednesday,2022-10-05,10:44:19,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,BSNL GSM,Karnataka,English,286,932.0,2.0,0.26,44
64,5504.0,RBH Dussehra New Customers 0510,8.050241e+09,TIE759,https://mv343.app.goo.gl/pQxK,2022-10-05 10:28:41,2022-10-05 10:28:45,2022-10-05,10:28:41,10,Wednesday,2022-10-05,10:28:45,10,This is the time to celebrate the triumph of g...,NaN,Delivered,Delivered,Vodafone,Karnataka,English,286,4.0,2.0,0.26,44
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585113,3169.0,Bangalore Tieups 1411,9.341838e+09,BANGALORE3102,NaN,2021-11-14 14:03:06,NaN,2021-11-14,14:03:06,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance CDMA,Karnataka,English,282,NaN,2.0,0.26,31
585114,3169.0,Bangalore Tieups 1411,9.731078e+09,BANGALORE1474,NaN,2021-11-14 14:03:22,NaN,2021-11-14,14:03:22,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English,282,NaN,2.0,0.26,31
585115,3169.0,Bangalore Tieups 1411,8.217085e+09,BANGALORE2732,NaN,2021-11-14 14:04:14,NaN,2021-11-14,14:04:14,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,English,282,NaN,2.0,0.26,31
585116,3169.0,Bangalore Tieups 1411,8.496879e+09,BANGALORE400,NaN,2021-11-14 14:03:03,NaN,2021-11-14,14:03:03,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Vodafone,Karnataka,English,282,NaN,2.0,0.26,31
585117,3169.0,Bangalore Tieups 1411,9.611899e+09,BANGALORE1427,NaN,2021-11-14 20:03:20,NaN,2021-11-14,20:03:20,20,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,undelivered,undelivered,Idea,Karnataka,English,282,NaN,2.0,0.26,31

In [44]:
def convert_to_day_of_month(date_str):
    try:
        day_of_mon = datetime.fromtimestamp(func_UTCToEpoch(date_str)).day
    except:
        day_of_mon = np.nan
    return day_of_mon

In [45]:
df['Day of Month'] = df['Delivered Date'].apply(convert_to_day_of_month)

In [46]:
def mean_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    mean = np.nanmean(x_upd)
    return mean

def median_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    median = np.nanmedian(x_upd)
    return median

In [47]:
timelag = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Timelag (s)'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
timelag.rename(columns= {'mean': 'Avg Timelag (s)',
                        'median': 'Median Timelag (s)',
                         'mean_wo_0': 'Avg Timelag (s) wo 0',
                        'median_wo_0': 'Median Timelag (s) wo 0',
                        }, inplace=True)

<ipython-input-46-1f399104b8e5>:3: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(x_upd)
/home/myshubhlife/anaconda3/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,

In [48]:
num_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_sms.rename(columns= {'mean': 'Avg Num SMS Sent',
                        'median': 'Median Num SMS Sent',
                        'mean_wo_0': 'Avg Num SMS Sent wo 0',
                        'median_wo_0': 'Median Num SMS Sent wo 0',
                        }, inplace=True)

In [49]:
cost_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Cost of All SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
cost_sms.rename(columns= {'mean': 'Avg Cost of All SMS Sent',
                        'median': 'Median Cost of All SMS Sent',
                         'mean_wo_0': 'Avg Cost of All SMS Sent wo 0',
                        'median_wo_0': 'Median Cost of All SMS Sent wo 0'}, inplace=True)

In [50]:
len_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['SMS Length'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
len_sms.rename(columns= {'mean': 'Avg SMS Length',
                        'median': 'Median SMS Length',
                        'mean_wo_0': 'Avg SMS Length wo 0',
                        'median_wo_0': 'Median SMS Length wo 0'}, inplace=True)

In [51]:
day_of_mon = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Day of Month'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
day_of_mon.rename(columns= {'mean': 'Avg Day of Month',
                        'median': 'Median Day of Month',
                           'mean_wo_0': 'Avg Day of Month wo 0',
                        'median_wo_0': 'Median Day of Month wo 0'}, inplace=True)

In [52]:
num_words = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num words in SMS'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_words.rename(columns= {'mean': 'Avg Num Words',
                        'median': 'Median Num Words',
                          'mean_wo_0': 'Avg Num Words wo 0',
                        'median_wo_0': 'Median Num Words wo 0'}, inplace=True)

In [53]:
new_features = pd.merge(num_sms,cost_sms, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,len_sms, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,timelag, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,day_of_mon, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,num_words, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

In [54]:
new_features.fillna(0, inplace = True)

In [55]:
new_features

                                                     Avg Num SMS Sent  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                        2.0
                                        10                        2.0
                                        11                        2.0
                                        12                        2.0
                                        13                        2.0
...                                                               ...
West Bengal-Andaman Nicobar Wednesday   15                        2.0
                                        16                        2.0
                                        19                        2.0
                                        21                        2.0
                                        22                        2.0

                                                     Median Num SMS Sent  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                           2.0
                                        10                           2.0
                                        11                           2.0
                                        12                           2.0
                                        13                           2.0
...                                                                  ...
West Bengal-Andaman Nicobar Wednesday   15                           2.0
                                        16                           2.0
                                        19                           2.0
                                        21                           2.0
                                        22                           2.0

                                                     Avg Num SMS Sent wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                             2.0
                                        10                             2.0
                                        11                             2.0
                                        12                             2.0
                                        13                             2.0
...                                                                    ...
West Bengal-Andaman Nicobar Wednesday   15                             2.0
                                        16                             2.0
                                        19                             2.0
                                        21                             2.0
                                        22                             2.0

                                                     Median Num SMS Sent wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                                2.0
                                        10                                2.0
                                        11                                2.0
                                        12                                2.0
                                        13                                2.0
...                                                                       ...
West Bengal-Andaman Nicobar Wednesday   15                                2.0
                                        16                                2.0
                                        19                                2.0
                                        21                                2.0
                                        22                                2.0

                                                     Avg Cost of All SMS Sent  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                               0.26
                                        10                               0.26
                                        11                               0.26
                                        12                               0.26
                                        13                               0.26
...                                                                       ...
West Bengal-Andaman Nicobar Wednesday   15                               0.26
                                        16                               0.26
                                        19                               0.26
                                        21                               0.26
                                        22                               0.26

                                                     Median Cost of All SMS Sent  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                                  0.26
                                        10                                  0.26
                                        11                                  0.26
                                        12                                  0.26
                                        13                                  0.26
...                                                                          ...
West Bengal-Andaman Nicobar Wednesday   15                                  0.26
                                        16                                  0.26
                                        19                                  0.26
                                        21                                  0.26
                                        22                                  0.26

                                                     Avg Cost of All SMS Sent wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                                    0.26
                                        10                                    0.26
                                        11                                    0.26
                                        12                                    0.26
                                        13                                    0.26
...                                                                            ...
West Bengal-Andaman Nicobar Wednesday   15                                    0.26
                                        16                                    0.26
                                        19                                    0.26
                                        21                                    0.26
                                        22                                    0.26

                                                     Median Cost of All SMS Sent wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                                       0.26
                                        10                                       0.26
                                        11                                       0.26
                                        12                                       0.26
                                        13                                       0.26
...                                                                               ...
West Bengal-Andaman Nicobar Wednesday   15                                       0.26
                                        16                                       0.26
                                        19                                       0.26
                                        21                                       0.26
                                        22                                       0.26

                                                     Avg SMS Length  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09               197.000000
                                        10               239.972196
                                        11               239.961573
                                        12               264.432692
                                        13               258.666667
...                                                             ...
West Bengal-Andaman Nicobar Wednesday   15               163.000000
                                        16               231.000000
                                        19               202.857143
                                        21               197.000000
                                        22               231.000000

                                                     Median SMS Length  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                       197.0
                                        10                       240.0
                                        11                       240.0
                                        12                       268.0
                                        13                       268.0
...                                                                ...
West Bengal-Andaman Nicobar Wednesday   15                       163.0
                                        16                       231.0
                                        19                       197.0
                                        21                       197.0
                                        22                       231.0

                                                     Avg SMS Length wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                    197.000000
                                        10                    239.972196
                                        11                    239.961573
                                        12                    264.432692
                                        13                    258.666667
...                                                                  ...
West Bengal-Andaman Nicobar Wednesday   15                    163.000000
                                        16                    231.000000
                                        19                    202.857143
                                        21                    197.000000
                                        22                    231.000000

                                                     Median SMS Length wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                            197.0
                                        10                            240.0
                                        11                            240.0
                                        12                            268.0
                                        13                            268.0
...                                                                     ...
West Bengal-Andaman Nicobar Wednesday   15                            163.0
                                        16                            231.0
                                        19                            197.0
                                        21                            197.0
                                        22                            231.0

                                                     Avg Timelag (s)  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09               2497.259740
                                        10              15765.801282
                                        11                  2.794118
                                        12               7713.801887
                                        13                  0.000000
...                                                              ...
West Bengal-Andaman Nicobar Wednesday   15                  0.000000
                                        16                  0.000000
                                        19                 35.100000
                                        21                  0.000000
                                        22                  0.000000

                                                     Median Timelag (s)  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                          3.0
                                        10                          2.0
                                        11                          2.0
                                        12                         25.5
                                        13                          0.0
...                                                                 ...
West Bengal-Andaman Nicobar Wednesday   15                          0.0
                                        16                          0.0
                                        19                          4.0
                                        21                          0.0
                                        22                          0.0

                                                     Avg Timelag (s) wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                    2497.259740
                                        10                   19488.629160
                                        11                       2.968750
                                        12                    8016.303922
                                        13                       0.000000
...                                                                   ...
West Bengal-Andaman Nicobar Wednesday   15                       0.000000
                                        16                       0.000000
                                        19                      39.000000
                                        21                       0.000000
                                        22                       0.000000

                                                     Median Timelag (s) wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                               3.0
                                        10                               2.0
                                        11                               2.5
                                        12                              27.0
                                        13                               0.0
...                                                                      ...
West Bengal-Andaman Nicobar Wednesday   15                               0.0
                                        16                               0.0
                                        19                               4.0
                                        21                               0.0
                                        22                               0.0

                                                     Avg Day of Month  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                  24.000000
                                        10                   2.014225
                                        11                   7.080429
                                        12                  11.331731
                                        13                  11.000000
...                                                               ...
West Bengal-Andaman Nicobar Wednesday   15                   8.000000
                                        16                  11.000000
                                        19                  22.114286
                                        21                  22.000000
                                        22                  11.000000

                                                     Median Day of Month  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                          24.0
                                        10                           2.0
                                        11                           2.0
                                        12                          12.0
                                        13                          12.0
...                                                                  ...
West Bengal-Andaman Nicobar Wednesday   15                           8.0
                                        16                          11.0
                                        19                          22.0
                                        21                          22.0
                                        22                          11.0

                                                     Avg Day of Month wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                       24.000000
                                        10                        2.014225
                                        11                        7.080429
                                        12                       11.331731
                                        13                       11.000000
...                                                                    ...
West Bengal-Andaman Nicobar Wednesday   15                        8.000000
                                        16                       11.000000
                                        19                       22.114286
                                        21                       22.000000
                                        22                       11.000000

                                                     Median Day of Month wo 0  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09                               24.0
                                        10                                2.0
                                        11                                2.0
                                        12                               12.0
                                        13                               12.0
...                                                                       ...
West Bengal-Andaman Nicobar Wednesday   15                                8.0
                                        16                               11.0
                                        19                               22.0
                                        21                               22.0
                                        22                               11.0

                                                     Avg Num Words  \
Circle                      Day of Week Hour of Day
Andhra Pradesh              Friday      09               29.000000
                                        10               33.996767
                                        11               33.995532
                                        12               36.617788
                                        13               36.000000
...                                                            ...
West Bengal-Andaman Nicobar Wednesday   15               22.000000
                                        16               32.000000
                                        19               30.185714
                                        21               29.000000
                                        22               32.000000


In [56]:
circle_df = pd.DataFrame(df.groupby(by = ['Circle', 
                                          #'Operator',
                                          'SMS Language','Day of Week','Hour of Day']).Status.count())
circle_df.rename(columns= {'Status': 'sms_sent'}, inplace=True)
circle_df

                                                                  sms_sent
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                461
                                                     10              13919
                                                     11               2238
                                                     12                832
                                                     13                 12
...                                                                    ...
West Bengal-Andaman Nicobar English      Wednesday   15                  9
                                                     16                  7
                                                     19                 70
                                                     21                  1
                                                     22                  1

[1768 rows x 1 columns]

In [57]:
circle_delv= pd.DataFrame(df[df['Status']=='Delivered'].groupby(by = ['Circle','SMS Language','Day of Week','Hour of Day']).Status.count())
circle_delv.rename(columns= {'Status': 'sms_delivered'}, inplace=True)
circle_delv

                                                                  sms_delivered
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                     438
                                                     10                    7784
                                                     11                     366
                                                     12                     633
                                                     13                      10
...                                                                         ...
West Bengal-Andaman Nicobar English      Wednesday   13                       4
                                                     14                       3
                                                     16                       5
                                                     19                      64
                                                     21                       1

[1418 rows x 1 columns]

In [58]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [59]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [60]:
circle_delv_rate_df.fillna(0, inplace = True)
circle_delv_rate_df['delivery_rate'] = circle_delv_rate_df['sms_delivered']*100 / circle_delv_rate_df['sms_sent']
circle_delv_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                461
                                                     10              13919
                                                     11               2238
                                                     12                832
                                                     13                 12
...                                                                    ...
West Bengal-Andaman Nicobar English      Wednesday   15                  9
                                                     16                  7
                                                     19                 70
                                                     21                  1
                                                     22                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                   438.0
                                                     10                  7784.0
                                                     11                   366.0
                                                     12                   633.0
                                                     13                    10.0
...                                                                         ...
West Bengal-Andaman Nicobar English      Wednesday   15                     0.0
                                                     16                     5.0
                                                     19                    64.0
                                                     21                     1.0
                                                     22                     0.0

                                                                  delivery_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09               95.010846
                                                     10               55.923558
                                                     11               16.353887
                                                     12               76.081731
                                                     13               83.333333
...                                                                         ...
West Bengal-Andaman Nicobar English      Wednesday   15                0.000000
                                                     16               71.428571
                                                     19               91.428571
                                                     21              100.000000
                                                     22                0.000000

[1768 rows x 3 columns]

In [61]:
click= pd.DataFrame(df[df['Clicked Date']==df['Clicked Date']].groupby(by = ['Circle', 'SMS Language',
                                                                                           'Day of Week','Hour of Day']
                                                                                    ).Status.count())
click.rename(columns= {'Status': 'sms_clicked'}, inplace=True)
click

                                                                  sms_clicked
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                    77
                                                     10                   780
                                                     11                    34
                                                     12                   106
                                                     14                     3
...                                                                       ...
West Bengal-Andaman Nicobar English      Wednesday   09                    64
                                                     10                     3
                                                     13                     2
                                                     14                     1
                                                     19                    10

[910 rows x 1 columns]

In [62]:
click_rate_df = pd.merge(circle_delv_rate_df,click, how= 'outer', 
                         on = ['Circle','SMS Language','Day of Week','Hour of Day'])
click_rate_df.fillna(0, inplace = True)
click_rate_df['clicked_rate'] = click_rate_df['sms_clicked']*100 / click_rate_df['sms_delivered']
click_rate_df.fillna(0, inplace = True)
click_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                461
                                                     10              13919
                                                     11               2238
                                                     12                832
                                                     13                 12
...                                                                    ...
West Bengal-Andaman Nicobar English      Wednesday   15                  9
                                                     16                  7
                                                     19                 70
                                                     21                  1
                                                     22                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                   438.0
                                                     10                  7784.0
                                                     11                   366.0
                                                     12                   633.0
                                                     13                    10.0
...                                                                         ...
West Bengal-Andaman Nicobar English      Wednesday   15                     0.0
                                                     16                     5.0
                                                     19                    64.0
                                                     21                     1.0
                                                     22                     0.0

                                                                  delivery_rate  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09               95.010846
                                                     10               55.923558
                                                     11               16.353887
                                                     12               76.081731
                                                     13               83.333333
...                                                                         ...
West Bengal-Andaman Nicobar English      Wednesday   15                0.000000
                                                     16               71.428571
                                                     19               91.428571
                                                     21              100.000000
                                                     22                0.000000

                                                                  sms_clicked  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09                  77.0
                                                     10                 780.0
                                                     11                  34.0
                                                     12                 106.0
                                                     13                   0.0
...                                                                       ...
West Bengal-Andaman Nicobar English      Wednesday   15                   0.0
                                                     16                   0.0
                                                     19                  10.0
                                                     21                   0.0
                                                     22                   0.0

                                                                  clicked_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              English      Friday      09              17.579909
                                                     10              10.020555
                                                     11               9.289617
                                                     12              16.745656
                                                     13               0.000000
...                                                                        ...
West Bengal-Andaman Nicobar English      Wednesday   15               0.000000
                                                     16               0.000000
                                                     19              15.625000
                                                     21               0.000000
                                                     22               0.000000

[1768 rows x 5 columns]

In [65]:
final_df = pd.merge(click_rate_df,new_features, how= 'outer', 
               on = ['Circle',
                     #'SMS Language',
                     'Day of Week','Hour of Day'])

In [66]:
final_df = final_df.reset_index()

In [67]:
final_df

,Circle,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,Friday,09,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0
1,Andhra Pradesh,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0
2,Andhra Pradesh,Friday,11,2238,366.0,16.353887,34.0,9.289617,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.961573,240.0,239.961573,240.0,2.794118,2.0,2.968750,2.5,7.080429,2.0,7.080429,2.0,33.995532,34.0,33.995532,34.0
3,Andhra Pradesh,Friday,12,832,633.0,76.081731,106.0,16.745656,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,264.432692,268.0,264.432692,268.0,7713.801887,25.5,8016.303922,27.0,11.331731,12.0,11.331731,12.0,36.617788,37.0,36.617788,37.0
4,Andhra Pradesh,Friday,13,12,10.0,83.333333,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.666667,268.0,258.666667,268.0,0.000000,0.0,0.000000,0.0,11.000000,12.0,11.000000,12.0,36.000000,37.0,36.000000,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1763,West Bengal-Andaman Nicobar,Wednesday,15,9,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,163.000000,163.0,163.000000,163.0,0.000000,0.0,0.000000,0.0,8.000000,8.0,8.000000,8.0,22.000000,22.0,22.000000,22.0
1764,West Bengal-Andaman Nicobar,Wednesday,16,7,5.0,71.428571,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,231.000000,231.0,231.000000,231.0,0.000000,0.0,0.000000,0.0,11.000000,11.0,11.000000,11.0,32.000000,32.0,32.000000,32.0
1765,West Bengal-Andaman Nicobar,Wednesday,19,70,64.0,91.428571,10.0,15.625000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,202.857143,197.0,202.857143,197.0,35.100000,4.0,39.000000,4.0,22.114286,22.0,22.114286,22.0,30.185714,29.0,30.185714,29.0
1766,West Bengal-Andaman Nicobar,Wednesday,21,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,0.000000,0.0,0.000000,0.0,22.000000,22.0,22.000000,22.0,29.000000,29.0,29.000000,29.0
1767,West Bengal-Andaman Nicobar,Wednesday,22,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,231.000000,231.0,231.000000,231.0,0.000000,0.0,0.000000,0.0,11.000000,11.0,11.000000,11.0,32.000000,32.0,32.000000,32.0

In [68]:
final_df['SN'] = np.arange(0,1768).tolist()

final_df.to_csv('mkting_cmpgn_data_wo_existing_users.csv', index=False)