In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
data  = pd.read_csv("/home/aamin/files/marketing/copy/Jupiter_files/testm.csv")

In [5]:
data.drop("Unnamed: 0",axis = 1, inplace= True)

In [22]:
data["profiledata_mobile"].nunique()

29180

In [13]:
data.drop_duplicates("profiledata_mobile", keep="first")

,profiledata_mobile,userid,applieddate,loandetail_amount,status,loandetail_status
0,8688889935,35894,2017-06-28,33000.0,DATASIGNS_APPROVED,DISBURSED
1,9844678626,35138,2019-11-15,NaN,DATASIGNS_REJECTED,NaN
5,9430166990,35068,2017-06-24,NaN,NON_SERVICEABLE,NaN
6,7386034408,58854,2018-07-08,NaN,DATASIGNS_REJECTED,NaN
7,7406433048,34878,2019-12-18,NaN,DATASIGNS_REJECTED,NaN
...,...,...,...,...,...,...
46670,9476000018,1142587,2022-10-12,5000.0,DATASIGNS_APPROVED,DISBURSED
46673,9113596561,3874590,2022-12-28,NaN,DATASIGNS_REJECTED,NaN
46675,9365720644,3604232,2023-01-09,NaN,INCOMPLETE_INFO,NaN
46678,8579830197,4173446,2022-09-14,100000.0,DATASIGNS_APPROVED,DISBURSED
46679,9890021475,3701718,2021-11-16,75000.0,DATASIGNS_APPROVED,DISBURSED

In [24]:
data[data["applieddate"].str.contains("2023") & (data["status"] == "DATASIGNS_APPROVED" )]

,profiledata_mobile,userid,applieddate,loandetail_amount,status,loandetail_status
41095,8867593287,4371428,2023-01-05,50000.0,DATASIGNS_APPROVED,DISBURSED
41307,7300039961,3687748,2023-01-03,NaN,DATASIGNS_APPROVED,NaN
41382,8858708998,3781631,2023-01-04,10000.0,DATASIGNS_APPROVED,DISBURSED
41458,8317486346,2094969,2023-01-03,10000.0,DATASIGNS_APPROVED,DISBURSED
41486,8420173156,3775386,2023-01-06,10000.0,DATASIGNS_APPROVED,DISBURSED
41622,6393621504,3816339,2023-01-08,10000.0,DATASIGNS_APPROVED,DISBURSED
41746,8367678268,3735790,2023-01-04,67000.0,DATASIGNS_APPROVED,DISBURSED
41789,9791318106,3938314,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
42089,7438014296,4263538,2023-01-02,85000.0,DATASIGNS_APPROVED,DISBURSED
42353,9502097727,2770332,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
42360,7983166056,3308838,2023-01-08,10000.0,DATASIGNS_APPROVED,DISBURSED
42384,8093938085,3729687,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
42435,8953761815,3864119,2023-01-12,NaN,DATASIGNS_APPROVED,NaN
42671,9686549162,2612236,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
42676,8140639887,3710655,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
42679,8896265524,3674931,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
42691,7012531707,3903980,2023-01-11,NaN,DATASIGNS_APPROVED,NaN
42999,8073879045,4379025,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
43086,8692803358,2557158,2023-01-06,25000.0,DATASIGNS_APPROVED,DISBURSED
43572,9323068369,3677079,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
43579,8951388240,3692337,2023-01-11,NaN,DATASIGNS_APPROVED,NaN
43596,9550729219,3929186,2023-01-11,10000.0,DATASIGNS_APPROVED,DISBURSED
43618,7906039320,3708716,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
44600,9933068513,4363736,2023-01-03,20000.0,DATASIGNS_APPROVED,DISBURSED
44903,8902602862,3335809,2023-01-01,10000.0,DATASIGNS_APPROVED,DISBURSED
44926,7738274308,3675023,2023-01-01,10000.0,DATASIGNS_APPROVED,DISBURSED
44989,8309178376,3932240,2023-01-03,8000.0,DATASIGNS_APPROVED,DISBURSED
45002,9045333711,3747142,2023-01-02,20000.0,DATASIGNS_APPROVED,DISBURSED
45023,9066375350,4344492,2023-01-05,40000.0,DATASIGNS_APPROVED,DISBURSED
45104,8249261545,3930437,2023-01-06,15000.0,DATASIGNS_APPROVED,DISBURSED
45164,7067796961,3961838,2023-01-04,NaN,DATASIGNS_APPROVED,NaN
45294,7975868425,3869672,2023-01-09,NaN,DATASIGNS_APPROVED,NaN
45346,7012498575,3950956,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
45471,9717815572,3915032,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
45501,8918642841,3782241,2023-01-06,NaN,DATASIGNS_APPROVED,NaN
45825,9738401900,4377374,2023-01-09,50000.0,DATASIGNS_APPROVED,DISBURSED
45859,9625828588,749604,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
45961,9971604374,3864523,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
46020,9391740596,4166724,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
46087,6296904075,759560,2023-01-12,NaN,DATASIGNS_APPROVED,NaN
46101,9591256834,3753541,2023-01-11,NaN,DATASIGNS_APPROVED,NaN
46195,9902276410,2389751,2023-01-05,200000.0,DATASIGNS_APPROVED,DISBURSED
46277,9657432054,474669,2023-01-12,NaN,DATASIGNS_APPROVED,NaN
46283,8959171457,3947048,2023-01-04,20000.0,DATASIGNS_APPROVED,DISBURSED
46301,8709004879,4368178,2023-01-02,100000.0,DATASIGNS_APPROVED,DISBURSED
46422,8779191671,4006322,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED
46452,9052463512,843405,2023-01-10,5000.0,DATASIGNS_APPROVED,DISBURSED
46508,9126448547,4366376,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
46547,8450991289,3701062,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
46573,9606323463,3717946,2023-01-12,NaN,DATASIGNS_APPROVED,NaN
46618,9768357981,3232117,2023-01-08,NaN,DATASIGNS_APPROVED,NaN
46644,8682034622,3925837,2023-01-10,10000.0,DATASIGNS_APPROVED,DISBURSED

In [18]:
data[data["status"] == "DATASIGNS_APPROVED"].sort_values("applieddate").drop_duplicates("profiledata_mobile",keep = "first")

,profiledata_mobile,userid,applieddate,loandetail_amount,status,loandetail_status
970,7411112797,4851,2017-01-16,33000.0,DATASIGNS_APPROVED,DISBURSED
1423,9845353703,4849,2017-01-18,33000.0,DATASIGNS_APPROVED,CUST_NOT_INTERESTED
969,9986629658,5112,2017-01-19,100000.0,DATASIGNS_APPROVED,CLOSED
603,9632288267,5520,2017-01-23,30000.0,DATASIGNS_APPROVED,WRITTEN_OFF
376,9916995511,4571,2017-01-26,100000.0,DATASIGNS_APPROVED,WRITTEN_OFF
...,...,...,...,...,...,...
42360,7983166056,3308838,2023-01-08,10000.0,DATASIGNS_APPROVED,DISBURSED
45825,9738401900,4377374,2023-01-09,50000.0,DATASIGNS_APPROVED,DISBURSED
46508,9126448547,4366376,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
42671,9686549162,2612236,2023-01-10,NaN,DATASIGNS_APPROVED,NaN
46101,9591256834,3753541,2023-01-11,NaN,DATASIGNS_APPROVED,NaN