In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import calendar
pd.set_option('display.max_columns', None)

from langdetect import detect

In [2]:
def convert_to_day_of_week(date_str):
    try:
        date_ = datetime.date.fromisoformat(date_str)
        weekday = calendar.day_name[date_.weekday()]
    except:
        weekday = np.nan
    return weekday

#### Reports

In [4]:
# camp_dir_path = r'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/1148818'
# camp_filename_list = []
# for path in os.scandir(camp_dir_path):
#     if path.is_file():
#         camp_filename_list.append(path.name)

In [124]:
main_camp_dir_path = r'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'
camp_filename_list = []

for folder_name in os.listdir(main_camp_dir_path):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    for path in os.scandir(camp_dir_path):
        if path.is_file():
            camp_filename_list.append(path.name)

camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

camp_sms_delivery_df = pd.DataFrame()
for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_delvreport_filename_list):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    camp_temp_delivery_df = pd.read_csv(f'{camp_dir_path}/{file}')
    camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
camp_sms_delivery_df = camp_sms_delivery_df.drop_duplicates()

camp_sms_click_df = pd.DataFrame()
for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_clickreport_filename_list):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    camp_temp_click_df = pd.read_csv(f'{camp_dir_path}/{file}')
    camp_sms_click_df = pd.concat([camp_sms_click_df, camp_temp_click_df])
camp_sms_click_df = camp_sms_click_df.drop_duplicates()

In [6]:
# camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
# camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

# camp_path_to_reports = '/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'

# camp_sms_delivery_df = pd.DataFrame()

# for file in camp_delvreport_filename_list:
    
#     camp_temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
#     camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
    
# camp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
# camp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [7]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS")]["Broadcast ID"].unique()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS") & (camp_sms_delivery_df["Broadcast name"].str.contains("English"))]["Broadcast name"].unique()

In [9]:
# df = camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") | (camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212" )]

In [10]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast ID"].str.contains("DTSS")]["Broadcast name"].unique()

In [125]:
camp_sms_delivery_df['Delivered Date'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[0])
camp_sms_delivery_df['Delivery Time'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[1])
camp_sms_delivery_df['Hour of Day'] = camp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_delivery_df['Day of Week'] = camp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
camp_sms_delivery_df['SMS Language'] = camp_sms_delivery_df["Message"].apply(lambda x: detect(x))

In [5]:
# camp_sms_delivery_df.to_csv("reports_nov_dec.csv")

In [15]:
broadcast_name_data = pd.read_csv("/home/aamin/files/marketing/copy/Shubh Saathi - Campaign Tracker.xlsx - Sheet1.csv")

In [19]:
broadcast_name_data = broadcast_name_data.iloc[1:]

In [42]:
broadcast_name_data

,S No,Region,Partner/ Company,Data Received,Duplicate Data,SMS Campaign- 1,Unnamed: 6,Unnamed: 7,Unnamed: 8,Whatsapp Campaign-1,Unnamed: 10,Unnamed: 11,SMS Campaign- 2,Unnamed: 13,Unnamed: 14,Unnamed: 15,Whatsapp Campaign-2,Unnamed: 17,Unnamed: 18,SMS Campaign- 3,Unnamed: 20,Unnamed: 21,Unnamed: 22,Whatsapp Campaign-3,Unnamed: 24,Unnamed: 25,Whatsapp Campaign-4,Unnamed: 27,Unnamed: 28,Whatsapp Campaign-5,Unnamed: 30,Unnamed: 31,Application,Approvals,Disbursals,Approval%,Disbursal%
1,1.0,Karnataka,DTSS,10228.0,302.0,08 Nov,9926,460,4.52%,10 Nov,460,338,12 Nov,9926,328,3.30%,14 Nov,372,263,24 Nov,9926,336,3.39%,21 Nov,85,63,29 Nov,621,447,6 Dec,776,578,214.0,84.0,81.0,39.25%,37.85%
2,2.0,Karnataka,Dust Bucket,24.0,0.0,08 Nov,24,NaN,NaN,10 Nov,NaN,NaN,12 Nov,24,NaN,NaN,NaN,NaN,NaN,24 Nov,24,2,8.33%,NaN,NaN,NaN,29 Nov,3,2,6 Dec,4,3,0.0,0.0,0.0,0.00%,0.00%
3,3.0,Karnataka,Bluedart,234.0,8.0,08 Nov,226,NaN,NaN,10 Nov,NaN,NaN,12 Nov,226,NaN,NaN,NaN,NaN,NaN,24 Nov,226,15,6.64%,NaN,NaN,NaN,29 Nov,31,23,6 Dec,21,13,3.0,0.0,0.0,0,0
4,4.0,Karnataka,Pragathi HR services,846.0,75.0,08 Nov,771,39,5.06%,10 Nov,39,35,12 Nov,768,32,4.17%,NaN,NaN,NaN,24 Nov,764,27,3.53%,NaN,NaN,NaN,29 Nov,91,79,6 Dec,353,267,4.0,0.0,0.0,0,0
5,5.0,Delhi,UDS,5279.0,222.0,25 Oct,5057,633,12.52%,NaN,NaN,NaN,11 Nov,5057,524,10.36%,NaN,NaN,NaN,24 Nov,5202,780,14.99%,NaN,NaN,NaN,26 Nov,780,643,7 Dec,661,500,33.0,2.0,1.0,6.06%,3.03%
6,6.0,Delhi,DTSS,3552.0,706.0,9 Aug,2846,332,11.67%,NaN,NaN,NaN,13 Aug,2846,293,10.30%,NaN,NaN,NaN,24 Nov,2811,436,15.51%,NaN,NaN,NaN,25 Nov,435,343,7 Dec,328,241,30.0,2.0,2.0,6.67%,6.67%
7,7.0,Delhi,Avtar Steels Ltd,291.0,2.0,06 Sep,289,25,8.65%,NaN,NaN,NaN,16 Sep,289,21,7.27%,NaN,NaN,NaN,03 Oct,287,25,8.71%,NaN,NaN,NaN,27 Nov,40,31,7 Dec,45,37,3.0,0.0,0.0,0,0
8,8.0,Karnataka,ASPPL,244.0,3.0,07 Sep,241,16,6.64%,NaN,NaN,NaN,16 Sep,241,9,3.73%,NaN,NaN,NaN,23 Sep,239,15,6.28%,NaN,NaN,NaN,29 Nov,50,38,6 Dec,34,25,7.0,0.0,0.0,0,0
9,9.0,Karnataka,UNISERVICE APARTMENT SOLUTIONS LLP,864.0,14.0,19 Dec,850,142,16.70%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,3.0,2.0,37.50%,25.00%
10,10.0,Karnataka,Vinolya,782.0,159.0,09 Sep,623,27,4.33%,NaN,NaN,NaN,16 Sep,623,22,3.53%,NaN,NaN,NaN,24 Sep,623,36,5.78%,NaN,NaN,NaN,29 Nov,91,79,6 Dec,34,24,11.0,8.0,8.0,72.73%,72.73%
11,11.0,Hyderabad,Cognizant Technology,780.0,0.0,09 Sep,780,26,3.33%,NaN,NaN,NaN,16 Sep,780,26,3.33%,NaN,NaN,NaN,24 Sep,780,35,4.49%,NaN,NaN,NaN,NaN,NaN,NaN,8 Dec,69,50,0.0,0.0,0.0,0,0

In [32]:
import re

In [57]:
camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains(broadcast_name_data["Partner/ Company"].iloc[9].replace(" ",""), flags= re.IGNORECASE) == True , "Circle"] = broadcast_name_data["Region"].iloc[9]

In [121]:
camp_sms_delivery_df.loc[(camp_sms_delivery_df["Broadcast name"].str.contains("dtss", flags= re.IGNORECASE) == True)  &
                         (camp_sms_delivery_df["Broadcast name"].str.contains("hindi", flags= re.IGNORECASE) == True) &
                         (camp_sms_delivery_df["Broadcast name"].str.contains("bang", flags= re.IGNORECASE) == False)  
                         , ["Circle","Broadcast name"]] = ""

Empty DataFrame
Columns: [Circle, Broadcast name]
Index: []

In [127]:
camp_sms_delivery_df[camp_sms_delivery_df["Broadcast ID"] == 5698]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Message,Published date,Delivered time,Status,Remark,Operator,Circle,Delivered Date,Delivery Time,Hour of Day,Day of Week,SMS Language
0,5698,Tie Up Congnizant English 0612,9032946484,RBH778,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:12,undelivered,number invalid,Tata GSM,Andhra Pradesh,2022-12-06,13:02:12,13,Tuesday,en
1,5698,Tie Up Congnizant English 0612,9491895551,RBH730,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:12,Delivered,Delivered,BSNL GSM,Andhra Pradesh,2022-12-06,13:02:12,13,Tuesday,en
2,5698,Tie Up Congnizant English 0612,9966098236,RBH724,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:11,Delivered,Delivered,Reliance JIO,Andhra Pradesh,2022-12-06,13:02:11,13,Tuesday,en
3,5698,Tie Up Congnizant English 0612,9581236136,RBH58,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:11,undelivered,undelivered,Vodafone,Andhra Pradesh,2022-12-06,13:02:11,13,Tuesday,en
4,5698,Tie Up Congnizant English 0612,8374647476,RBH74,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:52:14,undelivered,number invalid,Airtel,Andhra Pradesh,2022-12-06,13:52:14,13,Tuesday,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774,5698,Tie Up Congnizant English 0612,9959182928,RBH384,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:13,Delivered,Delivered,Airtel,Andhra Pradesh,2022-12-06,13:02:13,13,Tuesday,en
775,5698,Tie Up Congnizant English 0612,8886886849,RBH324,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:11,not sent,number on DND,Vodafone,Andhra Pradesh,2022-12-06,13:02:11,13,Tuesday,en
776,5698,Tie Up Congnizant English 0612,9440707525,RBH310,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:12,Delivered,Delivered,Reliance JIO,Andhra Pradesh,2022-12-06,13:02:12,13,Tuesday,en
777,5698,Tie Up Congnizant English 0612,9849798215,RBH308,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:11,not sent,number on DND,Airtel,Andhra Pradesh,2022-12-06,13:02:11,13,Tuesday,en
778,5698,Tie Up Congnizant English 0612,9949920012,RBH300,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-06 13:02:12,Delivered,Delivered,Reliance JIO,Andhra Pradesh,2022-12-06,13:02:12,13,Tuesday,en

In [64]:
camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains(broadcast_name_data["Partner/ Company"].iloc[6].replace(" ",""))]

Empty DataFrame
Columns: [Broadcast ID, Broadcast name, Mobile number, Primary Key (User_id), Message, Published date, Delivered time, Status, Remark, Operator, Circle, Delivered Date, Delivery Time, Hour of Day, Day of Week, SMS Language]
Index: []

In [88]:
camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains("Cognizant", flags= re.IGNORECASE)]["Broadcast name"].value_counts()

Tie Up Cognizant 1811    780
Tie Up Cognizant 1609    780
Tie Up Cognizant 0909    391
Name: Broadcast name, dtype: int64

In [108]:
camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains("dtss", flags= re.IGNORECASE)]["Circle"].value_counts()

Karnataka                           38571
Delhi                                9774
Uttar Pradesh (West)-Uttarakhand      326
Haryana                               292
Rajasthan                             185
Uttar Pradesh (East)                  172
West Bengal-Andaman Nicobar           115
Bihar-Jharkhand                        81
Mumbai                                 69
Madhya Pradesh-Chattisgarh             43
-                                      41
Punjab                                 27
Gujarat                                20
Jammu-Kashmir                          20
Maharashtra-Goa                        12
Kolkata                                11
Orissa                                 10
Himachal Pradesh                        9
Kerala                                  8
Assam                                   7
Andhra Pradesh                          7
Tamil Nadu                              4
Chennai                                 2
North East                              2
Tamil Nadu-Chennai                      1
Name: Circle, dtype: int64

In [115]:
camp_sms_delivery_df["Circle"].value_counts()

Karnataka                           46130
Delhi                               31384
Hyderabad                            3509
Uttar Pradesh (West)-Uttarakhand      326
Haryana                               292
Rajasthan                             185
Uttar Pradesh (East)                  172
West Bengal-Andaman Nicobar           115
Bihar-Jharkhand                        81
Mumbai                                 69
Madhya Pradesh-Chattisgarh             43
-                                      41
Punjab                                 27
Gujarat                                20
Jammu-Kashmir                          20
Maharashtra-Goa                        12
Kolkata                                11
Orissa                                 10
Himachal Pradesh                        9
Kerala                                  8
Andhra Pradesh                          7
Assam                                   7
Tamil Nadu                              4
Chennai                                 2
North East                              2
Tamil Nadu-Chennai                      1
Name: Circle, dtype: int64

In [112]:
camp_sms_delivery_df[camp_sms_delivery_df["Circle"] == "Haryana"]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Message,Published date,Delivered time,Status,Remark,Operator,Circle,Delivered Date,Delivery Time,Hour of Day,Day of Week,SMS Language
4,5632,Tie Up DTSS Hindi 2411,7011334118,DTSS1426,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 19:10:14,Delivered,Delivered,Idea,Haryana,2022-11-24,19:10:14,19,Thursday,hi
9,5632,Tie Up DTSS Hindi 2411,8860866019,DTSS1409,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 17:11:16,Delivered,Delivered,Idea,Haryana,2022-11-24,17:11:16,17,Thursday,hi
10,5632,Tie Up DTSS Hindi 2411,9996957694,DTSS1389,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:26:43,Delivered,Delivered,Vodafone,Haryana,2022-11-24,16:26:43,16,Thursday,hi
30,5632,Tie Up DTSS Hindi 2411,9001645487,DTSS1431,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 17:11:15,Delivered,Delivered,Idea,Haryana,2022-11-24,17:11:15,17,Thursday,hi
35,5632,Tie Up DTSS Hindi 2411,9521144427,DTSS1363,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:26:43,Delivered,Delivered,Vodafone,Haryana,2022-11-24,16:26:43,16,Thursday,hi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2763,5632,Tie Up DTSS Hindi 2411,8094903619,DTSS1936,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:40:32,Delivered,Delivered,Vodafone,Haryana,2022-11-24,16:40:32,16,Thursday,hi
2778,5632,Tie Up DTSS Hindi 2411,8127387291,DTSS2423,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:26:50,Delivered,Delivered,Airtel,Haryana,2022-11-24,16:26:50,16,Thursday,hi
2781,5632,Tie Up DTSS Hindi 2411,9871273697,DTSS2467,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:26:31,Delivered,Delivered,Idea,Haryana,2022-11-24,16:26:31,16,Thursday,hi
2782,5632,Tie Up DTSS Hindi 2411,9306699767,DTSS2430,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:27:04,Delivered,Delivered,Vodafone,Haryana,2022-11-24,16:27:04,16,Thursday,hi
2804,5632,Tie Up DTSS Hindi 2411,7985081181,DTSS1000,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,2022-11-24 16:26:44,Delivered,Delivered,Airtel,Haryana,2022-11-24,16:26:44,16,Thursday,hi

In [13]:
camp_sms_delivery_df.columns = camp_sms_delivery_df.columns.str.replace('Delivered time', 'Delivered Time')

In [ ]:
# camp_sms_delivery_df["SMS Language"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"].shape

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Circle"] == "-")]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Circle"] == "-")]["Remark"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212")]

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Remark"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16") & ("")]["Operator"].value_counts().to_frame()

In [98]:
camp_sms_click_df = camp_sms_click_df[camp_sms_click_df["Delivered Time"] != "-"]

In [99]:
camp_sms_click_df['Delivered Date'] = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Delivery Time']  = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Hour of Day'] = camp_sms_click_df['Delivery Time'].apply(lambda x:  x.split(':')[0] )
camp_sms_click_df['Day of Week'] = camp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

camp_sms_click_df['Clicked Date'] = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Click Time']  = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Clicked Hour of Day'] = camp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Hour of Day"] != "12")]["Remark"].value_counts()

In [ ]:
# camp_sms_click_df[camp_sms_click_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]

In [139]:
camp_sms_dff = pd.merge(camp_sms_click_df, camp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='inner')

In [ ]:
### we don't have the circle and 


# camp_sms_dff[camp_sms_dff["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Clicked Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_dff[camp_sms_dff["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Circle"].value_counts()

In [108]:
df = camp_sms_dff[camp_sms_dff['Circle']!='-']
df = df[df['Operator']!='-']

In [109]:
df['SMS Length'] = df['Message'].apply(lambda x: len(x) if x==x else np.nan)

In [110]:
df.shape, camp_sms_dff.shape

((70320, 22), (82487, 21))

In [112]:
import time
from datetime import datetime
from dateutil import parser

def func_UTCToEpoch(utcData, timestampFormat=None):
    if timestampFormat == None:
        dateObj    = parser.parse(utcData)
        epochValue = dateObj.timestamp()
    else:
        timeTuple  = time.strptime(utcData, timestampFormat)
        epochValue = time.mktime(timeTuple)
    return (epochValue)

In [113]:
import dateutil.relativedelta

def calculate_timelag(delv_time, click_time):
    
    if click_time == click_time:
        delv_time_ts = datetime.fromtimestamp(func_UTCToEpoch(delv_time))
        click_time_ts = datetime.fromtimestamp(func_UTCToEpoch(click_time))
        diff = click_time_ts - delv_time_ts
        seconds = diff.total_seconds()
    
    else:
        seconds = np.nan
    
    return seconds

In [114]:
df['Timelag (s)'] = df.apply(lambda x: calculate_timelag(x['Delivered Time'], x['Clicked time']), axis=1)

In [115]:
df = df[~(df['Timelag (s)'] < -10)]

In [116]:
df['Timelag (s)'] = df['Timelag (s)'].apply(lambda x: abs(x) if x==x else np.nan)

In [117]:
#df['SMS Length'] = len(df['Message'])
df['Num SMS Sent'] = np.ceil(df['SMS Length']/160)
df['Cost of All SMS Sent'] = 0.13 * df['Num SMS Sent'] #  cost_of_sms

In [118]:
df['Num words in SMS'] = df['Message'].apply(lambda x: len(x.split(' ')))

In [119]:
def convert_to_day_of_month(date_str):
    try:
        day_of_mon = datetime.fromtimestamp(func_UTCToEpoch(date_str)).day
    except:
        day_of_mon = np.nan
    return day_of_mon

In [120]:
df['Day of Month'] = df['Delivered Date'].apply(convert_to_day_of_month)

In [121]:
def mean_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    mean = np.nanmean(x_upd)
    return mean

def median_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    median = np.nanmedian(x_upd)
    return median

In [122]:
timelag = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Timelag (s)'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
timelag.rename(columns= {'mean': 'Avg Timelag (s)',
                        'median': 'Median Timelag (s)',
                         'mean_wo_0': 'Avg Timelag (s) wo 0',
                        'median_wo_0': 'Median Timelag (s) wo 0',
                        }, inplace=True)

/tmp/ipykernel_11845/3554248693.py:3: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(x_upd)
/home/aamin/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,

In [123]:
num_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_sms.rename(columns= {'mean': 'Avg Num SMS Sent',
                        'median': 'Median Num SMS Sent',
                        'mean_wo_0': 'Avg Num SMS Sent wo 0',
                        'median_wo_0': 'Median Num SMS Sent wo 0',
                        }, inplace=True)

In [124]:
cost_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Cost of All SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
cost_sms.rename(columns= {'mean': 'Avg Cost of All SMS Sent',
                        'median': 'Median Cost of All SMS Sent',
                         'mean_wo_0': 'Avg Cost of All SMS Sent wo 0',
                        'median_wo_0': 'Median Cost of All SMS Sent wo 0'}, inplace=True)

In [125]:
len_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['SMS Length'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
len_sms.rename(columns= {'mean': 'Avg SMS Length',
                        'median': 'Median SMS Length',
                        'mean_wo_0': 'Avg SMS Length wo 0',
                        'median_wo_0': 'Median SMS Length wo 0'}, inplace=True)

In [126]:
day_of_mon = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Day of Month'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
day_of_mon.rename(columns= {'mean': 'Avg Day of Month',
                        'median': 'Median Day of Month',
                           'mean_wo_0': 'Avg Day of Month wo 0',
                        'median_wo_0': 'Median Day of Month wo 0'}, inplace=True)

In [127]:
num_words = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num words in SMS'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_words.rename(columns= {'mean': 'Avg Num Words',
                        'median': 'Median Num Words',
                          'mean_wo_0': 'Avg Num Words wo 0',
                        'median_wo_0': 'Median Num Words wo 0'}, inplace=True)

In [128]:
new_features = pd.merge(num_sms,cost_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,len_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,timelag, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,day_of_mon, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,num_words, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [129]:
new_features.fillna(0, inplace = True)

In [130]:
new_features

                                                                  Avg Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                        2.0
                                                     11                        2.0
                                                     12                        2.0
                                                     13                        2.0
                                                     14                        2.0
...                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                        2.0
                                                     17                        2.0
                                                     18                        2.0
                                                     22                        2.0
                                                     23                        2.0

                                                                  Median Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                           2.0
                                                     11                           2.0
                                                     12                           2.0
                                                     13                           2.0
                                                     14                           2.0
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                           2.0
                                                     17                           2.0
                                                     18                           2.0
                                                     22                           2.0
                                                     23                           2.0

                                                                  Avg Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                             2.0
                                                     11                             2.0
                                                     12                             2.0
                                                     13                             2.0
                                                     14                             2.0
...                                                                                 ...
West Bengal-Andaman Nicobar hi           Thursday    16                             2.0
                                                     17                             2.0
                                                     18                             2.0
                                                     22                             2.0
                                                     23                             2.0

                                                                  Median Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                2.0
                                                     11                                2.0
                                                     12                                2.0
                                                     13                                2.0
                                                     14                                2.0
...                                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                                2.0
                                                     17                                2.0
                                                     18                                2.0
                                                     22                                2.0
                                                     23                                2.0

                                                                  Avg Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                               0.26
                                                     11                               0.26
                                                     12                               0.26
                                                     13                               0.26
                                                     14                               0.26
...                                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                               0.26
                                                     17                               0.26
                                                     18                               0.26
                                                     22                               0.26
                                                     23                               0.26

                                                                  Median Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                  0.26
                                                     11                                  0.26
                                                     12                                  0.26
                                                     13                                  0.26
                                                     14                                  0.26
...                                                                                       ...
West Bengal-Andaman Nicobar hi           Thursday    16                                  0.26
                                                     17                                  0.26
                                                     18                                  0.26
                                                     22                                  0.26
                                                     23                                  0.26

                                                                  Avg Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                    0.26
                                                     11                                    0.26
                                                     12                                    0.26
                                                     13                                    0.26
                                                     14                                    0.26
...                                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                                    0.26
                                                     17                                    0.26
                                                     18                                    0.26
                                                     22                                    0.26
                                                     23                                    0.26

                                                                  Median Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                       0.26
                                                     11                                       0.26
                                                     12                                       0.26
                                                     13                                       0.26
                                                     14                                       0.26
...                                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                                       0.26
                                                     17                                       0.26
                                                     18                                       0.26
                                                     22                                       0.26
                                                     23                                       0.26

                                                                  Avg SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                      240
                                                     11                      240
                                                     12                      240
                                                     13                      240
                                                     14                      240
...                                                                          ...
West Bengal-Andaman Nicobar hi           Thursday    16                      261
                                                     17                      261
                                                     18                      261
                                                     22                      261
                                                     23                      261

                                                                  Median SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                         240
                                                     11                         240
                                                     12                         240
                                                     13                         240
                                                     14                         240
...                                                                             ...
West Bengal-Andaman Nicobar hi           Thursday    16                         261
                                                     17                         261
                                                     18                         261
                                                     22                         261
                                                     23                         261

                                                                  Avg SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                           240
                                                     11                           240
                                                     12                           240
                                                     13                           240
                                                     14                           240
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                           261
                                                     17                           261
                                                     18                           261
                                                     22                           261
                                                     23                           261

                                                                  Median SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                              240
                                                     11                              240
                                                     12                              240
                                                     13                              240
                                                     14                              240
...                                                                                  ...
West Bengal-Andaman Nicobar hi           Thursday    16                              261
                                                     17                              261
                                                     18                              261
                                                     22                              261
                                                     23                              261

                                                                  Avg Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  0.000000
                                                     11                  2.000000
                                                     12                  5.000000
                                                     13                  0.000000
                                                     14                 23.758621
...                                                                           ...
West Bengal-Andaman Nicobar hi           Thursday    16                  9.777778
                                                     17                  0.000000
                                                     18                  0.000000
                                                     22                  0.000000
                                                     23                  0.000000

                                                                  Median Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                          0.0
                                                     11                          2.0
                                                     12                          5.0
                                                     13                          0.0
                                                     14                          4.0
...                                                                              ...
West Bengal-Andaman Nicobar hi           Thursday    16                          8.0
                                                     17                          0.0
                                                     18                          0.0
                                                     22                          0.0
                                                     23                          0.0

                                                                  Avg Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                       0.000000
                                                     11                       2.200000
                                                     12                       5.000000
                                                     13                       0.000000
                                                     14                      23.758621
...                                                                                ...
West Bengal-Andaman Nicobar hi           Thursday    16                       9.777778
                                                     17                       0.000000
                                                     18                       0.000000
                                                     22                       0.000000
                                                     23                       0.000000

                                                                  Median Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                               0.0
                                                     11                               2.0
                                                     12                               5.0
                                                     13                               0.0
                                                     14                               4.0
...                                                                                   ...
West Bengal-Andaman Nicobar hi           Thursday    16                               8.0
                                                     17                               0.0
                                                     18                               0.0
                                                     22                               0.0
                                                     23                               0.0

                                                                  Avg Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                       25.0
                                                     11                       16.0
                                                     12                       19.0
                                                     13                       16.0
                                                     14                       18.0
...                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                       24.0
                                                     17                       24.0
                                                     18                       24.0
                                                     22                       24.0
                                                     23                       24.0

                                                                  Median Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                          25.0
                                                     11                          16.0
                                                     12                          16.0
                                                     13                          16.0
                                                     14                          18.0
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                          24.0
                                                     17                          24.0

In [47]:
circle_df = pd.DataFrame(df.groupby(by = ['Circle', 
                                          #'Operator',
                                        'SMS Language',
                                          'Day of Week','Hour of Day']).Status.count())
circle_df.rename(columns= {'Status': 'sms_sent'}, inplace=True)
circle_df

                                                                  sms_sent
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

[864 rows x 1 columns]

In [48]:
circle_delv= pd.DataFrame(df[df['Status']=='Delivered'].groupby(by = ['Circle',
                                                                      'SMS Language',
                                                                      'Day of Week','Hour of Day']).Status.count())
circle_delv.rename(columns= {'Status': 'sms_delivered'}, inplace=True)
circle_delv

                                                                  sms_delivered
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      11                     225
                                                     12                      13
                                                     14                     245
                                                     15                     132
                                                     16                     335
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    10                     156
                                                     11                       3
                                                     13                       1
                                                     16                      93
                                                     17                       2

[549 rows x 1 columns]

In [49]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [50]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [51]:
circle_delv_rate_df.fillna(0, inplace = True)
circle_delv_rate_df['delivery_rate'] = circle_delv_rate_df['sms_delivered']*100 / circle_delv_rate_df['sms_sent']
circle_delv_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                     0.0
                                                     11                   225.0
                                                     12                    13.0
                                                     13                     0.0
                                                     14                   245.0
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                    93.0
                                                     17                     2.0
                                                     18                     0.0
                                                     22                     0.0
                                                     23                     0.0

                                                                  delivery_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                0.000000
                                                     11               36.173633
                                                     12               36.111111
                                                     13                0.000000
                                                     14               42.241379
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16               86.111111
                                                     17               25.000000
                                                     18                0.000000
                                                     22                0.000000
                                                     23                0.000000

[864 rows x 3 columns]

In [54]:
click= pd.DataFrame(df[df['Clicked Date']==df['Clicked Date']].groupby(by = ['Circle', 'SMS Language',
                                                                                           'Day of Week','Hour of Day']
                                                                                    ).Status.count())
click.rename(columns= {'Status': 'sms_clicked'}, inplace=True)
click

                                                                  sms_clicked
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      11                    22
                                                     12                     1
                                                     14                    29
                                                     15                    12
                                                     16                    24
...                                                                       ...
West Bengal-Andaman Nicobar hi           Friday      15                     1
                                                     17                     1
                                         Monday      12                    25
                                         Thursday    10                    18
                                                     16                     9

[246 rows x 1 columns]

In [55]:
click_rate_df = pd.merge(circle_delv_rate_df,click, how= 'outer', 
                         on = ['Circle','SMS Language','Day of Week','Hour of Day'])
click_rate_df.fillna(0, inplace = True)
click_rate_df['clicked_rate'] = click_rate_df['sms_clicked']*100 / click_rate_df['sms_delivered']
click_rate_df.fillna(0, inplace = True)
click_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                     0.0
                                                     11                   225.0
                                                     12                    13.0
                                                     13                     0.0
                                                     14                   245.0
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                    93.0
                                                     17                     2.0
                                                     18                     0.0
                                                     22                     0.0
                                                     23                     0.0

                                                                  delivery_rate  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                0.000000
                                                     11               36.173633
                                                     12               36.111111
                                                     13                0.000000
                                                     14               42.241379
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16               86.111111
                                                     17               25.000000
                                                     18                0.000000
                                                     22                0.000000
                                                     23                0.000000

                                                                  sms_clicked  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                   0.0
                                                     11                  22.0
                                                     12                   1.0
                                                     13                   0.0
                                                     14                  29.0
...                                                                       ...
West Bengal-Andaman Nicobar hi           Thursday    16                   9.0
                                                     17                   0.0
                                                     18                   0.0
                                                     22                   0.0
                                                     23                   0.0

                                                                  clicked_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02               0.000000
                                                     11               9.777778
                                                     12               7.692308
                                                     13               0.000000
                                                     14              11.836735
...                                                                        ...
West Bengal-Andaman Nicobar hi           Thursday    16               9.677419
                                                     17               0.000000
                                                     18               0.000000
                                                     22               0.000000
                                                     23               0.000000

[864 rows x 5 columns]

In [56]:
final_df = pd.merge(click_rate_df,new_features, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [57]:
final_df = final_df.reset_index()

In [58]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34,34,34,34
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34,34,34,34
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34,34,34,34
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34,34,34,34
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34,34,34,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,West Bengal-Andaman Nicobar,hi,Thursday,16,108,93.0,86.111111,9.0,9.677419,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,9.777778,8.0,9.777778,8.0,24.0,24.0,24.0,24.0,41,41,41,41
860,West Bengal-Andaman Nicobar,hi,Thursday,17,8,2.0,25.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
861,West Bengal-Andaman Nicobar,hi,Thursday,18,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
862,West Bengal-Andaman Nicobar,hi,Thursday,22,6,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
863,West Bengal-Andaman Nicobar,hi,Thursday,23,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41

In [59]:
final_df['SN'] = np.arange(0,864).tolist()

In [60]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34,34,34,34,0
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34,34,34,34,1
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34,34,34,34,2
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34,34,34,34,3
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34,34,34,34,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,West Bengal-Andaman Nicobar,hi,Thursday,16,108,93.0,86.111111,9.0,9.677419,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,9.777778,8.0,9.777778,8.0,24.0,24.0,24.0,24.0,41,41,41,41,859
860,West Bengal-Andaman Nicobar,hi,Thursday,17,8,2.0,25.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,860
861,West Bengal-Andaman Nicobar,hi,Thursday,18,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,861
862,West Bengal-Andaman Nicobar,hi,Thursday,22,6,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,862
863,West Bengal-Andaman Nicobar,hi,Thursday,23,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,863

In [61]:
final_df.to_csv('mkting_cmpgn_data_wo_existing_users_2.csv', index=False)

In [62]:
df_2 = pd.read_csv("/home/aamin/files/marketing/copy/mkting_cmpgn_data_wo_existing_users.csv")

In [66]:
df_2

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0,0
1,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0,1
2,Andhra Pradesh,en,Friday,11,2238,366.0,16.353887,34.0,9.289617,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.961573,240.0,239.961573,240.0,2.794118,2.0,2.968750,2.5,7.080429,2.0,7.080429,2.0,33.995532,34.0,33.995532,34.0,2
3,Andhra Pradesh,en,Friday,12,832,633.0,76.081731,106.0,16.745656,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,264.432692,268.0,264.432692,268.0,7713.801887,25.5,8016.303922,27.0,11.331731,12.0,11.331731,12.0,36.617788,37.0,36.617788,37.0,3
4,Andhra Pradesh,en,Friday,13,12,10.0,83.333333,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.666667,268.0,258.666667,268.0,0.000000,0.0,0.000000,0.0,11.000000,12.0,11.000000,12.0,36.000000,37.0,36.000000,37.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2144
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2145
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2146
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2147
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2148

In [69]:
new_data = pd.concat([final_df,df_2])

In [71]:
new_data.drop("SN",axis=1,inplace=True)

In [72]:
new_data

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34.0,34.0,34.0,34.0
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34.0,34.0,34.0,34.0
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34.0,34.0,34.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,44.666667,49.0,44.666667,49.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,5.333333,4.0,5.333333,4.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0

In [73]:
new_data['SN'] = np.arange(0,3013).tolist()

In [75]:
new_data.to_csv('mkting_cmpgn_data_wo_existing_users_3.csv', index=False)