In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import calendar
pd.set_option('display.max_columns', None)

from langdetect import detect

In [2]:
def convert_to_day_of_week(date_str):
    try:
        date_ = datetime.date.fromisoformat(date_str)
        weekday = calendar.day_name[date_.weekday()]
    except:
        weekday = np.nan
    return weekday

#### Reports

In [3]:
# camp_dir_path = r'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/1148818'
# camp_filename_list = []
# for path in os.scandir(camp_dir_path):
#     if path.is_file():
#         camp_filename_list.append(path.name)

In [4]:
main_camp_dir_path = r'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'
camp_filename_list = []

for folder_name in os.listdir(main_camp_dir_path):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    for path in os.scandir(camp_dir_path):
        if path.is_file():
            camp_filename_list.append(path.name)

camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

camp_sms_delivery_df = pd.DataFrame()
for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_delvreport_filename_list):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    camp_temp_delivery_df = pd.read_csv(f'{camp_dir_path}/{file}')
    camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
camp_sms_delivery_df = camp_sms_delivery_df.drop_duplicates()

camp_sms_click_df = pd.DataFrame()
for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_clickreport_filename_list):
    camp_dir_path = f'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
    camp_temp_click_df = pd.read_csv(f'{camp_dir_path}/{file}')
    camp_sms_click_df = pd.concat([camp_sms_click_df, camp_temp_click_df])
camp_sms_click_df = camp_sms_click_df.drop_duplicates()

In [5]:
# camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
# camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

# camp_path_to_reports = '/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'

# camp_sms_delivery_df = pd.DataFrame()

# for file in camp_delvreport_filename_list:
    
#     camp_temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
#     camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
    
# camp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
# camp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [6]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS")]["Broadcast ID"].unique()

In [7]:
camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS") & (camp_sms_delivery_df["Broadcast name"].str.contains("English"))]["Broadcast name"].unique()

array(['Tie Up DTSS Bang English 2511', 'Tie Up DTSS Bang English 0212'],
      dtype=object)

In [8]:
camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") | (camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212" )]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Message,Published date,Delivered time,Status,Remark,Operator,Circle
0,5638,Tie Up DTSS Bang English 2511,9910594223,DTSS2792,"Dear Customer, Congratulations! As an employee...",NaN,2022-11-25 12:02:20,not sent,number on DND,-,-
1,5638,Tie Up DTSS Bang English 2511,9968258450,DTSS2725,"Dear Customer, Congratulations! As an employee...",NaN,2022-11-25 12:17:49,Delivered,Delivered,Vodafone,Karnataka
2,5638,Tie Up DTSS Bang English 2511,9518683330,DTSS1373,"Dear Customer, Congratulations! As an employee...",NaN,2022-11-25 12:02:22,undelivered,undelivered,-,-
3,5638,Tie Up DTSS Bang English 2511,9538872998,DTSS2636,"Dear Customer, Congratulations! As an employee...",NaN,2022-11-25 12:09:47,Delivered,Delivered,-,-
4,5638,Tie Up DTSS Bang English 2511,9844423352,DTSS3165,"Dear Customer, Congratulations! As an employee...",NaN,2022-11-25 12:09:45,Delivered,Delivered,-,-
...,...,...,...,...,...,...,...,...,...,...,...
9762,5669,Tie Up DTSS Bang English 0212,9535830076,DTSS3732,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-02 16:32:39,Delivered,Delivered,Idea,Karnataka
9763,5669,Tie Up DTSS Bang English 0212,9945213913,DTSS3759,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-02 16:32:41,Delivered,Delivered,Airtel,Karnataka
9764,5669,Tie Up DTSS Bang English 0212,7899829447,DTSS7298,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-02 16:32:41,Delivered,Delivered,Unitech Infrastructures,Karnataka
9765,5669,Tie Up DTSS Bang English 0212,7676991183,DTSS3702,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-02 16:32:53,Delivered,Delivered,Reliance JIO,Karnataka
9766,5669,Tie Up DTSS Bang English 0212,7899883882,DTSS3705,"Dear Customer, Congratulations! As an employee...",NaN,2022-12-02 16:32:41,Delivered,Delivered,Unitech Infrastructures,Karnataka

In [8]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast ID"].str.contains("DTSS")]["Broadcast name"].unique()

In [9]:
camp_sms_delivery_df['Delivered Date'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[0])
camp_sms_delivery_df['Delivery Time'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[1])
camp_sms_delivery_df['Hour of Day'] = camp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_delivery_df['Day of Week'] = camp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
camp_sms_delivery_df['SMS Language'] = camp_sms_delivery_df["Message"].apply(lambda x: detect(x))

In [10]:
camp_sms_delivery_df.columns = camp_sms_delivery_df.columns.str.replace('Delivered time', 'Delivered Time')

In [11]:
camp_sms_click_df = camp_sms_click_df[camp_sms_click_df["Delivered Time"] != "-"]

In [12]:
camp_sms_click_df['Delivered Date'] = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Delivery Time']  = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Hour of Day'] = camp_sms_click_df['Delivery Time'].apply(lambda x:  x.split(':')[0] )
camp_sms_click_df['Day of Week'] = camp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

camp_sms_click_df['Clicked Date'] = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Click Time']  = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Clicked Hour of Day'] = camp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [13]:
camp_sms_click_df

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day
0,5641,Tie Up ASPPL Hindi 2511,9986973357,ASPPL134,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:33,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:33,10
1,5641,Tie Up ASPPL Hindi 2511,7259111908,ASPPL238,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:31,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:31,10
2,5641,Tie Up ASPPL Hindi 2511,7010058674,ASPPL42,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:32,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:32,10
3,5641,Tie Up ASPPL Hindi 2511,6362895723,ASPPL80,https://mshblf.page.link/EGF4,2022-11-25 10:58:29,2022-11-25 10:58:33,2022-11-25,10:58:29,10,Friday,2022-11-25,10:58:33,10
4,5641,Tie Up ASPPL Hindi 2511,9071171837,ASPPL216,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:32,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:32,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,5639,Tie Up Vinolya Hindi 2511,9035355620,VINOLYA575,https://mshblf.page.link/EGF4,2022-11-25 10:56:13,2022-11-25 10:56:24,2022-11-25,10:56:13,10,Friday,2022-11-25,10:56:24,10
21,5639,Tie Up Vinolya Hindi 2511,9900296910,VINOLYA98,https://mshblf.page.link/EGF4,2022-11-25 10:56:12,2022-11-25 10:56:19,2022-11-25,10:56:12,10,Friday,2022-11-25,10:56:19,10
22,5639,Tie Up Vinolya Hindi 2511,9738565931,VINOLYA34,https://mshblf.page.link/EGF4,2022-11-25 10:56:13,2022-11-25 10:56:19,2022-11-25,10:56:13,10,Friday,2022-11-25,10:56:19,10
24,5639,Tie Up Vinolya Hindi 2511,9066984640,VINOLYA588,https://mshblf.page.link/EGF4,2022-11-25 10:56:17,2022-11-25 11:12:09,2022-11-25,10:56:17,10,Friday,2022-11-25,11:12:09,11
25,5639,Tie Up Vinolya Hindi 2511,9632183041,VINOLYA443,https://mshblf.page.link/EGF4,2022-11-25 10:56:11,2022-11-25 11:10:38,2022-11-25,10:56:11,10,Friday,2022-11-25,11:10:38,11

In [14]:
camp_sms_dff = pd.merge(camp_sms_click_df, camp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [24]:
# all_sms = pd.concat([camp_sms_dff, campp_sms_dff]) #, comm_sms_dff])
# all_sms.reset_index(drop=True, inplace=True)

In [25]:
# all_sms.columns

Index(['Broadcast ID', 'Broadcast name', 'Mobile number',
       'Primary Key (User_id)', 'Link clicked', 'Delivered Time',
       'Clicked time', 'Delivered Date', 'Delivery Time', 'Hour of Day',
       'Day of Week', 'Clicked Date', 'Click Time', 'Clicked Hour of Day',
       'Message', 'Published date', 'Status', 'Remark', 'Operator', 'Circle',
       'SMS Language'],
      dtype='object')

In [ ]:
# all_sms = all_sms.drop(['Unnamed: 0', 'myshubhlife',
#                            'myshubhlife-Latitude-7480', '26.07.2022 14:48',
#                            'file:///home/myshubhlife/.config/libreoffice/4;'], axis=1)

In [15]:
cmpgn_category_df = pd.read_csv('/home/aamin/files/marketing/copy/reports/click_rate_cmpgn_wise.csv', usecols=[0,1,2])

In [26]:
all_sms = camp_sms_dff.merge(cmpgn_category_df[['Broadcast name','category']], on='Broadcast name', how='left')

In [27]:
all_sms['category'].value_counts()

Series([], Name: category, dtype: int64)

In [28]:
all_sms['category'].value_counts()

Series([], Name: category, dtype: int64)

In [29]:
all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,category
0,5641,Tie Up ASPPL Hindi 2511,9986973357,ASPPL134,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:33,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:33,10,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Vodafone,Karnataka,hi,NaN
1,5641,Tie Up ASPPL Hindi 2511,7259111908,ASPPL238,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:31,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:31,10,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,"BPL Mobile, Loop Telecom",Karnataka,hi,NaN
2,5641,Tie Up ASPPL Hindi 2511,7010058674,ASPPL42,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:32,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:32,10,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Reliance JIO,Andhra Pradesh,hi,NaN
3,5641,Tie Up ASPPL Hindi 2511,6362895723,ASPPL80,https://mshblf.page.link/EGF4,2022-11-25 10:58:29,2022-11-25 10:58:33,2022-11-25,10:58:29,10,Friday,2022-11-25,10:58:33,10,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,hi,NaN
4,5641,Tie Up ASPPL Hindi 2511,9071171837,ASPPL216,https://mshblf.page.link/EGF4,2022-11-25 10:58:27,2022-11-25 10:58:32,2022-11-25,10:58:27,10,Friday,2022-11-25,10:58:32,10,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,hi,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82482,5639,Tie Up Vinolya Hindi 2511,9972363521,VINOLYA197,NaN,2022-11-25 10:56:11,NaN,2022-11-25,10:56:11,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82483,5639,Tie Up Vinolya Hindi 2511,9945768371,VINOLYA481,NaN,2022-11-25 10:56:14,NaN,2022-11-25,10:56:14,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82484,5639,Tie Up Vinolya Hindi 2511,9741814983,VINOLYA1,NaN,2022-11-25 10:56:15,NaN,2022-11-25,10:56:15,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82485,5639,Tie Up Vinolya Hindi 2511,9611708813,VINOLYA301,NaN,2022-11-25 10:56:11,NaN,2022-11-25,10:56:11,10,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,Delivered,Delivered,Airtel,Karnataka,hi,NaN
82486,5639,Tie Up Vinolya Hindi 2511,9606157498,VINOLYA429,NaN,2022-11-25 16:56:11,NaN,2022-11-25,16:56:11,16,Friday,NaN,NaN,NaN,"प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ...",NaN,undelivered,expired,Reliance CDMA,North East,hi,NaN

In [30]:
df_to_use = all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

In [24]:
# df_to_use.drop(['category'], axis=1, inplace=True)

In [31]:
df_to_use.to_csv("/home/aamin/files/marketing/copy/reports_data/reports_nov_dec.csv")

def convert_df_for_delivery(df):
    
    df_copy = df.copy()
    
    for i, row in df_copy.iterrows():
        if (row['Clicked Date'] == row['Clicked Date']) and (row['Message'] != row['Message']):
            df_copy.at[i, 'Status'] = 'Delivered'
            df_copy.at[i, 'Remark'] = 'Delivered'
            df_copy.at[i, 'Message'] = df_copy['Message'].value_counts().index[0]
            df_copy.at[i, 'Operator'] = df_copy['Operator'].value_counts().index[0]
            df_copy.at[i, 'Circle'] = df_copy['Circle'].value_counts().index[0]
            df_copy.at[i, 'SMS Language'] = df_copy['SMS Language'].value_counts().index[0]
            #df_copy.at[i, 'SMS Length'] = len(row['Message'])
            
    for i, row in df_copy.iterrows():
        df_copy.at[i, 'SMS Length'] = len(row['Message'])
    
    return df_copy

mob_nums = df_to_use[df_to_use['Message']!=df_to_use['Message']]['Mobile number'].unique().tolist()
to_impute = df_to_use[df_to_use['Mobile number'].isin(mob_nums)]
no_impute = df_to_use[~df_to_use['Mobile number'].isin(mob_nums)]

mob_nums

groupby_df = to_impute.groupby(['Mobile number',
                              'Primary Key (User_id)'
                             ]).apply(convert_df_for_delivery)

groupby_df

groupby_df2 = groupby_df.droplevel(level=0)
groupby_df2.reset_index(drop=True, inplace=True)

prepared_df = pd.concat([groupby_df2, no_impute]).reset_index(drop=True)

In [16]:
df = camp_sms_dff[camp_sms_dff['Circle']!='-']
df = df[df['Operator']!='-']

In [17]:
df['SMS Length'] = df['Message'].apply(lambda x: len(x) if x==x else np.nan)

In [18]:
df.shape, camp_sms_dff.shape

((70320, 22), (82487, 21))

In [19]:
import time
from datetime import datetime
from dateutil import parser

def func_UTCToEpoch(utcData, timestampFormat=None):
    if timestampFormat == None:
        dateObj    = parser.parse(utcData)
        epochValue = dateObj.timestamp()
    else:
        timeTuple  = time.strptime(utcData, timestampFormat)
        epochValue = time.mktime(timeTuple)
    return (epochValue)

In [20]:
import dateutil.relativedelta

def calculate_timelag(delv_time, click_time):
    
    if click_time == click_time:
        delv_time_ts = datetime.fromtimestamp(func_UTCToEpoch(delv_time))
        click_time_ts = datetime.fromtimestamp(func_UTCToEpoch(click_time))
        diff = click_time_ts - delv_time_ts
        seconds = diff.total_seconds()
    
    else:
        seconds = np.nan
    
    return seconds

In [21]:
df['Timelag (s)'] = df.apply(lambda x: calculate_timelag(x['Delivered Time'], x['Clicked time']), axis=1)

In [22]:
df = df[~(df['Timelag (s)'] < -10)]

In [23]:
df['Timelag (s)'] = df['Timelag (s)'].apply(lambda x: abs(x) if x==x else np.nan)

In [24]:
#df['SMS Length'] = len(df['Message'])
df['Num SMS Sent'] = np.ceil(df['SMS Length']/160)
df['Cost of All SMS Sent'] = 0.13 * df['Num SMS Sent'] #  cost_of_sms

In [25]:
df['Num words in SMS'] = df['Message'].apply(lambda x: len(x.split(' ')))

In [26]:
def convert_to_day_of_month(date_str):
    try:
        day_of_mon = datetime.fromtimestamp(func_UTCToEpoch(date_str)).day
    except:
        day_of_mon = np.nan
    return day_of_mon

In [27]:
df['Day of Month'] = df['Delivered Date'].apply(convert_to_day_of_month)

In [28]:
def mean_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    mean = np.nanmean(x_upd)
    return mean

def median_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    median = np.nanmedian(x_upd)
    return median

In [38]:
timelag = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Timelag (s)'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
timelag.rename(columns= {'mean': 'Avg Timelag (s)',
                        'median': 'Median Timelag (s)',
                         'mean_wo_0': 'Avg Timelag (s) wo 0',
                        'median_wo_0': 'Median Timelag (s) wo 0',
                        }, inplace=True)

/tmp/ipykernel_42360/3554248693.py:3: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(x_upd)
/home/aamin/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,

In [39]:
num_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_sms.rename(columns= {'mean': 'Avg Num SMS Sent',
                        'median': 'Median Num SMS Sent',
                        'mean_wo_0': 'Avg Num SMS Sent wo 0',
                        'median_wo_0': 'Median Num SMS Sent wo 0',
                        }, inplace=True)

In [40]:
cost_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Cost of All SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
cost_sms.rename(columns= {'mean': 'Avg Cost of All SMS Sent',
                        'median': 'Median Cost of All SMS Sent',
                         'mean_wo_0': 'Avg Cost of All SMS Sent wo 0',
                        'median_wo_0': 'Median Cost of All SMS Sent wo 0'}, inplace=True)

In [41]:
len_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['SMS Length'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
len_sms.rename(columns= {'mean': 'Avg SMS Length',
                        'median': 'Median SMS Length',
                        'mean_wo_0': 'Avg SMS Length wo 0',
                        'median_wo_0': 'Median SMS Length wo 0'}, inplace=True)

In [42]:
day_of_mon = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Day of Month'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
day_of_mon.rename(columns= {'mean': 'Avg Day of Month',
                        'median': 'Median Day of Month',
                           'mean_wo_0': 'Avg Day of Month wo 0',
                        'median_wo_0': 'Median Day of Month wo 0'}, inplace=True)

In [43]:
num_words = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num words in SMS'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_words.rename(columns= {'mean': 'Avg Num Words',
                        'median': 'Median Num Words',
                          'mean_wo_0': 'Avg Num Words wo 0',
                        'median_wo_0': 'Median Num Words wo 0'}, inplace=True)

In [44]:
new_features = pd.merge(num_sms,cost_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,len_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,timelag, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,day_of_mon, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,num_words, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [45]:
new_features.fillna(0, inplace = True)

In [46]:
new_features

                                                                  Avg Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                        2.0
                                                     11                        2.0
                                                     12                        2.0
                                                     13                        2.0
                                                     14                        2.0
...                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                        2.0
                                                     17                        2.0
                                                     18                        2.0
                                                     22                        2.0
                                                     23                        2.0

                                                                  Median Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                           2.0
                                                     11                           2.0
                                                     12                           2.0
                                                     13                           2.0
                                                     14                           2.0
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                           2.0
                                                     17                           2.0
                                                     18                           2.0
                                                     22                           2.0
                                                     23                           2.0

                                                                  Avg Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                             2.0
                                                     11                             2.0
                                                     12                             2.0
                                                     13                             2.0
                                                     14                             2.0
...                                                                                 ...
West Bengal-Andaman Nicobar hi           Thursday    16                             2.0
                                                     17                             2.0
                                                     18                             2.0
                                                     22                             2.0
                                                     23                             2.0

                                                                  Median Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                2.0
                                                     11                                2.0
                                                     12                                2.0
                                                     13                                2.0
                                                     14                                2.0
...                                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                                2.0
                                                     17                                2.0
                                                     18                                2.0
                                                     22                                2.0
                                                     23                                2.0

                                                                  Avg Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                               0.26
                                                     11                               0.26
                                                     12                               0.26
                                                     13                               0.26
                                                     14                               0.26
...                                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                               0.26
                                                     17                               0.26
                                                     18                               0.26
                                                     22                               0.26
                                                     23                               0.26

                                                                  Median Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                  0.26
                                                     11                                  0.26
                                                     12                                  0.26
                                                     13                                  0.26
                                                     14                                  0.26
...                                                                                       ...
West Bengal-Andaman Nicobar hi           Thursday    16                                  0.26
                                                     17                                  0.26
                                                     18                                  0.26
                                                     22                                  0.26
                                                     23                                  0.26

                                                                  Avg Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                    0.26
                                                     11                                    0.26
                                                     12                                    0.26
                                                     13                                    0.26
                                                     14                                    0.26
...                                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                                    0.26
                                                     17                                    0.26
                                                     18                                    0.26
                                                     22                                    0.26
                                                     23                                    0.26

                                                                  Median Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                                       0.26
                                                     11                                       0.26
                                                     12                                       0.26
                                                     13                                       0.26
                                                     14                                       0.26
...                                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                                       0.26
                                                     17                                       0.26
                                                     18                                       0.26
                                                     22                                       0.26
                                                     23                                       0.26

                                                                  Avg SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                      240
                                                     11                      240
                                                     12                      240
                                                     13                      240
                                                     14                      240
...                                                                          ...
West Bengal-Andaman Nicobar hi           Thursday    16                      261
                                                     17                      261
                                                     18                      261
                                                     22                      261
                                                     23                      261

                                                                  Median SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                         240
                                                     11                         240
                                                     12                         240
                                                     13                         240
                                                     14                         240
...                                                                             ...
West Bengal-Andaman Nicobar hi           Thursday    16                         261
                                                     17                         261
                                                     18                         261
                                                     22                         261
                                                     23                         261

                                                                  Avg SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                           240
                                                     11                           240
                                                     12                           240
                                                     13                           240
                                                     14                           240
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                           261
                                                     17                           261
                                                     18                           261
                                                     22                           261
                                                     23                           261

                                                                  Median SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                              240
                                                     11                              240
                                                     12                              240
                                                     13                              240
                                                     14                              240
...                                                                                  ...
West Bengal-Andaman Nicobar hi           Thursday    16                              261
                                                     17                              261
                                                     18                              261
                                                     22                              261
                                                     23                              261

                                                                  Avg Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  0.000000
                                                     11                  2.000000
                                                     12                  5.000000
                                                     13                  0.000000
                                                     14                 23.758621
...                                                                           ...
West Bengal-Andaman Nicobar hi           Thursday    16                  9.777778
                                                     17                  0.000000
                                                     18                  0.000000
                                                     22                  0.000000
                                                     23                  0.000000

                                                                  Median Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                          0.0
                                                     11                          2.0
                                                     12                          5.0
                                                     13                          0.0
                                                     14                          4.0
...                                                                              ...
West Bengal-Andaman Nicobar hi           Thursday    16                          8.0
                                                     17                          0.0
                                                     18                          0.0
                                                     22                          0.0
                                                     23                          0.0

                                                                  Avg Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                       0.000000
                                                     11                       2.200000
                                                     12                       5.000000
                                                     13                       0.000000
                                                     14                      23.758621
...                                                                                ...
West Bengal-Andaman Nicobar hi           Thursday    16                       9.777778
                                                     17                       0.000000
                                                     18                       0.000000
                                                     22                       0.000000
                                                     23                       0.000000

                                                                  Median Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                               0.0
                                                     11                               2.0
                                                     12                               5.0
                                                     13                               0.0
                                                     14                               4.0
...                                                                                   ...
West Bengal-Andaman Nicobar hi           Thursday    16                               8.0
                                                     17                               0.0
                                                     18                               0.0
                                                     22                               0.0
                                                     23                               0.0

                                                                  Avg Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                       25.0
                                                     11                       16.0
                                                     12                       19.0
                                                     13                       16.0
                                                     14                       18.0
...                                                                            ...
West Bengal-Andaman Nicobar hi           Thursday    16                       24.0
                                                     17                       24.0
                                                     18                       24.0
                                                     22                       24.0
                                                     23                       24.0

                                                                  Median Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                          25.0
                                                     11                          16.0
                                                     12                          16.0
                                                     13                          16.0
                                                     14                          18.0
...                                                                               ...
West Bengal-Andaman Nicobar hi           Thursday    16                          24.0
                                                     17                          24.0

In [47]:
circle_df = pd.DataFrame(df.groupby(by = ['Circle', 
                                          #'Operator',
                                        'SMS Language',
                                          'Day of Week','Hour of Day']).Status.count())
circle_df.rename(columns= {'Status': 'sms_sent'}, inplace=True)
circle_df

                                                                  sms_sent
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

[864 rows x 1 columns]

In [48]:
circle_delv= pd.DataFrame(df[df['Status']=='Delivered'].groupby(by = ['Circle',
                                                                      'SMS Language',
                                                                      'Day of Week','Hour of Day']).Status.count())
circle_delv.rename(columns= {'Status': 'sms_delivered'}, inplace=True)
circle_delv

                                                                  sms_delivered
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      11                     225
                                                     12                      13
                                                     14                     245
                                                     15                     132
                                                     16                     335
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    10                     156
                                                     11                       3
                                                     13                       1
                                                     16                      93
                                                     17                       2

[549 rows x 1 columns]

In [49]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [50]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [51]:
circle_delv_rate_df.fillna(0, inplace = True)
circle_delv_rate_df['delivery_rate'] = circle_delv_rate_df['sms_delivered']*100 / circle_delv_rate_df['sms_sent']
circle_delv_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                     0.0
                                                     11                   225.0
                                                     12                    13.0
                                                     13                     0.0
                                                     14                   245.0
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                    93.0
                                                     17                     2.0
                                                     18                     0.0
                                                     22                     0.0
                                                     23                     0.0

                                                                  delivery_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                0.000000
                                                     11               36.173633
                                                     12               36.111111
                                                     13                0.000000
                                                     14               42.241379
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16               86.111111
                                                     17               25.000000
                                                     18                0.000000
                                                     22                0.000000
                                                     23                0.000000

[864 rows x 3 columns]

In [54]:
click= pd.DataFrame(df[df['Clicked Date']==df['Clicked Date']].groupby(by = ['Circle', 'SMS Language',
                                                                                           'Day of Week','Hour of Day']
                                                                                    ).Status.count())
click.rename(columns= {'Status': 'sms_clicked'}, inplace=True)
click

                                                                  sms_clicked
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      11                    22
                                                     12                     1
                                                     14                    29
                                                     15                    12
                                                     16                    24
...                                                                       ...
West Bengal-Andaman Nicobar hi           Friday      15                     1
                                                     17                     1
                                         Monday      12                    25
                                         Thursday    10                    18
                                                     16                     9

[246 rows x 1 columns]

In [55]:
click_rate_df = pd.merge(circle_delv_rate_df,click, how= 'outer', 
                         on = ['Circle','SMS Language','Day of Week','Hour of Day'])
click_rate_df.fillna(0, inplace = True)
click_rate_df['clicked_rate'] = click_rate_df['sms_clicked']*100 / click_rate_df['sms_delivered']
click_rate_df.fillna(0, inplace = True)
click_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                  2
                                                     11                622
                                                     12                 36
                                                     13                  2
                                                     14                580
...                                                                    ...
West Bengal-Andaman Nicobar hi           Thursday    16                108
                                                     17                  8
                                                     18                  1
                                                     22                  6
                                                     23                  1

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                     0.0
                                                     11                   225.0
                                                     12                    13.0
                                                     13                     0.0
                                                     14                   245.0
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16                    93.0
                                                     17                     2.0
                                                     18                     0.0
                                                     22                     0.0
                                                     23                     0.0

                                                                  delivery_rate  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                0.000000
                                                     11               36.173633
                                                     12               36.111111
                                                     13                0.000000
                                                     14               42.241379
...                                                                         ...
West Bengal-Andaman Nicobar hi           Thursday    16               86.111111
                                                     17               25.000000
                                                     18                0.000000
                                                     22                0.000000
                                                     23                0.000000

                                                                  sms_clicked  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02                   0.0
                                                     11                  22.0
                                                     12                   1.0
                                                     13                   0.0
                                                     14                  29.0
...                                                                       ...
West Bengal-Andaman Nicobar hi           Thursday    16                   9.0
                                                     17                   0.0
                                                     18                   0.0
                                                     22                   0.0
                                                     23                   0.0

                                                                  clicked_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      02               0.000000
                                                     11               9.777778
                                                     12               7.692308
                                                     13               0.000000
                                                     14              11.836735
...                                                                        ...
West Bengal-Andaman Nicobar hi           Thursday    16               9.677419
                                                     17               0.000000
                                                     18               0.000000
                                                     22               0.000000
                                                     23               0.000000

[864 rows x 5 columns]

In [56]:
final_df = pd.merge(click_rate_df,new_features, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [57]:
final_df = final_df.reset_index()

In [58]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34,34,34,34
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34,34,34,34
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34,34,34,34
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34,34,34,34
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34,34,34,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,West Bengal-Andaman Nicobar,hi,Thursday,16,108,93.0,86.111111,9.0,9.677419,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,9.777778,8.0,9.777778,8.0,24.0,24.0,24.0,24.0,41,41,41,41
860,West Bengal-Andaman Nicobar,hi,Thursday,17,8,2.0,25.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
861,West Bengal-Andaman Nicobar,hi,Thursday,18,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
862,West Bengal-Andaman Nicobar,hi,Thursday,22,6,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41
863,West Bengal-Andaman Nicobar,hi,Thursday,23,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41

In [59]:
final_df['SN'] = np.arange(0,864).tolist()

In [60]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34,34,34,34,0
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34,34,34,34,1
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34,34,34,34,2
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34,34,34,34,3
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34,34,34,34,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,West Bengal-Andaman Nicobar,hi,Thursday,16,108,93.0,86.111111,9.0,9.677419,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,9.777778,8.0,9.777778,8.0,24.0,24.0,24.0,24.0,41,41,41,41,859
860,West Bengal-Andaman Nicobar,hi,Thursday,17,8,2.0,25.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,860
861,West Bengal-Andaman Nicobar,hi,Thursday,18,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,861
862,West Bengal-Andaman Nicobar,hi,Thursday,22,6,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,862
863,West Bengal-Andaman Nicobar,hi,Thursday,23,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,0.000000,0.0,0.000000,0.0,24.0,24.0,24.0,24.0,41,41,41,41,863

In [61]:
final_df.to_csv('mkting_cmpgn_data_wo_existing_users_2.csv', index=False)

In [62]:
df_2 = pd.read_csv("/home/aamin/files/marketing/copy/mkting_cmpgn_data_wo_existing_users.csv")

In [66]:
df_2

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0,0
1,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0,1
2,Andhra Pradesh,en,Friday,11,2238,366.0,16.353887,34.0,9.289617,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.961573,240.0,239.961573,240.0,2.794118,2.0,2.968750,2.5,7.080429,2.0,7.080429,2.0,33.995532,34.0,33.995532,34.0,2
3,Andhra Pradesh,en,Friday,12,832,633.0,76.081731,106.0,16.745656,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,264.432692,268.0,264.432692,268.0,7713.801887,25.5,8016.303922,27.0,11.331731,12.0,11.331731,12.0,36.617788,37.0,36.617788,37.0,3
4,Andhra Pradesh,en,Friday,13,12,10.0,83.333333,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.666667,268.0,258.666667,268.0,0.000000,0.0,0.000000,0.0,11.000000,12.0,11.000000,12.0,36.000000,37.0,36.000000,37.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2144
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2145
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2146
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2147
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2148

In [69]:
new_data = pd.concat([final_df,df_2])

In [71]:
new_data.drop("SN",axis=1,inplace=True)

In [72]:
new_data

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34.0,34.0,34.0,34.0
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34.0,34.0,34.0,34.0
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34.0,34.0,34.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,44.666667,49.0,44.666667,49.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,5.333333,4.0,5.333333,4.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0

In [73]:
new_data['SN'] = np.arange(0,3013).tolist()

In [75]:
new_data.to_csv('mkting_cmpgn_data_wo_existing_users_3.csv', index=False)