In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import calendar
pd.set_option('display.max_columns', None)

from langdetect import detect

In [70]:
def convert_to_day_of_week(date_str):
    try:
        date_ = datetime.date.fromisoformat(date_str)
        weekday = calendar.day_name[date_.weekday()]
    except:
        weekday = np.nan
    return weekday

#### Reports

In [4]:
# camp_dir_path = r'/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/1148818'
# camp_filename_list = []
# for path in os.scandir(camp_dir_path):
#     if path.is_file():
#         camp_filename_list.append(path.name)

In [72]:
# main_camp_dir_path = r'/home/aamin/files/marketing/copy/data/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'
# camp_filename_list = []

# for folder_name in os.listdir(main_camp_dir_path):
#     camp_dir_path = f'/home/aamin/files/marketing/copy/data/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
#     for path in os.scandir(camp_dir_path):
#         if path.is_file():
#             camp_filename_list.append(path.name)

# camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
# camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

# camp_sms_delivery_df = pd.DataFrame()
# for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_delvreport_filename_list):
#     camp_dir_path = f'/home/aamin/files/marketing/copy/data/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
#     camp_temp_delivery_df = pd.read_csv(f'{camp_dir_path}/{file}')
#     camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
# camp_sms_delivery_df = camp_sms_delivery_df.drop_duplicates()

# camp_sms_click_df = pd.DataFrame()
# for folder_name,file in zip(os.listdir(main_camp_dir_path),camp_clickreport_filename_list):
#     camp_dir_path = f'/home/aamin/files/marketing/copy/data/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022/{folder_name}'
#     camp_temp_click_df = pd.read_csv(f'{camp_dir_path}/{file}')
#     camp_sms_click_df = pd.concat([camp_sms_click_df, camp_temp_click_df])
# camp_sms_click_df = camp_sms_click_df.drop_duplicates()

In [6]:
# camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
# camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

# camp_path_to_reports = '/home/aamin/files/marketing/campaign_reports_till_9dec2022-20221212T111230Z-001/campaign_reports_till_9dec2022'

# camp_sms_delivery_df = pd.DataFrame()

# for file in camp_delvreport_filename_list:
    
#     camp_temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
#     camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
    
# camp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
# camp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [7]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS")]["Broadcast ID"].unique()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains("DTSS") & (camp_sms_delivery_df["Broadcast name"].str.contains("English"))]["Broadcast name"].unique()

In [9]:
# df = camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") | (camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212" )]

In [10]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast ID"].str.contains("DTSS")]["Broadcast name"].unique()

In [73]:
# camp_sms_delivery_df['Delivered Date'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[0])
# camp_sms_delivery_df['Delivery Time'] = camp_sms_delivery_df['Delivered time'].apply(lambda x: x.split(' ')[1])
# camp_sms_delivery_df['Hour of Day'] = camp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
# camp_sms_delivery_df['Day of Week'] = camp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
# camp_sms_delivery_df['SMS Language'] = camp_sms_delivery_df["Message"].apply(lambda x: detect(x))

In [5]:
# camp_sms_delivery_df.to_csv("reports_nov_dec.csv")

In [15]:
# broadcast_name_data = pd.read_csv("/home/aamin/files/marketing/copy/Shubh Saathi - Campaign Tracker.xlsx - Sheet1.csv")

In [19]:
# broadcast_name_data = broadcast_name_data.iloc[1:]

In [ ]:
# broadcast_name_data

In [32]:
# import re

In [57]:
# camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains(broadcast_name_data["Partner/ Company"].iloc[9].replace(" ",""), flags= re.IGNORECASE) == True , "Circle"] = broadcast_name_data["Region"].iloc[9]

In [ ]:
# camp_sms_delivery_df.loc[(camp_sms_delivery_df["Broadcast name"].str.contains("dtss", flags= re.IGNORECASE) == True)  &
#                          (camp_sms_delivery_df["Broadcast name"].str.contains("hindi", flags= re.IGNORECASE) == True) &
#                          (camp_sms_delivery_df["Broadcast name"].str.contains("bang", flags= re.IGNORECASE) == False)  
#                          , ["Circle","Broadcast name"]] = ""

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast ID"] == 5698]

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"].str.contains(broadcast_name_data["Partner/ Company"].iloc[6].replace(" ",""))]

In [ ]:
# camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains("Cognizant", flags= re.IGNORECASE)]["Broadcast name"].value_counts()

In [ ]:
# camp_sms_delivery_df.loc[camp_sms_delivery_df["Broadcast name"].str.contains("dtss", flags= re.IGNORECASE)]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Circle"] == "Haryana"]

In [74]:
# camp_sms_delivery_df.columns = camp_sms_delivery_df.columns.str.replace('Delivered time', 'Delivered Time')

In [ ]:
# camp_sms_delivery_df["SMS Language"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"].shape

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Circle"] == "-")]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Circle"] == "-")]["Remark"].value_counts()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511"]["Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212")]

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Circle"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Status"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16")]["Remark"].value_counts()

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 0212") & (camp_sms_delivery_df["Hour of Day"] != "16") & ("")]["Operator"].value_counts().to_frame()

In [75]:
# camp_sms_click_df = camp_sms_click_df[camp_sms_click_df["Delivered Time"] != "-"]

In [76]:
# camp_sms_click_df['Delivered Date'] = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
# camp_sms_click_df['Delivery Time']  = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
# camp_sms_click_df['Hour of Day'] = camp_sms_click_df['Delivery Time'].apply(lambda x:  x.split(':')[0] )
# camp_sms_click_df['Day of Week'] = camp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

# camp_sms_click_df['Clicked Date'] = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
# camp_sms_click_df['Click Time']  = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
# camp_sms_click_df['Clicked Hour of Day'] = camp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [ ]:
# camp_sms_delivery_df[(camp_sms_delivery_df["Broadcast name"] == "Tie Up DTSS Bang English 2511") & (camp_sms_delivery_df["Hour of Day"] != "12")]["Remark"].value_counts()

In [ ]:
# camp_sms_click_df[camp_sms_click_df["Broadcast name"] == "Tie Up DTSS Bang English 0212"]

In [77]:
# camp_sms_dff = pd.merge(camp_sms_click_df, camp_sms_delivery_df, on=['Broadcast ID', 
#                                             'Broadcast name',
#                                             'Mobile number',
#                                             'Primary Key (User_id)',
#                                             'Delivered Time',
#                                             'Delivered Date','Delivery Time',
#                                             'Hour of Day','Day of Week'], how='outer')

In [ ]:
### we don't have the circle and 


# camp_sms_dff[camp_sms_dff["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Clicked Hour of Day"].value_counts().to_frame()

In [ ]:
# camp_sms_dff[camp_sms_dff["Broadcast name"] == "Tie Up DTSS Bang English 0212"]["Circle"].value_counts()

In [3]:
camp_sms_dff = pd.read_csv("/home/aamin/files/marketing/copy/reports_data/tie_up_data.csv")

/home/aamin/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3106: DtypeWarning: Columns (5,7,12,13,22) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [4]:
camp_sms_dff.drop(["Unnamed: 0","category"],axis = 1,inplace = True)

In [13]:
# camp_sms_dff[""].value_counts()

In [14]:
df = camp_sms_dff[camp_sms_dff['Circle']!='-']
df = df[df['Operator']!='-']

In [15]:
df['SMS Length'] = df['Message'].apply(lambda x: len(x) if x==x else np.nan)

In [16]:
df.shape, camp_sms_dff.shape

((81171, 22), (93402, 21))

In [17]:
import time
from datetime import datetime
from dateutil import parser

def func_UTCToEpoch(utcData, timestampFormat=None):
    if timestampFormat == None:
        dateObj    = parser.parse(utcData)
        epochValue = dateObj.timestamp()
    else:
        timeTuple  = time.strptime(utcData, timestampFormat)
        epochValue = time.mktime(timeTuple)
    return (epochValue)

In [18]:
import dateutil.relativedelta

def calculate_timelag(delv_time, click_time):
    
    if click_time == click_time:
        delv_time_ts = datetime.fromtimestamp(func_UTCToEpoch(delv_time))
        click_time_ts = datetime.fromtimestamp(func_UTCToEpoch(click_time))
        diff = click_time_ts - delv_time_ts
        seconds = diff.total_seconds()
    
    else:
        seconds = np.nan
    
    return seconds

In [19]:
df['Timelag (s)'] = df.apply(lambda x: calculate_timelag(x['Delivered Time'], x['Clicked time']), axis=1)

In [20]:
df = df[~(df['Timelag (s)'] < -10)]

In [21]:
df['Timelag (s)'] = df['Timelag (s)'].apply(lambda x: abs(x) if x==x else np.nan)

In [22]:
#df['SMS Length'] = len(df['Message'])
df['Num SMS Sent'] = np.ceil(df['SMS Length']/160)
df['Cost of All SMS Sent'] = 0.13 * df['Num SMS Sent'] #  cost_of_sms

In [23]:
df['Num words in SMS'] = df['Message'].apply(lambda x: len(x.split(' ')))

In [24]:
def convert_to_day_of_month(date_str):
    try:
        day_of_mon = datetime.fromtimestamp(func_UTCToEpoch(date_str)).day
    except:
        day_of_mon = np.nan
    return day_of_mon

In [25]:
df['Day of Month'] = df['Delivered Date'].apply(convert_to_day_of_month)

In [26]:
def mean_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    mean = np.nanmean(x_upd)
    return mean

def median_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    median = np.nanmedian(x_upd)
    return median

In [27]:
timelag = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Timelag (s)'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
timelag.rename(columns= {'mean': 'Avg Timelag (s)',
                        'median': 'Median Timelag (s)',
                         'mean_wo_0': 'Avg Timelag (s) wo 0',
                        'median_wo_0': 'Median Timelag (s) wo 0',
                        }, inplace=True)

/tmp/ipykernel_380522/3554248693.py:3: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(x_upd)
/home/aamin/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,

In [28]:
num_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_sms.rename(columns= {'mean': 'Avg Num SMS Sent',
                        'median': 'Median Num SMS Sent',
                        'mean_wo_0': 'Avg Num SMS Sent wo 0',
                        'median_wo_0': 'Median Num SMS Sent wo 0',
                        }, inplace=True)

In [29]:
cost_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Cost of All SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
cost_sms.rename(columns= {'mean': 'Avg Cost of All SMS Sent',
                        'median': 'Median Cost of All SMS Sent',
                         'mean_wo_0': 'Avg Cost of All SMS Sent wo 0',
                        'median_wo_0': 'Median Cost of All SMS Sent wo 0'}, inplace=True)

In [30]:
len_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['SMS Length'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
len_sms.rename(columns= {'mean': 'Avg SMS Length',
                        'median': 'Median SMS Length',
                        'mean_wo_0': 'Avg SMS Length wo 0',
                        'median_wo_0': 'Median SMS Length wo 0'}, inplace=True)

In [31]:
day_of_mon = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Day of Month'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
day_of_mon.rename(columns= {'mean': 'Avg Day of Month',
                        'median': 'Median Day of Month',
                           'mean_wo_0': 'Avg Day of Month wo 0',
                        'median_wo_0': 'Median Day of Month wo 0'}, inplace=True)

In [32]:
num_words = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num words in SMS'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_words.rename(columns= {'mean': 'Avg Num Words',
                        'median': 'Median Num Words',
                          'mean_wo_0': 'Avg Num Words wo 0',
                        'median_wo_0': 'Median Num Words wo 0'}, inplace=True)

In [33]:
new_features = pd.merge(num_sms,cost_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,len_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,timelag, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,day_of_mon, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,num_words, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [34]:
new_features.fillna(0, inplace = True)

In [35]:
new_features

                                                Avg Num SMS Sent  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                         2.0
                                   1                         2.0
                                   2                         2.0
                                   11                        2.0
                                   12                        2.0
...                                                          ...
Karnataka kn           Sunday      15                        2.0
                                   16                        2.0
                                   17                        2.0
                                   19                        2.0
                                   20                        2.0

                                                Median Num SMS Sent  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                            2.0
                                   1                            2.0
                                   2                            2.0
                                   11                           2.0
                                   12                           2.0
...                                                             ...
Karnataka kn           Sunday      15                           2.0
                                   16                           2.0
                                   17                           2.0
                                   19                           2.0
                                   20                           2.0

                                                Avg Num SMS Sent wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                              2.0
                                   1                              2.0
                                   2                              2.0
                                   11                             2.0
                                   12                             2.0
...                                                               ...
Karnataka kn           Sunday      15                             2.0
                                   16                             2.0
                                   17                             2.0
                                   19                             2.0
                                   20                             2.0

                                                Median Num SMS Sent wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                 2.0
                                   1                                 2.0
                                   2                                 2.0
                                   11                                2.0
                                   12                                2.0
...                                                                  ...
Karnataka kn           Sunday      15                                2.0
                                   16                                2.0
                                   17                                2.0
                                   19                                2.0
                                   20                                2.0

                                                Avg Cost of All SMS Sent  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                0.26
                                   1                                0.26
                                   2                                0.26
                                   11                               0.26
                                   12                               0.26
...                                                                  ...
Karnataka kn           Sunday      15                               0.26
                                   16                               0.26
                                   17                               0.26
                                   19                               0.26
                                   20                               0.26

                                                Median Cost of All SMS Sent  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                   0.26
                                   1                                   0.26
                                   2                                   0.26
                                   11                                  0.26
                                   12                                  0.26
...                                                                     ...
Karnataka kn           Sunday      15                                  0.26
                                   16                                  0.26
                                   17                                  0.26
                                   19                                  0.26
                                   20                                  0.26

                                                Avg Cost of All SMS Sent wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                     0.26
                                   1                                     0.26
                                   2                                     0.26
                                   11                                    0.26
                                   12                                    0.26
...                                                                       ...
Karnataka kn           Sunday      15                                    0.26
                                   16                                    0.26
                                   17                                    0.26
                                   19                                    0.26
                                   20                                    0.26

                                                Median Cost of All SMS Sent wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                        0.26
                                   1                                        0.26
                                   2                                        0.26
                                   11                                       0.26
                                   12                                       0.26
...                                                                          ...
Karnataka kn           Sunday      15                                       0.26
                                   16                                       0.26
                                   17                                       0.26
                                   19                                       0.26
                                   20                                       0.26

                                                Avg SMS Length  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                       240
                                   1                       240
                                   2                       240
                                   11                      240
                                   12                      240
...                                                        ...
Karnataka kn           Sunday      15                      282
                                   16                      282
                                   17                      282
                                   19                      282
                                   20                      282

                                                Median SMS Length  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                          240
                                   1                          240
                                   2                          240
                                   11                         240
                                   12                         240
...                                                           ...
Karnataka kn           Sunday      15                         282
                                   16                         282
                                   17                         282
                                   19                         282
                                   20                         282

                                                Avg SMS Length wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                            240
                                   1                            240
                                   2                            240
                                   11                           240
                                   12                           240
...                                                             ...
Karnataka kn           Sunday      15                           282
                                   16                           282
                                   17                           282
                                   19                           282
                                   20                           282

                                                Median SMS Length wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                               240
                                   1                               240
                                   2                               240
                                   11                              240
                                   12                              240
...                                                                ...
Karnataka kn           Sunday      15                              282
                                   16                              282
                                   17                              282
                                   19                              282
                                   20                              282

                                                Avg Timelag (s)  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                   0.000000
                                   1                   0.000000
                                   2                   0.000000
                                   11               2136.095238
                                   12                  0.000000
...                                                         ...
Karnataka kn           Sunday      15                 59.000000
                                   16                  0.000000
                                   17                  0.000000
                                   19                 23.000000
                                   20                  0.000000

                                                Median Timelag (s)  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                           0.0
                                   1                           0.0
                                   2                           0.0
                                   11                          6.0
                                   12                          0.0
...                                                            ...
Karnataka kn           Sunday      15                         59.0
                                   16                          0.0
                                   17                          0.0
                                   19                         23.0
                                   20                          0.0

                                                Avg Timelag (s) wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                        0.000000
                                   1                        0.000000
                                   2                        0.000000
                                   11                    2136.095238
                                   12                       0.000000
...                                                              ...
Karnataka kn           Sunday      15                      59.000000
                                   16                       0.000000
                                   17                       0.000000
                                   19                      23.000000
                                   20                       0.000000

                                                Median Timelag (s) wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                0.0
                                   1                                0.0
                                   2                                0.0
                                   11                               6.0
                                   12                               0.0
...                                                                 ...
Karnataka kn           Sunday      15                              59.0
                                   16                               0.0
                                   17                               0.0
                                   19                              23.0
                                   20                               0.0

                                                Avg Day of Month  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                        25.0
                                   1                        25.0
                                   2                        25.0
                                   11                       16.0
                                   12                       16.0
...                                                          ...
Karnataka kn           Sunday      15                       14.0
                                   16                       14.0
                                   17                       14.0
                                   19                       14.0
                                   20                       14.0

                                                Median Day of Month  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                             25
                                   1                             25
                                   2                             25
                                   11                            16
                                   12                            16
...                                                             ...
Karnataka kn           Sunday      15                            14
                                   16                            14
                                   17                            14
                                   19                            14
                                   20                            14

                                                Avg Day of Month wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                             25.0
                                   1                             25.0
                                   2                             25.0
                                   11                            16.0
                                   12                            16.0
...                                                               ...
Karnataka kn           Sunday      15                            14.0
                                   16                            14.0
                                   17                            14.0
                                   19                            14.0
                                   20                            14.0

                                                Median Day of Month wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                                  25
                                   1                                  25
                                   2                                  25
                                   11                                 16
                                   12                                 16
...                                                                  ...
Karnataka kn           Sunday      15                                 14
                                   16                                 14
                                   17                                 14
                                   19                                 14
                                   20                                 14

                                                Avg Num Words  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                       34
                                   1                       34
                                   2                       34
                                   11                      34
                                   12                      34
...                                                       ...
Karnataka kn           Sunday      15                      31
                                   16                      31
                                   17                      31
                                   19                      31
                                   20                      31

                                                Median Num Words  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                          34
                                   1                          34
                                   2                          34
                                   11                         34
                                   12                         34
...                                                          ...
Karnataka kn           Sunday      15                         31
                                   16                         31
                                   17                         31
                                   19                         31
                                   20                         31

                                                Avg Num Words wo 0  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                            34
                                   1                            34
                                   2                            34
                                   11                           34
                                   12                           34
...                                                            ...

In [36]:
circle_df = pd.DataFrame(df.groupby(by = ['Circle', 
                                          #'Operator',
                                        'SMS Language',
                                          'Day of Week','Hour of Day']).Status.count())
circle_df.rename(columns= {'Status': 'sms_sent'}, inplace=True)
circle_df

                                                sms_sent
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                   3
                                   1                   1
                                   2                 145
                                   11                360
                                   12                 10
...                                                  ...
Karnataka kn           Sunday      15                 39
                                   16                  1
                                   17                 28
                                   19                 64
                                   20                225

[107 rows x 1 columns]

In [37]:
circle_delv= pd.DataFrame(df[df['Status']=='Delivered'].groupby(by = ['Circle',
                                                                      'SMS Language',
                                                                      'Day of Week','Hour of Day']).Status.count())
circle_delv.rename(columns= {'Status': 'sms_delivered'}, inplace=True)
circle_delv

                                                sms_delivered
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                        3
                                   1                        1
                                   2                        1
                                   11                     236
                                   12                       2
...                                                       ...
Karnataka kn           Sunday      15                      32
                                   16                       1
                                   17                      28
                                   19                       7
                                   20                       1

[91 rows x 1 columns]

In [38]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [39]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [40]:
circle_delv_rate_df.fillna(0, inplace = True)
circle_delv_rate_df['delivery_rate'] = circle_delv_rate_df['sms_delivered']*100 / circle_delv_rate_df['sms_sent']
circle_delv_rate_df

                                                sms_sent  sms_delivered  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                   3            3.0
                                   1                   1            1.0
                                   2                 145            1.0
                                   11                360          236.0
                                   12                 10            2.0
...                                                  ...            ...
Karnataka kn           Sunday      15                 39           32.0
                                   16                  1            1.0
                                   17                 28           28.0
                                   19                 64            7.0
                                   20                225            1.0

                                                delivery_rate
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0               100.000000
                                   1               100.000000
                                   2                 0.689655
                                   11               65.555556
                                   12               20.000000
...                                                       ...
Karnataka kn           Sunday      15               82.051282
                                   16              100.000000
                                   17              100.000000
                                   19               10.937500
                                   20                0.444444

[107 rows x 3 columns]

In [41]:
click= pd.DataFrame(df[df['Clicked Date']==df['Clicked Date']].groupby(by = ['Circle', 'SMS Language',
                                                                                           'Day of Week','Hour of Day']
                                                                                    ).Status.count())
click.rename(columns= {'Status': 'sms_clicked'}, inplace=True)
click

                                                sms_clicked
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      11                    21
                       Monday      19                   521
                       Thursday    13                   401
                                   17                     1
                                   18                     1
                                   20                   275
          hi           Monday      12                   626
                                   13                    35
                                   14                     4
                                   16                     1
                       Thursday    10                   577
                                   11                     5
                                   12                     1
                                   13                     1
                                   15                     2
Hyderabad en           Friday      11                    50
                                   12                     2
                                   14                    33
                                   15                    26
                                   19                     2
                       Tuesday     13                    26
                                   17                     1
          hi           Tuesday     11                    52
Karnataka en           Friday      11                    30
                                   12                     8
                                   13                     3
                                   15                     7
                                   16                   415
                                   17                     7
                                   18                     3
                                   19                     1
                                   21                    10
                                   22                     1
                       Wednesday   16                    15
                                   17                     1
          hi           Friday      10                   640
                                   11                   662
                                   12                     2
                                   13                     3
                                   14                     2
                                   15                    11
                                   16                    13
                                   17                     2
                       Thursday    16                   238
                                   17                    24
                                   18                     2
                                   19                     2
                                   20                     2
                                   21                     1
          kn           Saturday    10                   356
                                   11                     3
                                   13                     2
                                   15                     1
                       Sunday      14                   357
                                   15                     1
                                   19                     1

In [42]:
click_rate_df = pd.merge(circle_delv_rate_df,click, how= 'outer', 
                         on = ['Circle','SMS Language','Day of Week','Hour of Day'])
click_rate_df.fillna(0, inplace = True)
click_rate_df['clicked_rate'] = click_rate_df['sms_clicked']*100 / click_rate_df['sms_delivered']
click_rate_df.fillna(0, inplace = True)
click_rate_df

                                                sms_sent  sms_delivered  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                   3            3.0
                                   1                   1            1.0
                                   2                 145            1.0
                                   11                360          236.0
                                   12                 10            2.0
...                                                  ...            ...
Karnataka kn           Sunday      15                 39           32.0
                                   16                  1            1.0
                                   17                 28           28.0
                                   19                 64            7.0
                                   20                225            1.0

                                                delivery_rate  sms_clicked  \
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0               100.000000          0.0
                                   1               100.000000          0.0
                                   2                 0.689655          0.0
                                   11               65.555556         21.0
                                   12               20.000000          0.0
...                                                       ...          ...
Karnataka kn           Sunday      15               82.051282          1.0
                                   16              100.000000          0.0
                                   17              100.000000          0.0
                                   19               10.937500          1.0
                                   20                0.444444          0.0

                                                clicked_rate
Circle    SMS Language Day of Week Hour of Day
Delhi     en           Friday      0                0.000000
                                   1                0.000000
                                   2                0.000000
                                   11               8.898305
                                   12               0.000000
...                                                      ...
Karnataka kn           Sunday      15               3.125000
                                   16               0.000000
                                   17               0.000000
                                   19              14.285714
                                   20               0.000000

[107 rows x 5 columns]

In [43]:
final_df = pd.merge(click_rate_df,new_features, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [44]:
final_df = final_df.reset_index()

In [48]:
final_df.to_csv("aggregated_data_of_tie_up_data.csv")

In [47]:
final_df[final_df["clicked_rate"] > 10]

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
6,Delhi,en,Monday,19,7797,5205.0,66.756445,521.0,10.009606,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,1740.955854,5.0,1740.955854,5.0,5.000000,5,5.000000,5,34,34,34,34
11,Delhi,en,Thursday,13,5257,3561.0,67.738254,401.0,11.260882,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,13157.269327,6.0,13157.269327,6.0,24.000000,24,24.000000,24,34,34,34,34
15,Delhi,en,Thursday,17,12,9.0,75.000000,1.0,11.111111,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,3.000000,3.0,3.000000,3.0,24.000000,24,24.000000,24,34,34,34,34
16,Delhi,en,Thursday,18,10,5.0,50.000000,1.0,20.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,9.000000,9.0,9.000000,9.0,24.000000,24,24.000000,24,34,34,34,34
18,Delhi,en,Thursday,20,2487,1809.0,72.738239,275.0,15.201769,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,20501.745455,5.0,20501.745455,5.0,24.000000,24,24.000000,24,34,34,34,34
25,Delhi,hi,Monday,13,673,339.0,50.371471,35.0,10.324484,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,7707.142857,24.0,7707.142857,24.0,5.000000,5,5.000000,5,41,41,41,41
32,Delhi,hi,Thursday,10,4926,4586.0,93.097848,577.0,12.581771,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,25007.003466,8.0,25007.003466,8.0,24.000000,24,24.000000,24,41,41,41,41
37,Delhi,hi,Thursday,15,16,11.0,68.750000,2.0,18.181818,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,5289.000000,5289.0,5289.000000,5289.0,24.000000,24,24.000000,24,41,41,41,41
40,Hyderabad,en,Friday,11,1432,496.0,34.636872,50.0,10.080645,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.160000,2.0,2.347826,2.0,16.000000,16,16.000000,16,34,34,34,34
41,Hyderabad,en,Friday,12,54,4.0,7.407407,2.0,50.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,16.000000,16,16.000000,16,34,34,34,34
43,Hyderabad,en,Friday,14,659,265.0,40.212443,33.0,12.452830,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,21.515152,4.0,21.515152,4.0,18.000000,18,18.000000,18,34,34,34,34
47,Hyderabad,en,Friday,19,3,3.0,100.000000,2.0,66.666667,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,9.000000,9.0,9.000000,9.0,18.000000,18,18.000000,18,34,34,34,34
50,Hyderabad,en,Tuesday,13,731,253.0,34.610123,26.0,10.276680,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,4.538462,4.0,4.538462,4.0,6.000000,6,6.000000,6,34,34,34,34
52,Hyderabad,en,Tuesday,17,1,1.0,100.000000,1.0,100.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,5.000000,5.0,5.000000,5.0,6.000000,6,6.000000,6,34,34,34,34
54,Hyderabad,hi,Tuesday,11,628,439.0,69.904459,52.0,11.845103,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,10.173077,7.5,10.173077,7.5,6.000000,6,6.000000,6,41,41,41,41
70,Karnataka,en,Friday,21,91,72.0,79.120879,10.0,13.888889,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,3484.400000,20.0,3484.400000,20.0,2.615385,2,2.615385,2,34,34,34,34
71,Karnataka,en,Friday,22,484,9.0,1.859504,1.0,11.111111,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,3.000000,3.0,3.000000,3.0,2.000000,2,2.000000,2,34,34,34,34
73,Karnataka,en,Wednesday,17,9,4.0,44.444444,1.0,25.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240,240,240,240,2.000000,2.0,2.000000,2.0,7.000000,7,7.000000,7,34,34,34,34
87,Karnataka,hi,Thursday,16,2167,2010.0,92.754961,238.0,11.840796,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,4985.168067,8.0,4985.168067,8.0,24.000000,24,24.000000,24,41,41,41,41
88,Karnataka,hi,Thursday,17,387,238.0,61.498708,24.0,10.084034,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,2537.416667,7.5,2537.416667,7.5,24.000000,24,24.000000,24,41,41,41,41
89,Karnataka,hi,Thursday,18,22,11.0,50.000000,2.0,18.181818,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,468675.000000,468675.0,468675.000000,468675.0,24.000000,24,24.000000,24,41,41,41,41
90,Karnataka,hi,Thursday,19,8,7.0,87.500000,2.0,28.571429,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,36.500000,36.5,36.500000,36.5,24.000000,24,24.000000,24,41,41,41,41
91,Karnataka,hi,Thursday,20,10,10.0,100.000000,2.0,20.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,261,261,261,261,13.500000,13.5,13.500000,13.5,24.000000,24,24.000000,24,41,41,41,41
95,Karnataka,kn,Saturday,10,3480,3088.0,88.735632,356.0,11.528497,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,282,282,282,282,8617.457865,25.0,8641.732394,25.0,13.000000,13,13.000000,13,31,31,31,31
98,Karnataka,kn,Saturday,13,19,19.0,100.000000,2.0,10.526316,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,282,282,282,282,39.500000,39.5,39.500000,39.5,13.000000,13,13.000000,13,31,31,31,31
99,Karnataka,kn,Saturday,15,75,7.0,9.333333,1.0,14.285714,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,282,282,282,282,41.000000,41.0,41.000000,41.0,13.000000,13,13.000000,13,31,31,31,31
101,Karnataka,kn,Sunday,14,3523,3129.0,88.816350,357.0,11.409396,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,282,282,282,282,26541.338936,7.0,27227.752874,7.0,14.000000,14,14.000000,14,31,31,31,31
105,Karnataka,kn,Sunday,19,64,7.0,10.937500,1.0,14.285714,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,282,282,282,282,23.000000,23.0,23.000000,23.0,14.000000,14,14.000000,14,31,31,31,31

In [42]:
final_data_2 = pd.read_csv("/home/aamin/files/marketing/final_leads_aggregated_data.csv")

In [68]:
final_data_2

,SN,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,0,Andhra Pradesh,en,Friday,2,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.000000,240.0,240.000000,240.0,0.000000,0.0,0.000000,0.0,25.000000,25.0,25.000000,25.0,34.000000,34.0,34.000000,34.0
1,1,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0
2,2,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.655128,2.0,19488.448494,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0
3,3,Andhra Pradesh,en,Friday,11,2860,591.0,20.664336,56.0,9.475465,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.969930,240.0,239.969930,240.0,2.446429,2.0,2.634615,2.0,9.020280,16.0,9.020280,16.0,33.996503,34.0,33.996503,34.0
4,4,Andhra Pradesh,en,Friday,12,868,646.0,74.423963,107.0,16.563467,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,263.419355,268.0,263.419355,268.0,7641.570093,25.0,7938.330097,26.0,11.649770,12.0,11.649770,12.0,36.509217,37.0,36.509217,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,2711,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2712,2712,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2713,2713,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2714,2714,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0
2715,2715,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0

In [48]:
final_df['SN'] = np.arange(0,2715).tolist()

In [51]:
final_df = final_df[['SN', 'Circle', 'SMS Language', 'Day of Week', 'Hour of Day',
       'sms_sent', 'sms_delivered', 'delivery_rate', 'sms_clicked',
       'clicked_rate', 'Avg Num SMS Sent', 'Median Num SMS Sent',
       'Avg Num SMS Sent wo 0', 'Median Num SMS Sent wo 0',
       'Avg Cost of All SMS Sent', 'Median Cost of All SMS Sent',
       'Avg Cost of All SMS Sent wo 0', 'Median Cost of All SMS Sent wo 0',
       'Avg SMS Length', 'Median SMS Length', 'Avg SMS Length wo 0',
       'Median SMS Length wo 0', 'Avg Timelag (s)', 'Median Timelag (s)',
       'Avg Timelag (s) wo 0', 'Median Timelag (s) wo 0', 'Avg Day of Month',
       'Median Day of Month', 'Avg Day of Month wo 0',
       'Median Day of Month wo 0', 'Avg Num Words', 'Median Num Words',
       'Avg Num Words wo 0', 'Median Num Words wo 0']]

In [60]:
final_data_2[final_data_2.isin(final_df) == False]

,SN,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.010846,NaN,NaN,NaN,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2497.259740,NaN,2497.259740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.923558,NaN,10.020555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.972196,NaN,239.972196,NaN,15765.655128,NaN,19488.448494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.475465,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,239.969930,NaN,239.969930,NaN,2.446429,NaN,2.634615,NaN,NaN,NaN,NaN,NaN,33.996503,NaN,33.996503,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74.423963,NaN,16.563467,NaN,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7641.570093,NaN,7938.330097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2711,NaN,NaN,NaN,NaN,10.0,50.0,47.0,94.000000,3.0,6.382979,NaN,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.666667,49.0,44.666667,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2712,NaN,NaN,NaN,NaN,11.0,NaN,1.0,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2713,NaN,NaN,NaN,Saturday,16.0,1.0,0.0,0.000000,0.0,0.000000,NaN,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,NaN,NaN,NaN,NaN
2714,NaN,NaN,NaN,NaN,14.0,50.0,47.0,94.000000,3.0,6.382979,NaN,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.333333,4.0,5.333333,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2715,2715.0,West Bengal-Andaman Nicobar,mr,Sunday,20.0,2.0,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.0,14.0,14.0,14.0,34.000000,34.0,34.000000,34.0

In [61]:
final_df.to_csv('mkting_cmpgn_data_wo_existing_users_2.csv', index=False)

In [62]:
df_2 = pd.read_csv("/home/aamin/files/marketing/copy/mkting_cmpgn_data_wo_existing_users.csv")

In [66]:
df_2

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0,0
1,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0,1
2,Andhra Pradesh,en,Friday,11,2238,366.0,16.353887,34.0,9.289617,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.961573,240.0,239.961573,240.0,2.794118,2.0,2.968750,2.5,7.080429,2.0,7.080429,2.0,33.995532,34.0,33.995532,34.0,2
3,Andhra Pradesh,en,Friday,12,832,633.0,76.081731,106.0,16.745656,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,264.432692,268.0,264.432692,268.0,7713.801887,25.5,8016.303922,27.0,11.331731,12.0,11.331731,12.0,36.617788,37.0,36.617788,37.0,3
4,Andhra Pradesh,en,Friday,13,12,10.0,83.333333,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.666667,268.0,258.666667,268.0,0.000000,0.0,0.000000,0.0,11.000000,12.0,11.000000,12.0,36.000000,37.0,36.000000,37.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2144
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2145
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2146
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2147
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2148

In [69]:
new_data = pd.concat([final_df,df_2])

In [71]:
new_data.drop("SN",axis=1,inplace=True)

In [72]:
new_data

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,02,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,25.0,25.0,25.0,25.0,34.0,34.0,34.0,34.0
1,Andhra Pradesh,en,Friday,11,622,225.0,36.173633,22.0,9.777778,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,2.000000,2.0,2.200000,2.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
2,Andhra Pradesh,en,Friday,12,36,13.0,36.111111,1.0,7.692308,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,5.000000,5.0,5.000000,5.0,19.0,16.0,19.0,16.0,34.0,34.0,34.0,34.0
3,Andhra Pradesh,en,Friday,13,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,0.000000,0.0,0.000000,0.0,16.0,16.0,16.0,16.0,34.0,34.0,34.0,34.0
4,Andhra Pradesh,en,Friday,14,580,245.0,42.241379,29.0,11.836735,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.0,240.0,240.0,240.0,23.758621,4.0,23.758621,4.0,18.0,18.0,18.0,18.0,34.0,34.0,34.0,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,44.666667,49.0,44.666667,49.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2145,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2146,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,13.0,13.0,13.0,13.0,34.0,34.0,34.0,34.0
2147,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,5.333333,4.0,5.333333,4.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0
2148,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.0,258.0,258.0,258.0,0.000000,0.0,0.000000,0.0,14.0,14.0,14.0,14.0,34.0,34.0,34.0,34.0

In [73]:
new_data['SN'] = np.arange(0,3013).tolist()

In [75]:
new_data.to_csv('mkting_cmpgn_data_wo_existing_users_3.csv', index=False)