In [1]:
import pandas as pd
import numpy as np
import os
import datetime
from datetime import date
import calendar
pd.set_option('display.max_columns', None)

In [63]:
!! pip install langdetect

['Collecting langdetect',
 '  Downloading langdetect-1.0.9.tar.gz (981 kB)',
 'Requirement already satisfied: six in /home/aamin/.local/lib/python3.8/site-packages (from langdetect) (1.13.0)',
 'Building wheels for collected packages: langdetect',
 '  Building wheel for langdetect (setup.py): started',
 "  Building wheel for langdetect (setup.py): finished with status 'done'",
 '  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993222 sha256=29e7a40ab0e4bc51d64b6d84122010ffc4625374f9ff9d91a200d42f38c5ca23',
 '  Stored in directory: /home/aamin/.cache/pip/wheels/13/c7/b0/79f66658626032e78fc1a83103690ef6797d551cb22e56e734',
 'Successfully built langdetect',
 'Installing collected packages: langdetect',
 'Successfully installed langdetect-1.0.9']

In [2]:
from langdetect import detect

In [3]:
def convert_to_day_of_week(date_str):
    try:
        date_ = datetime.date.fromisoformat(date_str)
        weekday = calendar.day_name[date_.weekday()]
    except:
        weekday = np.nan
    return weekday

#### Reports

In [4]:
camp_dir_path = r'/home/aamin/files/marketing/copy/Reports-20221122T082008Z-001/Reports'
camp_filename_list = []
for path in os.scandir(camp_dir_path):
    if path.is_file():
        camp_filename_list.append(path.name)

In [5]:
camp_clickreport_filename_list = [i for i in camp_filename_list if 'Click' in i]
camp_delvreport_filename_list = [i for i in camp_filename_list if 'Delivery' in i]

camp_path_to_reports = '/home/aamin/files/marketing/copy/Reports-20221122T082008Z-001/Reports'

camp_sms_delivery_df = pd.DataFrame()

for file in camp_delvreport_filename_list:
    
    camp_temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
    camp_sms_delivery_df = pd.concat([camp_sms_delivery_df, camp_temp_delivery_df])
    
camp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
camp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [6]:
camp_sms_delivery_df['Delivered Date'] = camp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_delivery_df['Delivery Time'] = camp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_delivery_df['Hour of Day'] = camp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_delivery_df['Day of Week'] = camp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
camp_sms_delivery_df['SMS Language'] = camp_sms_delivery_df["Message"].apply(lambda x: detect(x))

In [62]:
camp_sms_delivery_df[camp_sms_delivery_df["Delivered Time"].str.contains("2022")]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Message,Published date,Delivered Time,Status,Remark,Operator,Circle,Delivered Date,Delivery Time,Hour of Day,Day of Week,SMS Language
0,5101,India Gold 0407,7382097083,GOLD187,"Dear Customer, As a valued MyShubhLife custome...",NaN,2022-07-04 11:46:47,Delivered,Delivered,Idea,Andhra Pradesh,2022-07-04,11:46:47,11,Monday,en
1,5101,India Gold 0407,7228075710,GOLD387,"Dear Customer, As a valued MyShubhLife custome...",NaN,2022-07-04 11:46:49,Delivered,Delivered,Airtel,Gujarat,2022-07-04,11:46:49,11,Monday,en
2,5101,India Gold 0407,9834386974,GOLD330,"Dear Customer, As a valued MyShubhLife custome...",NaN,2022-07-04 12:47:50,Delivered,Delivered,Reliance JIO,Maharashtra-Goa,2022-07-04,12:47:50,12,Monday,en
3,5101,India Gold 0407,7620464393,GOLD573,"Dear Customer, As a valued MyShubhLife custome...",NaN,2022-07-04 11:46:50,Delivered,Delivered,Reliance JIO,Maharashtra-Goa,2022-07-04,11:46:50,11,Monday,en
4,5101,India Gold 0407,8744048700,GOLD145,"Dear Customer, As a valued MyShubhLife custome...",NaN,2022-07-04 11:46:50,Delivered,Delivered,Vodafone,Delhi,2022-07-04,11:46:50,11,Monday,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312227,4706,Personal Loan Pre-Approved 3004,9620011277,APPROVE841,"Dear Customer, Exclusive offer! Get Pre-approv...",NaN,2022-04-30 19:19:21,undelivered,number invalid,Vodafone,Karnataka,2022-04-30,19:19:21,19,Saturday,en
312228,4706,Personal Loan Pre-Approved 3004,8860663006,APPROVE2415,"Dear Customer, Exclusive offer! Get Pre-approv...",NaN,2022-04-30 19:19:24,Delivered,Delivered,Vodafone,Delhi,2022-04-30,19:19:24,19,Saturday,en
312229,4706,Personal Loan Pre-Approved 3004,9220168684,APPROVE954,"Dear Customer, Exclusive offer! Get Pre-approv...",NaN,2022-04-30 19:19:23,Delivered,Delivered,Vodafone,Mumbai,2022-04-30,19:19:23,19,Saturday,en
312230,4706,Personal Loan Pre-Approved 3004,9092288845,APPROVE1020,"Dear Customer, Exclusive offer! Get Pre-approv...",NaN,2022-04-30 19:20:00,Delivered,Delivered,Airtel,Chennai,2022-04-30,19:20:00,19,Saturday,en
312231,4706,Personal Loan Pre-Approved 3004,8778163041,APPROVE1441,"Dear Customer, Exclusive offer! Get Pre-approv...",NaN,2022-04-30 19:19:23,Delivered,Delivered,Reliance JIO,Tamil Nadu-Chennai,2022-04-30,19:19:23,19,Saturday,en

In [61]:
len(camp_sms_delivery_df["Broadcast name"].unique())

52

In [51]:
camp_sms_delivery_df[camp_sms_delivery_df["Broadcast name"] == "Big C 2903"].iloc[0,4]

'Dear Customer, Bring home the Happiness this May! MyShubhLife offers various loans to suit your requirement at attractive interest rates. Apply for a personal loan from Rs.3K-2L here https://mshblf.page.link/NwhQ - Team MyShubhLife'

#### Reports from 2021

In [8]:
campp_dir_path = r'/home/aamin/files/marketing/copy/Report from 2021-20221122T082040Z-001/Report from 2021'
campp_filename_list = []
for path in os.scandir(campp_dir_path):
    if path.is_file():
        campp_filename_list.append(path.name)

In [9]:
campp_clickreport_filename_list = [i for i in campp_filename_list if 'Click' in i]
campp_delvreport_filename_list = [i for i in campp_filename_list if 'Delivery' in i]

campp_path_to_reports = '/home/aamin/files/marketing/copy/Report from 2021-20221122T082040Z-001/Report from 2021'

campp_sms_delivery_df = pd.DataFrame()

for file in campp_delvreport_filename_list:
    
    campp_temp_delivery_df = pd.read_csv(f'{campp_path_to_reports}/{file}')
    campp_sms_delivery_df = pd.concat([campp_sms_delivery_df, campp_temp_delivery_df])
    
campp_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
campp_sms_delivery_df.reset_index(inplace=True, drop=True)

In [10]:
campp_sms_delivery_df['Delivered Date'] = campp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
campp_sms_delivery_df['Delivery Time'] = campp_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
campp_sms_delivery_df['Hour of Day'] = campp_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
campp_sms_delivery_df['Day of Week'] = campp_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
campp_sms_delivery_df['SMS Language'] = campp_sms_delivery_df["Message"].apply(lambda x: detect(x))

In [57]:
campp_sms_delivery_df[campp_sms_delivery_df["Delivered Time"].str.contains("2021")]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Message,Published date,Delivered Time,Status,Remark,Operator,Circle,Delivered Date,Delivery Time,Hour of Day,Day of Week,SMS Language
0,2181,DR ON CALL 1808,8105641569,DRONCALL1500,"Dear [NAME], Complimentary DOCTOR ON CALL offe...",NaN,2021-08-18 17:02:18,Delivered,Delivered,Airtel,Karnataka,2021-08-18,17:02:18,17,Wednesday,en
1,2181,DR ON CALL 1808,9148094245,DRONCALL0624,"Dear [NAME], Complimentary DOCTOR ON CALL offe...",NaN,2021-08-18 22:02:24,Delivered,Delivered,"Shyam Telelink, Rainbow CDMA",Orissa,2021-08-18,22:02:24,22,Wednesday,en
2,2181,DR ON CALL 1808,9849791186,DRONCALL0622,"Dear [NAME], Complimentary DOCTOR ON CALL offe...",NaN,2021-08-18 17:02:17,undelivered,expired,Airtel,Andhra Pradesh,2021-08-18,17:02:17,17,Wednesday,en
3,2181,DR ON CALL 1808,9686743525,DRONCALL0637,"Dear [NAME], Complimentary DOCTOR ON CALL offe...",NaN,2021-08-18 17:02:19,Delivered,Delivered,Airtel,Karnataka,2021-08-18,17:02:19,17,Wednesday,en
4,2181,DR ON CALL 1808,9591279144,DRONCALL0635,"Dear [NAME], Complimentary DOCTOR ON CALL offe...",NaN,2021-08-18 17:02:18,Delivered,Delivered,Airtel,Karnataka,2021-08-18,17:02:18,17,Wednesday,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272881,3169,Bangalore Tieups 1411,9341838144,BANGALORE3102,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,2021-11-14 14:03:06,Delivered,Delivered,Reliance CDMA,Karnataka,2021-11-14,14:03:06,14,Sunday,kn
272882,3169,Bangalore Tieups 1411,9731077561,BANGALORE1474,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,2021-11-14 14:03:22,Delivered,Delivered,Reliance JIO,Karnataka,2021-11-14,14:03:22,14,Sunday,kn
272883,3169,Bangalore Tieups 1411,8217085312,BANGALORE2732,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,2021-11-14 14:04:14,Delivered,Delivered,Reliance JIO,Karnataka,2021-11-14,14:04:14,14,Sunday,kn
272884,3169,Bangalore Tieups 1411,8496878926,BANGALORE400,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,2021-11-14 14:03:03,Delivered,Delivered,Vodafone,Karnataka,2021-11-14,14:03:03,14,Sunday,kn
272885,3169,Bangalore Tieups 1411,9611898924,BANGALORE1427,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,2021-11-14 20:03:20,undelivered,undelivered,Idea,Karnataka,2021-11-14,20:03:20,20,Sunday,kn

In [63]:
campp_sms_delivery_df["SMS Language"]

en    131017
mr     76488
hi     57234
kn      7822
te       325
Name: SMS Language, dtype: int64

In [64]:
camp_sms_delivery_df.groupby(["Broadcast name","SMS Language"]).count()

,,Broadcast ID,Mobile number,Primary Key (User_id),Message,Published date,Delivered Time,Status,Remark,Operator,Circle,Delivered Date,Delivery Time,Hour of Day,Day of Week
Broadcast name,SMS Language,,,,,,,,,,,,,,
Big C 2903,en,197,197,197,197,0,197,197,197,197,197,197,197,197,197
Chota Loan Top Up 1104,en,58,58,58,58,0,58,58,58,58,58,58,58,58,58
Cognizant 1105,en,4343,4343,4343,4343,0,4343,4343,4343,4343,4343,4343,4343,4343,4343
Communication_For_NACH_Rejection 2502,en,680,680,680,680,0,680,680,680,680,680,680,680,680,680
Communication_Marketing_Dropout_0301,en,11146,11146,11146,11146,0,11146,11146,11146,11146,11146,11146,11146,11146,11146
Copy:2022-09-26 12:26:41-RBH Navratri New Customers 2609,en,83629,83629,83629,83629,0,83629,83629,83629,83629,83629,83629,83629,83629,83629
Credit Mantri 0106,en,4226,4226,4226,4226,0,4226,4226,4226,4226,4226,4226,4226,4226,4226
Credit Mantri 3105,en,4229,4229,4229,4229,0,4229,4229,4229,4229,4229,4229,4229,4229,4229
Duster Solutions 0104,en,3223,3223,3223,3223,0,3223,3223,3223,3223,3223,3223,3223,3223,3223
FinPedia 0106,en,8385,8385,8385,8385,0,8385,8385,8385,8385,8385,8385,8385,8385,8385
FinPedia 0806,en,16606,16606,16606,16606,0,16606,16606,16606,16606,16606,16606,16606,16606,16606
FinPedia 0906,en,16598,16598,16598,16598,0,16598,16598,16598,16598,16598,16598,16598,16598,16598
Hinduja Global Solutions 2903,en,130,130,130,130,0,130,130,130,130,130,130,130,130,130
ISS Mumbai 3003,en,777,777,777,777,0,777,777,777,777,777,777,777,777,777
India Gold 0407,en,1001,1001,1001,1001,0,1001,1001,1001,1001,1001,1001,1001,1001,1001
Krishna Pharma 2903,en,527,527,527,527,0,527,527,527,527,527,527,527,527,527
MUTHOOT GOLD LOAN 1302,en,710,710,710,710,0,710,710,710,710,710,710,710,710,710
MUTHOOT GOLD LOAN 1403,en,444,444,444,444,0,444,444,444,444,444,444,444,444,444
MUTHOOT GOLD LOAN 1701,en,729,729,729,729,0,729,729,729,729,729,729,729,729,729
MUTHOOT GOLD LOAN 2204,en,2286,2286,2286,2286,0,2286,2286,2286,2286,2286,2286,2286,2286,2286
Medplus 1304,en,1723,1723,1723,1723,0,1723,1723,1723,1723,1723,1723,1723,1723,1723
Personal Loan Pre-Approved 3004,en,2579,2579,2579,2579,0,2579,2579,2579,2579,2579,2579,2579,2579,2579
Play Store Rating 0906,en,1460,1460,1460,1460,0,1460,1460,1460,1460,1460,1460,1460,1460,1460
Quess 2105,en,2603,2603,2603,2603,0,2603,2603,2603,2603,2603,2603,2603,2603,2603
Quess 2805,en,1339,1339,1339,1339,0,1339,1339,1339,1339,1339,1339,1339,1339,1339
Quess 3105,en,1339,1339,1339,1339,0,1339,1339,1339,1339,1339,1339,1339,1339,1339
RBH Dussehra New Customers 0510,en,1937,1937,1937,1937,0,1937,1937,1937,1937,1937,1937,1937,1937,1937
RBH Navratri New Customers 2609,en,1937,1937,1937,1937,0,1937,1937,1937,1937,1937,1937,1937,1937,1937
RNR Cases 0106,en,5812,5812,5812,5812,0,5812,5812,5812,5812,5812,5812,5812,5812,5812
RNR Cases 0206,en,6157,6157,6157,6157,0,6157,6157,6157,6157,6157,6157,6157,6157,6157
RNR Cases 2105,en,2243,2243,2243,2243,0,2243,2243,2243,2243,2243,2243,2243,2243,2243
RNR Cases 2206,en,4471,4471,4471,4471,0,4471,4471,4471,4471,4471,4471,4471,4471,4471
RNR Cases 22062022,en,4577,4577,4577,4577,0,4577,4577,4577,4577,4577,4577,4577,4577,4577
RNR Cases 2406,en,4687,4687,4687,4687,0,4687,4687,4687,4687,4687,4687,4687,4687,4687
RNR Cases 2507,en,2146,2146,2146,2146,0,2146,2146,2146,2146,2146,2146,2146,2146,2146
RNR Cases 2607,en,2120,2120,2120,2120,0,2120,2120,2120,2120,2120,2120,2120,2120,2120
RNR Cases 2707,en,1953,1953,1953,1953,0,1953,1953,1953,1953,1953,1953,1953,1953,1953
RNR Cases 2806,en,4928,4928,4928,4928,0,4928,4928,4928,4928,4928,4928,4928,4928,4928
RNR Cases 3006,en,5166,5166,5166,5166,0,5166,5166,5166,5166,5166,5166,5166,5166,5166
RNR Cases 3105,en,4808,4808,4808,4808,0,4808,4808,4808,4808,4808,4808,4808,4808,4808
Tie Up 0209,en,83527,83527,83527,83527,0,83527,83527,83527,83527,83527,83527,83527,83527,83527
Tie Up ASPPL 0709,en,233,233,233,233,0,233,233,233,233,233,233,233,233,233
Tie Up ASPPL 1609,en,233,233,233,233,0,233,233,233,233,233,233,233,233,233
Tie Up Avtar 1609,en,375,375,375,375,0,375,375,375,375,375,375,375,375,375
Tie Up Cognizant 0909,en,391,391,391,391,0,391,391,391,391,391,391,391,391,391
Tie Up Cognizant 1609,en,780,780,780,780,0,780,780,780,780,780,780,780,780,780
Tie Up Vinolya 0909,en,300,300,300,300,0,300,300,300,300,300,300,300,300,300
Tie Up Vinolya 1609,en,781,781,781,781,0,781,781,781,781,781,781,781,781,781
Will Do Customers 1605,en,588,588,588,588,0,588,588,588,588,588,588,588,588,588
Will Do Customers 2206,en,420,420,420,420,0,420,420,420,420,420,420,420,420,420
Will Do Customers 22062022,en,420,420,420,420,0,420,420,420,420,420,420,420,420,420
Will Do Customers 2707,en,275,275,275,275,0,275,275,275,275,275,275,275,275,275

In [76]:
campp_sms_delivery_df[["SMS Language","Broadcast name"]].drop_duplicates().groupby(["SMS Language"]).count()

              Broadcast name
SMS Language
en                        21
hi                         5
kn                         2
mr                         2
te                         2

In [68]:
campp_sms_delivery_df.groupby(["SMS Language","Broadcast name"]).count()

                                              Broadcast ID  Mobile number  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909                  1001           1001
             Big C Hyderabad 1211                    37892          37892
             Chota Loan_Top up 2211                    129            129
             DR ON CALL 1808                          1519           1519
             Hinduja Global Solutions 1211           37819          37819
             INCOMPLETE INFO 2010                      225            225
             INCOMPLETE_INFO 1309                      953            953
             ISS Mumbai 1211                         38244          38244
             MUTHOOT GOLD CAMPAIGN 2209               1242           1242
             MUTHOOT GOLD LOAN 1310                    657            657
             MUTHOOT GOLD LOAN 1311                    486            486
             MUTHOOT GOLD LOAN 1411                   1738           1738
             MUTHOOT GOLD LOAN 1610                   1269           1269
             MUTHOOT GOLD LOAN 1810                   1221           1221
             MUTHOOT GOLD LOAN 2010                   1630           1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510           552            552
             Medplus EMP 1311                         1984           1984
             Personal Loan_Top up 2211                 161            161
             Personal Loan_Top up 2211 New             161            161
             Quess SMS 2211                            654            654
             TOPUP 1808                               1480           1480
hi           DTSS Delhi 1211                         40918          40918
             DTSS Delhi 1311                          3223           3223
             DTSS Delhi 1411                          3223           3223
             UDS Delhi 1311                           4935           4935
             UDS Delhi 1411                           4935           4935
kn           Bangalore Tieups 1311                    3911           3911
             Bangalore Tieups 1411                    3911           3911
mr           ISS Mumbai 1311                         38244          38244
             ISS Mumbai 1411                         38244          38244
te           Big C Hyderabad 1311                      197            197
             Hinduja Global Solutions 1411             128            128

                                              Primary Key (User_id)  Message  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909                           1001     1001
             Big C Hyderabad 1211                             37892    37892
             Chota Loan_Top up 2211                             129      129
             DR ON CALL 1808                                   1519     1519
             Hinduja Global Solutions 1211                    37819    37819
             INCOMPLETE INFO 2010                               225      225
             INCOMPLETE_INFO 1309                               953      953
             ISS Mumbai 1211                                  38244    38244
             MUTHOOT GOLD CAMPAIGN 2209                        1242     1242
             MUTHOOT GOLD LOAN 1310                             657      657
             MUTHOOT GOLD LOAN 1311                             486      486
             MUTHOOT GOLD LOAN 1411                            1738     1738
             MUTHOOT GOLD LOAN 1610                            1269     1269
             MUTHOOT GOLD LOAN 1810                            1221     1221
             MUTHOOT GOLD LOAN 2010                            1630     1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510                    552      552
             Medplus EMP 1311                                  1984     1984
             Personal Loan_Top up 2211                          161      161
             Personal Loan_Top up 2211 New                      161      161
             Quess SMS 2211                                     654      654
             TOPUP 1808                                        1480     1480
hi           DTSS Delhi 1211                                  40918    40918
             DTSS Delhi 1311                                   3223     3223
             DTSS Delhi 1411                                   3223     3223
             UDS Delhi 1311                                    4935     4935
             UDS Delhi 1411                                    4935     4935
kn           Bangalore Tieups 1311                             3911     3911
             Bangalore Tieups 1411                             3911     3911
mr           ISS Mumbai 1311                                  38244    38244
             ISS Mumbai 1411                                  38244    38244
te           Big C Hyderabad 1311                               197      197
             Hinduja Global Solutions 1411                      128      128

                                              Published date  Delivered Time  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909                       0            1001
             Big C Hyderabad 1211                          0           37892
             Chota Loan_Top up 2211                        0             129
             DR ON CALL 1808                               0            1519
             Hinduja Global Solutions 1211                 0           37819
             INCOMPLETE INFO 2010                          0             225
             INCOMPLETE_INFO 1309                          0             953
             ISS Mumbai 1211                               0           38244
             MUTHOOT GOLD CAMPAIGN 2209                    0            1242
             MUTHOOT GOLD LOAN 1310                        0             657
             MUTHOOT GOLD LOAN 1311                        0             486
             MUTHOOT GOLD LOAN 1411                        0            1738
             MUTHOOT GOLD LOAN 1610                        0            1269
             MUTHOOT GOLD LOAN 1810                        0            1221
             MUTHOOT GOLD LOAN 2010                        0            1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510               0             552
             Medplus EMP 1311                              0            1984
             Personal Loan_Top up 2211                     0             161
             Personal Loan_Top up 2211 New                 0             161
             Quess SMS 2211                                0             654
             TOPUP 1808                                    0            1480
hi           DTSS Delhi 1211                               0           40918
             DTSS Delhi 1311                               0            3223
             DTSS Delhi 1411                               0            3223
             UDS Delhi 1311                                0            4935
             UDS Delhi 1411                                0            4935
kn           Bangalore Tieups 1311                         0            3911
             Bangalore Tieups 1411                         0            3911
mr           ISS Mumbai 1311                               0           38244
             ISS Mumbai 1411                               0           38244
te           Big C Hyderabad 1311                          0             197
             Hinduja Global Solutions 1411                 0             128

                                              Status  Remark  Operator  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909            1001    1001      1001
             Big C Hyderabad 1211              37892   37892     37892
             Chota Loan_Top up 2211              129     129       129
             DR ON CALL 1808                    1519    1519      1519
             Hinduja Global Solutions 1211     37819   37819     37819
             INCOMPLETE INFO 2010                225     225       225
             INCOMPLETE_INFO 1309                953     953       953
             ISS Mumbai 1211                   38244   38244     38244
             MUTHOOT GOLD CAMPAIGN 2209         1242    1242      1242
             MUTHOOT GOLD LOAN 1310              657     657       657
             MUTHOOT GOLD LOAN 1311              486     486       486
             MUTHOOT GOLD LOAN 1411             1738    1738      1738
             MUTHOOT GOLD LOAN 1610             1269    1269      1269
             MUTHOOT GOLD LOAN 1810             1221    1221      1221
             MUTHOOT GOLD LOAN 2010             1630    1630      1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510     552     552       552
             Medplus EMP 1311                   1984    1984      1984
             Personal Loan_Top up 2211           161     161       161
             Personal Loan_Top up 2211 New       161     161       161
             Quess SMS 2211                      654     654       654
             TOPUP 1808                         1480    1480      1480
hi           DTSS Delhi 1211                   40918   40918     40918
             DTSS Delhi 1311                    3223    3223      3223
             DTSS Delhi 1411                    3223    3223      3223
             UDS Delhi 1311                     4935    4935      4935
             UDS Delhi 1411                     4935    4935      4935
kn           Bangalore Tieups 1311              3911    3911      3911
             Bangalore Tieups 1411              3911    3911      3911
mr           ISS Mumbai 1311                   38244   38244     38244
             ISS Mumbai 1411                   38244   38244     38244
te           Big C Hyderabad 1311                197     197       197
             Hinduja Global Solutions 1411       128     128       128

                                              Circle  Delivered Date  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909            1001            1001
             Big C Hyderabad 1211              37892           37892
             Chota Loan_Top up 2211              129             129
             DR ON CALL 1808                    1519            1519
             Hinduja Global Solutions 1211     37819           37819
             INCOMPLETE INFO 2010                225             225
             INCOMPLETE_INFO 1309                953             953
             ISS Mumbai 1211                   38244           38244
             MUTHOOT GOLD CAMPAIGN 2209         1242            1242
             MUTHOOT GOLD LOAN 1310              657             657
             MUTHOOT GOLD LOAN 1311              486             486
             MUTHOOT GOLD LOAN 1411             1738            1738
             MUTHOOT GOLD LOAN 1610             1269            1269
             MUTHOOT GOLD LOAN 1810             1221            1221
             MUTHOOT GOLD LOAN 2010             1630            1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510     552             552
             Medplus EMP 1311                   1984            1984
             Personal Loan_Top up 2211           161             161
             Personal Loan_Top up 2211 New       161             161
             Quess SMS 2211                      654             654
             TOPUP 1808                         1480            1480
hi           DTSS Delhi 1211                   40918           40918
             DTSS Delhi 1311                    3223            3223
             DTSS Delhi 1411                    3223            3223
             UDS Delhi 1311                     4935            4935
             UDS Delhi 1411                     4935            4935
kn           Bangalore Tieups 1311              3911            3911
             Bangalore Tieups 1411              3911            3911
mr           ISS Mumbai 1311                   38244           38244
             ISS Mumbai 1411                   38244           38244
te           Big C Hyderabad 1311                197             197
             Hinduja Global Solutions 1411       128             128

                                              Delivery Time  Hour of Day  \
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909                   1001         1001
             Big C Hyderabad 1211                     37892        37892
             Chota Loan_Top up 2211                     129          129
             DR ON CALL 1808                           1519         1519
             Hinduja Global Solutions 1211            37819        37819
             INCOMPLETE INFO 2010                       225          225
             INCOMPLETE_INFO 1309                       953          953
             ISS Mumbai 1211                          38244        38244
             MUTHOOT GOLD CAMPAIGN 2209                1242         1242
             MUTHOOT GOLD LOAN 1310                     657          657
             MUTHOOT GOLD LOAN 1311                     486          486
             MUTHOOT GOLD LOAN 1411                    1738         1738
             MUTHOOT GOLD LOAN 1610                    1269         1269
             MUTHOOT GOLD LOAN 1810                    1221         1221
             MUTHOOT GOLD LOAN 2010                    1630         1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510            552          552
             Medplus EMP 1311                          1984         1984
             Personal Loan_Top up 2211                  161          161
             Personal Loan_Top up 2211 New              161          161
             Quess SMS 2211                             654          654
             TOPUP 1808                                1480         1480
hi           DTSS Delhi 1211                          40918        40918
             DTSS Delhi 1311                           3223         3223
             DTSS Delhi 1411                           3223         3223
             UDS Delhi 1311                            4935         4935
             UDS Delhi 1411                            4935         4935
kn           Bangalore Tieups 1311                     3911         3911
             Bangalore Tieups 1411                     3911         3911
mr           ISS Mumbai 1311                          38244        38244
             ISS Mumbai 1411                          38244        38244
te           Big C Hyderabad 1311                       197          197
             Hinduja Global Solutions 1411              128          128

                                              Day of Week
SMS Language Broadcast name
en           BB INCOMPLETE INFO 0909                 1001
             Big C Hyderabad 1211                   37892
             Chota Loan_Top up 2211                   129
             DR ON CALL 1808                         1519
             Hinduja Global Solutions 1211          37819
             INCOMPLETE INFO 2010                     225
             INCOMPLETE_INFO 1309                     953
             ISS Mumbai 1211                        38244
             MUTHOOT GOLD CAMPAIGN 2209              1242
             MUTHOOT GOLD LOAN 1310                   657
             MUTHOOT GOLD LOAN 1311                   486
             MUTHOOT GOLD LOAN 1411                  1738
             MUTHOOT GOLD LOAN 1610                  1269
             MUTHOOT GOLD LOAN 1810                  1221
             MUTHOOT GOLD LOAN 2010                  1630
             MUTHOOT GOLD LOAN CAMPAIGN 0510          552
             Medplus EMP 1311                        1984
             Personal Loan_Top up 2211                161
             Personal Loan_Top up 2211 New            161
             Quess SMS 2211                           654
             TOPUP 1808                              1480
hi           DTSS Delhi 1211                        40918
             DTSS Delhi 1311                         3223
             DTSS Delhi 1411                         3223
             UDS Delhi 1311                          4935
             UDS Delhi 1411                          4935
kn           Bangalore Tieups 1311                   3911
             Bangalore Tieups 1411                   3911
mr           ISS Mumbai 1311                        38244
             ISS Mumbai 1411                        38244
te           Big C Hyderabad 1311                     197
             Hinduja Global Solutions 1411            128

In [24]:
campp_sms_delivery_df[campp_sms_delivery_df["SMS Language"] == "te"]['Message'].iloc[0]

'ప్రియమైన కస్టమర్, అభినందనలు! మీ కంపెనీ మా ప్రత్యేకమైన శుభ్ సాథీ భాగస్వామి అయినందున, మీరు ఆకర్షణీయమైన వడ్డీ రేటుతో MyShubhLife ద్వారా రుణం కోసం ముందగా ఆమోదించబడ్డారు. కనీస వేతనం రూ.12,000. ఇప్పుడే రుణం పొందేందుకు https://mv343.app.goo.gl/JdxK ని క్లిక్ చేయండి! - టీమ్ MyShubhLife'

In [76]:
campp_sms_delivery_df[campp_sms_delivery_df["SMS Language"] == "hi"]["Message"].iloc[0]

'प्रिय ग्राहक, बधाई! आपकी कंपनी हमारा अनन्य शुभ साथी भागीदार ह। इसलिए आपको MyShubhLife द्वारा आकर्षक ब्याज दर पर ऋण के लिए पूर्व-अनुमोदित किया गया है। न्यूनतम वेतन आवश्यक रु.12,000. अभी लाभ उठाने के लिए https://mv343.app.goo.gl/3Pbh क्लिक करें! - टीम MyShubhLife'

In [77]:
campp_sms_delivery_df[campp_sms_delivery_df["SMS Language"] == "mr"]["Message"].iloc[0]

'प्रिय ग्राहक, अभिनंदन! तुमची कंपनी आमचा शुभ साथी भागीदार असल्याने, तुम्हाला MyShubhLife द्वारे आकर्षक व्याजदरावर कर्जासाठी पूर्व-मंजूर केले आहे. किमान पगार आवश्यक आहे रु.12,000. आता लाभ घेण्यासाठी https://mshblf.page.link/gKGp वर क्लिक करा! - टीम MyShubhLife'

In [11]:
## Report
camp_sms_click_df = pd.DataFrame()

for file in camp_clickreport_filename_list:
    
    temp_delivery_df = pd.read_csv(f'{camp_path_to_reports}/{file}')
    camp_sms_click_df = pd.concat([camp_sms_click_df, temp_delivery_df])
    
camp_sms_click_df.reset_index(inplace=True, drop=True)
camp_sms_click_df = camp_sms_click_df[camp_sms_click_df['Delivered Time']!='-']

In [12]:
camp_sms_click_df['Delivered Date'] = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Delivery Time']  = camp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Hour of Day'] = camp_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
camp_sms_click_df['Day of Week'] = camp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

camp_sms_click_df['Clicked Date'] = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
camp_sms_click_df['Click Time']  = camp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
camp_sms_click_df['Clicked Hour of Day'] = camp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [13]:
camp_sms_dff = pd.merge(camp_sms_click_df, camp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [14]:
## Report from 2021
campp_sms_click_df = pd.DataFrame()

for file in campp_clickreport_filename_list:
    
    temp_delivery_df = pd.read_csv(f'{campp_path_to_reports}/{file}')
    campp_sms_click_df = pd.concat([campp_sms_click_df, temp_delivery_df])
    
campp_sms_click_df.reset_index(inplace=True, drop=True)
campp_sms_click_df = campp_sms_click_df[campp_sms_click_df['Delivered Time']!='-']

In [15]:
campp_sms_click_df['Delivered Date'] = campp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
campp_sms_click_df['Delivery Time']  = campp_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
campp_sms_click_df['Hour of Day'] = campp_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
campp_sms_click_df['Day of Week'] = campp_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

campp_sms_click_df['Clicked Date'] = campp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
campp_sms_click_df['Click Time']  = campp_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
campp_sms_click_df['Clicked Hour of Day'] = campp_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [16]:
campp_sms_dff = pd.merge(campp_sms_click_df, campp_sms_delivery_df, on=['Broadcast ID', 
                                            'Broadcast name',
                                            'Mobile number',
                                            'Primary Key (User_id)',
                                            'Delivered Time',
                                            'Delivered Date','Delivery Time',
                                            'Hour of Day','Day of Week'], how='outer')

In [16]:
# comm_dir_path = r'/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Multilingual EMI Reminders/Reports'
# comm_filename_list = []
# for path in os.scandir(comm_dir_path):
#     if path.is_file():
#         comm_filename_list.append(path.name)

In [17]:
# comm_clickreport_filename_list = [i for i in comm_filename_list if 'Click' in i]
# comm_delvreport_filename_list = [i for i in comm_filename_list if 'Delivery' in i]

# comm_path_to_reports = '/home/myshubhlife/Projects/Marketing SMS Campaign Optimization/Sourav Work/Multilingual EMI Reminders/Reports'

# comm_sms_delivery_df = pd.DataFrame()

# for file in comm_delvreport_filename_list:
    
#     comm_temp_delivery_df = pd.read_csv(f'{comm_path_to_reports}/{file}')
#     comm_sms_delivery_df = pd.concat([comm_sms_delivery_df, comm_temp_delivery_df])
    
# comm_sms_delivery_df.rename(columns={'Delivered time':'Delivered Time'}, inplace=True)
# comm_sms_delivery_df.reset_index(inplace=True, drop=True)

In [18]:
# comm_sms_delivery_df['Delivered Date'] = comm_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
# comm_sms_delivery_df['Delivery Time'] = comm_sms_delivery_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
# comm_sms_delivery_df['Hour of Day'] = comm_sms_delivery_df['Delivery Time'].apply(lambda x: x.split(':')[0])
# comm_sms_delivery_df['Day of Week'] = comm_sms_delivery_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))
# comm_sms_delivery_df['SMS Language'] = comm_sms_delivery_df['Broadcast name'].apply(lambda x: x.split(' - ')[1])

In [19]:
# comm_sms_click_df = pd.DataFrame()

# for file in comm_clickreport_filename_list:
    
#     temp_delivery_df = pd.read_csv(f'{comm_path_to_reports}/{file}')
#     comm_sms_click_df = pd.concat([comm_sms_click_df, temp_delivery_df])
    
# comm_sms_click_df.reset_index(inplace=True, drop=True)
# comm_sms_click_df = comm_sms_click_df[comm_sms_click_df['Delivered Time']!='-']

In [20]:
# comm_sms_click_df['Delivered Date'] = comm_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[0])
# comm_sms_click_df['Delivery Time']  = comm_sms_click_df['Delivered Time'].apply(lambda x: x.split(' ')[1])
# comm_sms_click_df['Hour of Day'] = comm_sms_click_df['Delivery Time'].apply(lambda x: x.split(':')[0])
# comm_sms_click_df['Day of Week'] = comm_sms_click_df['Delivered Date'].apply(lambda x: convert_to_day_of_week(x))

# comm_sms_click_df['Clicked Date'] = comm_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[0])
# comm_sms_click_df['Click Time']  = comm_sms_click_df['Clicked time'].apply(lambda x: x.split(' ')[1])
# comm_sms_click_df['Clicked Hour of Day'] = comm_sms_click_df['Click Time'].apply(lambda x: x.split(':')[0])

In [21]:
# comm_sms_dff = pd.merge(comm_sms_click_df, comm_sms_delivery_df, on=['Broadcast ID', 
#                                             'Broadcast name',
#                                             'Mobile number',
#                                             'Primary Key (User_id)',
#                                             'Delivered Time',
#                                             'Delivered Date','Delivery Time',
#                                             'Hour of Day','Day of Week'], how='outer')

In [17]:
all_sms = pd.concat([camp_sms_dff, campp_sms_dff]) #, comm_sms_dff])
all_sms.reset_index(drop=True, inplace=True)

In [18]:
# all_sms = all_sms.drop(['Unnamed: 0', 'myshubhlife',
#                            'myshubhlife-Latitude-7480', '26.07.2022 14:48',
#                            'file:///home/myshubhlife/.config/libreoffice/4;'], axis=1)

In [28]:
cmpgn_category_df = pd.read_csv('/home/aamin/files/marketing/copy/click_rate_cmpgn_wise.csv', usecols=[0,1,2])

In [29]:
all_sms = all_sms.merge(cmpgn_category_df[['Broadcast name','category']], on='Broadcast name', how='left')

In [30]:
all_sms['category'].value_counts()

leads             389804
existing users     21191
Name: category, dtype: int64

In [78]:
all_sms["SMS Language"].value_counts()

en    443249
mr     76488
hi     57234
kn      7822
te       325
Name: SMS Language, dtype: int64

In [31]:
all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

,Broadcast ID,Broadcast name,Mobile number,Primary Key (User_id),Link clicked,Delivered Time,Clicked time,Delivered Date,Delivery Time,Hour of Day,Day of Week,Clicked Date,Click Time,Clicked Hour of Day,Message,Published date,Status,Remark,Operator,Circle,SMS Language,category
85,4862,Quess 3105,7550176840,QUESS1164,https://bit.ly/3KWO3qd,2022-05-31 08:02:24,2022-05-31 19:33:50,2022-05-31,08:02:24,08,Tuesday,2022-05-31,19:33:50,19,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Idea,Madhya Pradesh-Chattisgarh,en,leads
86,4862,Quess 3105,8920194583,QUESS737,https://bit.ly/3KWO3qd,2022-05-31 08:02:28,2022-05-31 20:18:12,2022-05-31,08:02:28,08,Tuesday,2022-05-31,20:18:12,20,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Airtel,Madhya Pradesh-Chattisgarh,en,leads
87,4862,Quess 3105,8860875024,QUESS612,https://bit.ly/3KWO3qd,2022-05-31 08:02:27,2022-06-18 10:50:57,2022-05-31,08:02:27,08,Tuesday,2022-06-18,10:50:57,10,"Dear Customer, Please download the MyShubhLIfe...",NaN,Delivered,Delivered,Airtel,Delhi,en,leads
88,5084,RNR Cases 3006,7095924021,RNR544,https://mv343.app.goo.gl/pQxK,2022-06-30 10:13:28,2022-06-30 10:13:38,2022-06-30,10:13:28,10,Thursday,2022-06-30,10:13:38,10,"Dear Customer, We noticed your interest in a M...",NaN,Delivered,Delivered,BSNL GSM,Tamil Nadu,en,leads
89,5084,RNR Cases 3006,9494080943,RNR555,https://mv343.app.goo.gl/pQxK,2022-06-30 10:12:14,2022-06-30 10:12:19,2022-06-30,10:12:14,10,Thursday,2022-06-30,10:12:19,10,"Dear Customer, We noticed your interest in a M...",NaN,Delivered,Delivered,Vodafone,Chennai,en,leads
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585113,3169,Bangalore Tieups 1411,9341838144,BANGALORE3102,NaN,2021-11-14 14:03:06,NaN,2021-11-14,14:03:06,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance CDMA,Karnataka,kn,leads
585114,3169,Bangalore Tieups 1411,9731077561,BANGALORE1474,NaN,2021-11-14 14:03:22,NaN,2021-11-14,14:03:22,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,kn,leads
585115,3169,Bangalore Tieups 1411,8217085312,BANGALORE2732,NaN,2021-11-14 14:04:14,NaN,2021-11-14,14:04:14,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Reliance JIO,Karnataka,kn,leads
585116,3169,Bangalore Tieups 1411,8496878926,BANGALORE400,NaN,2021-11-14 14:03:03,NaN,2021-11-14,14:03:03,14,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,Delivered,Delivered,Vodafone,Karnataka,kn,leads
585117,3169,Bangalore Tieups 1411,9611898924,BANGALORE1427,NaN,2021-11-14 20:03:20,NaN,2021-11-14,20:03:20,20,Sunday,NaN,NaN,NaN,"ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ...",NaN,undelivered,undelivered,Idea,Karnataka,kn,leads

In [32]:
df_to_use = all_sms[(all_sms['category']=='leads')|(all_sms['category']!=all_sms['category'])]

In [34]:
df_to_use.to_csv("reports_before_nov_dec.csv")

In [40]:
# df_to_use.drop(['category'], axis=1, inplace=True)

/home/aamin/.local/lib/python3.8/site-packages/pandas/core/frame.py:4167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [50]:
# df_to_use.loc[585113,"Message"]

'ಆತ್ಮೀಯ ಗ್ರಾಹಕರೆ, ಅಭಿನಂದನೆಗಳು! ನಿಮ್ಮ ಕಂಪನಿಯು ನಮ್ಮ ವಿಶೇಷವಾದ ಶುಭ್ ಸಾಥಿ ಪಾಲುದಾರರಾಗಿರುವುದರಿಂದ, ನೀವು MyShubhLife ನಿಂದ ಆಕರ್ಷಕ ಬಡ್ಡಿ ದರದಲ್ಲಿ ಲೋನ್\u200cಗಾಗಿ ಮುಂಗಡವಾಗಿ ಅನುಮೋದಿಸಲ್ಪಟ್ಟಿದ್ದೀರಿ. ಅಗತ್ಯವಿರುವ ಕನಿಷ್ಠ ವೇತನ ರೂ.12,000. ಇದೀಗ ಪಡೆಯಲು https://mv343.app.goo.gl/JdxK ಕ್ಲಿಕ್ ಮಾಡಿ! - MyShubhLife ತಂಡ'

In [58]:
# import re 
# if re.match('[a-zA-Z]',df_to_use.loc[85,"Message"]):
#     print("English")
# elif re.match('[a-zA-Z]',df_to_use.loc[85,"Message"])

English

In [ ]:
# df_to_use["Message"].value_counts()

In [62]:
# re.match('[\u0900-\u097F]+',df_to_use.loc[312977,"Message"])

In [ ]:
# import re 

# df_to_use[df_to_use["Message"].str.contains('प्रिय')]

def convert_df_for_delivery(df):
    
    df_copy = df.copy()
    
    for i, row in df_copy.iterrows():
        if (row['Clicked Date'] == row['Clicked Date']) and (row['Message'] != row['Message']):
            df_copy.at[i, 'Status'] = 'Delivered'
            df_copy.at[i, 'Remark'] = 'Delivered'
            df_copy.at[i, 'Message'] = df_copy['Message'].value_counts().index[0]
            df_copy.at[i, 'Operator'] = df_copy['Operator'].value_counts().index[0]
            df_copy.at[i, 'Circle'] = df_copy['Circle'].value_counts().index[0]
            df_copy.at[i, 'SMS Language'] = df_copy['SMS Language'].value_counts().index[0]
            #df_copy.at[i, 'SMS Length'] = len(row['Message'])
            
    for i, row in df_copy.iterrows():
        df_copy.at[i, 'SMS Length'] = len(row['Message'])
    
    return df_copy

mob_nums = df_to_use[df_to_use['Message']!=df_to_use['Message']]['Mobile number'].unique().tolist()
to_impute = df_to_use[df_to_use['Mobile number'].isin(mob_nums)]
no_impute = df_to_use[~df_to_use['Mobile number'].isin(mob_nums)]

mob_nums

groupby_df = to_impute.groupby(['Mobile number',
                              'Primary Key (User_id)'
                             ]).apply(convert_df_for_delivery)

groupby_df

groupby_df2 = groupby_df.droplevel(level=0)
groupby_df2.reset_index(drop=True, inplace=True)

prepared_df = pd.concat([groupby_df2, no_impute]).reset_index(drop=True)

In [79]:
all_reports = pd.read_csv("/home/aamin/files/marketing/copy/reports_data/all_reports_data.csv")

/home/aamin/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3106: DtypeWarning: Columns (6,8,13,14,23) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [80]:
# df = df_to_use[df_to_use['Circle']!='-']
# df = df[df['Operator']!='-']

df = all_reports[all_reports['Circle']!='-']
df = df[df['Operator']!='-']

In [81]:
df['SMS Length'] = df['Message'].apply(lambda x: len(x) if x==x else np.nan)

In [82]:
df.shape

(627661, 25)

In [83]:
import time
from datetime import datetime
from dateutil import parser

def func_UTCToEpoch(utcData, timestampFormat=None):
    if timestampFormat == None:
        dateObj    = parser.parse(utcData)
        epochValue = dateObj.timestamp()
    else:
        timeTuple  = time.strptime(utcData, timestampFormat)
        epochValue = time.mktime(timeTuple)
    return (epochValue)

In [84]:
import dateutil.relativedelta

def calculate_timelag(delv_time, click_time):
    
    if click_time == click_time:
        delv_time_ts = datetime.fromtimestamp(func_UTCToEpoch(delv_time))
        click_time_ts = datetime.fromtimestamp(func_UTCToEpoch(click_time))
        diff = click_time_ts - delv_time_ts
        seconds = diff.total_seconds()
    
    else:
        seconds = np.nan
    
    return seconds

In [85]:
df['Timelag (s)'] = df.apply(lambda x: calculate_timelag(x['Delivered Time'], x['Clicked time']), axis=1)

In [86]:
df = df[~(df['Timelag (s)'] < -10)]

In [87]:
df['Timelag (s)'] = df['Timelag (s)'].apply(lambda x: abs(x) if x==x else np.nan)

In [88]:
#df['SMS Length'] = len(df['Message'])
df['Num SMS Sent'] = np.ceil(df['SMS Length']/160)
df['Cost of All SMS Sent'] = 0.13 * df['Num SMS Sent'] #  cost_of_sms

In [89]:
df['Num words in SMS'] = df['Message'].apply(lambda x: len(x.split(' ')))

In [91]:
df = df.drop(["Unnamed: 0"	,"Unnamed: 0.1"], axis=1)

In [92]:
def convert_to_day_of_month(date_str):
    try:
        day_of_mon = datetime.fromtimestamp(func_UTCToEpoch(date_str)).day
    except:
        day_of_mon = np.nan
    return day_of_mon

In [93]:
df['Day of Month'] = df['Delivered Date'].apply(convert_to_day_of_month)

In [94]:
def mean_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    mean = np.nanmean(x_upd)
    return mean

def median_wo_0(x):
    x_upd = [i for i in x.values if i!=0]
    median = np.nanmedian(x_upd)
    return median

In [95]:
timelag = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Timelag (s)'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
timelag.rename(columns= {'mean': 'Avg Timelag (s)',
                        'median': 'Median Timelag (s)',
                         'mean_wo_0': 'Avg Timelag (s) wo 0',
                        'median_wo_0': 'Median Timelag (s) wo 0',
                        }, inplace=True)

/tmp/ipykernel_220876/3554248693.py:3: RuntimeWarning: Mean of empty slice
  mean = np.nanmean(x_upd)
/home/aamin/.local/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,

In [96]:
num_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_sms.rename(columns= {'mean': 'Avg Num SMS Sent',
                        'median': 'Median Num SMS Sent',
                        'mean_wo_0': 'Avg Num SMS Sent wo 0',
                        'median_wo_0': 'Median Num SMS Sent wo 0',
                        }, inplace=True)

In [97]:
cost_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Cost of All SMS Sent'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
cost_sms.rename(columns= {'mean': 'Avg Cost of All SMS Sent',
                        'median': 'Median Cost of All SMS Sent',
                         'mean_wo_0': 'Avg Cost of All SMS Sent wo 0',
                        'median_wo_0': 'Median Cost of All SMS Sent wo 0'}, inplace=True)

In [98]:
len_sms = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['SMS Length'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
len_sms.rename(columns= {'mean': 'Avg SMS Length',
                        'median': 'Median SMS Length',
                        'mean_wo_0': 'Avg SMS Length wo 0',
                        'median_wo_0': 'Median SMS Length wo 0'}, inplace=True)

In [99]:
day_of_mon = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Day of Month'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
day_of_mon.rename(columns= {'mean': 'Avg Day of Month',
                        'median': 'Median Day of Month',
                           'mean_wo_0': 'Avg Day of Month wo 0',
                        'median_wo_0': 'Median Day of Month wo 0'}, inplace=True)

In [100]:
num_words = pd.DataFrame(df.groupby(by = ['Circle', 
                                        'SMS Language',
                                        'Day of Week',
                                        'Hour of Day'])['Num words in SMS'].agg([np.mean, np.median, mean_wo_0, median_wo_0]))
num_words.rename(columns= {'mean': 'Avg Num Words',
                        'median': 'Median Num Words',
                          'mean_wo_0': 'Avg Num Words wo 0',
                        'median_wo_0': 'Median Num Words wo 0'}, inplace=True)

In [101]:
new_features = pd.merge(num_sms,cost_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,len_sms, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,timelag, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,day_of_mon, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

new_features = pd.merge(new_features,num_words, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [102]:
new_features.fillna(0, inplace = True)

In [103]:
new_features

                                                                  Avg Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                         2.0
                                                     9                         2.0
                                                     10                        2.0
                                                     11                        2.0
                                                     12                        2.0
...                                                                            ...
West Bengal-Andaman Nicobar mr           Saturday    10                        2.0
                                                     11                        2.0
                                                     16                        2.0
                                         Sunday      14                        2.0
                                                     20                        2.0

                                                                  Median Num SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                            2.0
                                                     9                            2.0
                                                     10                           2.0
                                                     11                           2.0
                                                     12                           2.0
...                                                                               ...
West Bengal-Andaman Nicobar mr           Saturday    10                           2.0
                                                     11                           2.0
                                                     16                           2.0
                                         Sunday      14                           2.0
                                                     20                           2.0

                                                                  Avg Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                              2.0
                                                     9                              2.0
                                                     10                             2.0
                                                     11                             2.0
                                                     12                             2.0
...                                                                                 ...
West Bengal-Andaman Nicobar mr           Saturday    10                             2.0
                                                     11                             2.0
                                                     16                             2.0
                                         Sunday      14                             2.0
                                                     20                             2.0

                                                                  Median Num SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                 2.0
                                                     9                                 2.0
                                                     10                                2.0
                                                     11                                2.0
                                                     12                                2.0
...                                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                                2.0
                                                     11                                2.0
                                                     16                                2.0
                                         Sunday      14                                2.0
                                                     20                                2.0

                                                                  Avg Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                0.26
                                                     9                                0.26
                                                     10                               0.26
                                                     11                               0.26
                                                     12                               0.26
...                                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                               0.26
                                                     11                               0.26
                                                     16                               0.26
                                         Sunday      14                               0.26
                                                     20                               0.26

                                                                  Median Cost of All SMS Sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                   0.26
                                                     9                                   0.26
                                                     10                                  0.26
                                                     11                                  0.26
                                                     12                                  0.26
...                                                                                       ...
West Bengal-Andaman Nicobar mr           Saturday    10                                  0.26
                                                     11                                  0.26
                                                     16                                  0.26
                                         Sunday      14                                  0.26
                                                     20                                  0.26

                                                                  Avg Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                     0.26
                                                     9                                     0.26
                                                     10                                    0.26
                                                     11                                    0.26
                                                     12                                    0.26
...                                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10                                    0.26
                                                     11                                    0.26
                                                     16                                    0.26
                                         Sunday      14                                    0.26
                                                     20                                    0.26

                                                                  Median Cost of All SMS Sent wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                        0.26
                                                     9                                        0.26
                                                     10                                       0.26
                                                     11                                       0.26
                                                     12                                       0.26
...                                                                                            ...
West Bengal-Andaman Nicobar mr           Saturday    10                                       0.26
                                                     11                                       0.26
                                                     16                                       0.26
                                         Sunday      14                                       0.26
                                                     20                                       0.26

                                                                  Avg SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                240.000000
                                                     9                197.000000
                                                     10               239.972196
                                                     11               239.969930
                                                     12               263.419355
...                                                                          ...
West Bengal-Andaman Nicobar mr           Saturday    10               258.000000
                                                     11               258.000000
                                                     16               258.000000
                                         Sunday      14               258.000000
                                                     20               258.000000

                                                                  Median SMS Length  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                        240.0
                                                     9                        197.0
                                                     10                       240.0
                                                     11                       240.0
                                                     12                       268.0
...                                                                             ...
West Bengal-Andaman Nicobar mr           Saturday    10                       258.0
                                                     11                       258.0
                                                     16                       258.0
                                         Sunday      14                       258.0
                                                     20                       258.0

                                                                  Avg SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                     240.000000
                                                     9                     197.000000
                                                     10                    239.972196
                                                     11                    239.969930
                                                     12                    263.419355
...                                                                               ...
West Bengal-Andaman Nicobar mr           Saturday    10                    258.000000
                                                     11                    258.000000
                                                     16                    258.000000
                                         Sunday      14                    258.000000
                                                     20                    258.000000

                                                                  Median SMS Length wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                             240.0
                                                     9                             197.0
                                                     10                            240.0
                                                     11                            240.0
                                                     12                            268.0
...                                                                                  ...
West Bengal-Andaman Nicobar mr           Saturday    10                            258.0
                                                     11                            258.0
                                                     16                            258.0
                                         Sunday      14                            258.0
                                                     20                            258.0

                                                                  Avg Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                   0.000000
                                                     9                2497.259740
                                                     10              15765.801282
                                                     11                  2.482143
                                                     12               7641.757009
...                                                                           ...
West Bengal-Andaman Nicobar mr           Saturday    10                 44.666667
                                                     11                  0.000000
                                                     16                  0.000000
                                         Sunday      14                  5.333333
                                                     20                  0.000000

                                                                  Median Timelag (s)  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                           0.0
                                                     9                           3.0
                                                     10                          2.0
                                                     11                          2.0
                                                     12                         25.0
...                                                                              ...
West Bengal-Andaman Nicobar mr           Saturday    10                         49.0
                                                     11                          0.0
                                                     16                          0.0
                                         Sunday      14                          4.0
                                                     20                          0.0

                                                                  Avg Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                        0.000000
                                                     9                     2497.259740
                                                     10                   19488.629160
                                                     11                       2.673077
                                                     12                    7938.524272
...                                                                                ...
West Bengal-Andaman Nicobar mr           Saturday    10                      44.666667
                                                     11                       0.000000
                                                     16                       0.000000
                                         Sunday      14                       5.333333
                                                     20                       0.000000

                                                                  Median Timelag (s) wo 0  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                                0.0
                                                     9                                3.0
                                                     10                               2.0
                                                     11                               2.0
                                                     12                              26.0
...                                                                                   ...
West Bengal-Andaman Nicobar mr           Saturday    10                              49.0
                                                     11                               0.0
                                                     16                               0.0
                                         Sunday      14                               4.0
                                                     20                               0.0

                                                                  Avg Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                   25.000000
                                                     9                   24.000000
                                                     10                   2.014225
                                                     11                   9.020280
                                                     12                  11.649770
...                                                                            ...
West Bengal-Andaman Nicobar mr           Saturday    10                  13.000000
                                                     11                  13.000000
                                                     16                  13.000000
                                         Sunday      14                  14.000000
                                                     20                  14.000000

                                                                  Median Day of Month  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                           25.0
                                                     9                           24.0
                                                     10                           2.0
                                                     11                          16.0
                                                     12                          12.0
...                                                                               ...
West Bengal-Andaman Nicobar mr           Saturday    10                          13.0
                                                     11                          13.0

In [104]:
circle_df = pd.DataFrame(df.groupby(by = ['Circle', 
                                        #   'Operator',
                                          'SMS Language','Day of Week','Hour of Day']).Status.count())
circle_df.rename(columns= {'Status': 'sms_sent'}, inplace=True)
circle_df

                                                                  sms_sent
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                   2
                                                     9                 461
                                                     10              13919
                                                     11               2860
                                                     12                868
...                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                 50
                                                     11                  1
                                                     16                  1
                                         Sunday      14                 50
                                                     20                  2

[2715 rows x 1 columns]

In [105]:
circle_delv= pd.DataFrame(df[df['Status']=='Delivered'].groupby(by = ['Circle','SMS Language','Day of Week','Hour of Day']).Status.count())
circle_delv.rename(columns= {'Status': 'sms_delivered'}, inplace=True)
circle_delv

                                                                  sms_delivered
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      9                      438
                                                     10                    7784
                                                     11                     591
                                                     12                     646
                                                     13                      10
...                                                                         ...
West Bengal-Andaman Nicobar kn           Sunday      14                       3
                                                     19                       1
                            mr           Saturday    10                      47
                                                     11                       1
                                         Sunday      14                      47

[2036 rows x 1 columns]

In [106]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [107]:
circle_delv_rate_df = pd.merge(circle_df,circle_delv, how= 'outer', 
               on = ['Circle','SMS Language',
                     'Day of Week','Hour of Day'])

In [108]:
circle_delv_rate_df.fillna(0, inplace = True)
circle_delv_rate_df['delivery_rate'] = circle_delv_rate_df['sms_delivered']*100 / circle_delv_rate_df['sms_sent']
circle_delv_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                   2
                                                     9                 461
                                                     10              13919
                                                     11               2860
                                                     12                868
...                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                 50
                                                     11                  1
                                                     16                  1
                                         Sunday      14                 50
                                                     20                  2

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                      0.0
                                                     9                    438.0
                                                     10                  7784.0
                                                     11                   591.0
                                                     12                   646.0
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10                    47.0
                                                     11                     1.0
                                                     16                     0.0
                                         Sunday      14                    47.0
                                                     20                     0.0

                                                                  delivery_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                 0.000000
                                                     9                95.010846
                                                     10               55.923558
                                                     11               20.664336
                                                     12               74.423963
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10               94.000000
                                                     11              100.000000
                                                     16                0.000000
                                         Sunday      14               94.000000
                                                     20                0.000000

[2715 rows x 3 columns]

In [109]:
click= pd.DataFrame(df[df['Clicked Date']==df['Clicked Date']].groupby(by = ['Circle', 'SMS Language',
                                                                                           'Day of Week','Hour of Day']
                                                                                    ).Status.count())
click.rename(columns= {'Status': 'sms_clicked'}, inplace=True)
click

                                                                  sms_clicked
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      9                     77
                                                     10                   780
                                                     11                    56
                                                     12                   107
                                                     14                    32
...                                                                       ...
West Bengal-Andaman Nicobar hi           Sunday      14                    22
                                         Thursday    10                    18
                                                     16                     9
                            mr           Saturday    10                     3
                                         Sunday      14                     3

[1226 rows x 1 columns]

In [110]:
click_rate_df = pd.merge(circle_delv_rate_df,click, how= 'outer', 
                         on = ['Circle','SMS Language','Day of Week','Hour of Day'])
click_rate_df.fillna(0, inplace = True)
click_rate_df['clicked_rate'] = click_rate_df['sms_clicked']*100 / click_rate_df['sms_delivered']
click_rate_df.fillna(0, inplace = True)
click_rate_df

                                                                  sms_sent  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                   2
                                                     9                 461
                                                     10              13919
                                                     11               2860
                                                     12                868
...                                                                    ...
West Bengal-Andaman Nicobar mr           Saturday    10                 50
                                                     11                  1
                                                     16                  1
                                         Sunday      14                 50
                                                     20                  2

                                                                  sms_delivered  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                      0.0
                                                     9                    438.0
                                                     10                  7784.0
                                                     11                   591.0
                                                     12                   646.0
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10                    47.0
                                                     11                     1.0
                                                     16                     0.0
                                         Sunday      14                    47.0
                                                     20                     0.0

                                                                  delivery_rate  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                 0.000000
                                                     9                95.010846
                                                     10               55.923558
                                                     11               20.664336
                                                     12               74.423963
...                                                                         ...
West Bengal-Andaman Nicobar mr           Saturday    10               94.000000
                                                     11              100.000000
                                                     16                0.000000
                                         Sunday      14               94.000000
                                                     20                0.000000

                                                                  sms_clicked  \
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                    0.0
                                                     9                   77.0
                                                     10                 780.0
                                                     11                  56.0
                                                     12                 107.0
...                                                                       ...
West Bengal-Andaman Nicobar mr           Saturday    10                   3.0
                                                     11                   0.0
                                                     16                   0.0
                                         Sunday      14                   3.0
                                                     20                   0.0

                                                                  clicked_rate
Circle                      SMS Language Day of Week Hour of Day
Andhra Pradesh              en           Friday      2                0.000000
                                                     9               17.579909
                                                     10              10.020555
                                                     11               9.475465
                                                     12              16.563467
...                                                                        ...
West Bengal-Andaman Nicobar mr           Saturday    10               6.382979
                                                     11               0.000000
                                                     16               0.000000
                                         Sunday      14               6.382979
                                                     20               0.000000

[2715 rows x 5 columns]

In [111]:
final_df = pd.merge(click_rate_df,new_features, how= 'outer', 
               on = ['Circle',
                     'SMS Language',
                     'Day of Week','Hour of Day'])

In [112]:
final_df = final_df.reset_index()

In [113]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0
0,Andhra Pradesh,en,Friday,2,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.000000,240.0,240.000000,240.0,0.000000,0.0,0.000000,0.0,25.000000,25.0,25.000000,25.0,34.000000,34.0,34.000000,34.0
1,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0
2,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0
3,Andhra Pradesh,en,Friday,11,2860,591.0,20.664336,56.0,9.475465,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.969930,240.0,239.969930,240.0,2.482143,2.0,2.673077,2.0,9.020280,16.0,9.020280,16.0,33.996503,34.0,33.996503,34.0
4,Andhra Pradesh,en,Friday,12,868,646.0,74.423963,107.0,16.563467,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,263.419355,268.0,263.419355,268.0,7641.757009,25.0,7938.524272,26.0,11.649770,12.0,11.649770,12.0,36.509217,37.0,36.509217,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2710,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2711,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2712,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0
2713,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0
2714,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0

In [114]:
final_df['SN'] = np.arange(0,2715).tolist()

In [115]:
final_df

,Circle,SMS Language,Day of Week,Hour of Day,sms_sent,sms_delivered,delivery_rate,sms_clicked,clicked_rate,Avg Num SMS Sent,Median Num SMS Sent,Avg Num SMS Sent wo 0,Median Num SMS Sent wo 0,Avg Cost of All SMS Sent,Median Cost of All SMS Sent,Avg Cost of All SMS Sent wo 0,Median Cost of All SMS Sent wo 0,Avg SMS Length,Median SMS Length,Avg SMS Length wo 0,Median SMS Length wo 0,Avg Timelag (s),Median Timelag (s),Avg Timelag (s) wo 0,Median Timelag (s) wo 0,Avg Day of Month,Median Day of Month,Avg Day of Month wo 0,Median Day of Month wo 0,Avg Num Words,Median Num Words,Avg Num Words wo 0,Median Num Words wo 0,SN
0,Andhra Pradesh,en,Friday,2,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,240.000000,240.0,240.000000,240.0,0.000000,0.0,0.000000,0.0,25.000000,25.0,25.000000,25.0,34.000000,34.0,34.000000,34.0,0
1,Andhra Pradesh,en,Friday,9,461,438.0,95.010846,77.0,17.579909,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,197.000000,197.0,197.000000,197.0,2497.259740,3.0,2497.259740,3.0,24.000000,24.0,24.000000,24.0,29.000000,29.0,29.000000,29.0,1
2,Andhra Pradesh,en,Friday,10,13919,7784.0,55.923558,780.0,10.020555,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.972196,240.0,239.972196,240.0,15765.801282,2.0,19488.629160,2.0,2.014225,2.0,2.014225,2.0,33.996767,34.0,33.996767,34.0,2
3,Andhra Pradesh,en,Friday,11,2860,591.0,20.664336,56.0,9.475465,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,239.969930,240.0,239.969930,240.0,2.482143,2.0,2.673077,2.0,9.020280,16.0,9.020280,16.0,33.996503,34.0,33.996503,34.0,3
4,Andhra Pradesh,en,Friday,12,868,646.0,74.423963,107.0,16.563467,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,263.419355,268.0,263.419355,268.0,7641.757009,25.0,7938.524272,26.0,11.649770,12.0,11.649770,12.0,36.509217,37.0,36.509217,37.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2710,West Bengal-Andaman Nicobar,mr,Saturday,10,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,44.666667,49.0,44.666667,49.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2710
2711,West Bengal-Andaman Nicobar,mr,Saturday,11,1,1.0,100.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2711
2712,West Bengal-Andaman Nicobar,mr,Saturday,16,1,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,13.000000,13.0,13.000000,13.0,34.000000,34.0,34.000000,34.0,2712
2713,West Bengal-Andaman Nicobar,mr,Sunday,14,50,47.0,94.000000,3.0,6.382979,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,5.333333,4.0,5.333333,4.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2713
2714,West Bengal-Andaman Nicobar,mr,Sunday,20,2,0.0,0.000000,0.0,0.000000,2.0,2.0,2.0,2.0,0.26,0.26,0.26,0.26,258.000000,258.0,258.000000,258.0,0.000000,0.0,0.000000,0.0,14.000000,14.0,14.000000,14.0,34.000000,34.0,34.000000,34.0,2714

In [ ]:
final_df.to_csv('mkting_cmpgn_data_wo_existing_users_4.csv', index=False)